"""Feature registry: D (Competency), E (Role), F (Personalization), G (Tutor), H (iGOT)."""

from registry_common import F, category, IMPL, PART, MOCK, PLAN, BLOCK, HUMAN

API = "Planned internal API (docs/API_INTEGRATION_SPEC.md): "

# ------------------------------------------------ D. COMPETENCY INTELLIGENCE
category(
    "D", "CMP", "Competency intelligence", "Competency intelligence",
    "Learner", "Trainer; Competency framework administrator; Department administrator",
    "AI-012 (score calculation); ADM-004 (competency management)",
    "Adjustments only by authorised reviewers with a reason; learners can request corrections (RAI-018).",
    "Competency data is personal data: visible to the learner, assigned trainers and scoped administrators only; never used for automated employment decisions.",
    "Heatmaps and graphs have table equivalents; colour is never the only signal.",
)

F("CMP-001", "Learner competency profile", "P0",
  "Shows the learner's job role, competencies required by that role, current estimates, evidence-sufficiency bands and gaps.",
  "Single place for a learner to understand their development position.",
  "UserCompetency; RoleCompetency; framework metadata.",
  "None (displays deterministic estimates).",
  API + "GET /api/v1/me/competency-profile; GET /api/v1/users/{id}/competency-profile",
  "Competency profile screen.",
  "No estimates yet -> call to action to take the pre-assessment.",
  "Profile shows only the learner's own data (or scoped access); each estimate links to explanation and evidence.",
  "Skill passport (CMP-015).",
  deps="AI-012; AI-018; ROLE-001")

F("CMP-002", "Competency scores", "P0",
  "Numeric score and mapped level per competency with method version.",
  "Comparable measures over time.",
  "UserCompetency.",
  "None.",
  API + "Included in competency profile",
  "Score and level with band.",
  "Levels not configured -> score only with notice.",
  "Scores are reproducible from evidence and method version.",
  "IRT-based scaling (FUT-006).",
  deps="AI-012")

F("CMP-003", "Competency heatmap", "P1",
  "Grid of competencies by learners or departments coloured by level, with accessible table view.",
  "Quick visual scan of capability.",
  "Aggregated estimates with minimum group size.",
  "None.",
  API + "GET /api/v1/analytics/competency-heatmap (P1)",
  "Department heatmap screen.",
  "Group smaller than minimum -> cell suppressed.",
  "Heatmap never reveals individuals below the minimum group size to unauthorised roles.",
  "Trend overlays.",
  primary="Department administrator")

F("CMP-004", "Competency-gap analysis", "P0",
  "Detailed gap view: required vs estimated level, evidence, and recommended actions.",
  "Clear development priorities.",
  "Gaps (AI-002); recommendations.",
  "None.",
  API + "GET /api/v1/me/competency-gaps",
  "Competency-gap analysis screen.",
  "Insufficient evidence -> 'reassess to confirm' instead of a gap.",
  "Each gap shows required level, estimate, band, evidence link and at least one action or an 'no approved content' note.",
  "Critical skills (CMP-005).",
  deps="AI-002")

F("CMP-005", "Critical skills", "P1",
  "Marks competencies as critical for a role so their gaps are prioritised.",
  "Aligns development with role-critical work.",
  "RoleCompetency.is_critical.",
  "None.",
  API + "PUT /api/v1/job-roles/{id}/competencies (is_critical, P1)",
  "Critical badge in gap analysis.",
  "Unconfigured -> all equal.",
  "Critical flags set only by competency framework administrators.",
  "Weighted readiness (ROLE-008).",
  primary="Competency framework administrator")

F("CMP-006", "Strengths", "P0",
  "Lists competencies at or above the required level with sufficient evidence.",
  "Balanced, motivating view of capability.",
  "Estimates vs required levels.",
  "None.",
  API + "Included in competency profile",
  "Strengths section on profile.",
  "Insufficient evidence -> not listed as strength.",
  "A strength requires evidence sufficiency of at least 'medium'.",
  "Peer mentoring suggestions (P2).")

F("CMP-007", "Developing skills", "P0",
  "Lists competencies below the required level (gaps) in plain language.",
  "Non-judgemental framing of gaps.",
  "Gaps.",
  "None.",
  API + "Included in competency profile",
  "'Developing' section on profile.",
  "Same as CMP-004.",
  "Wording avoids evaluative labels about the person (UI_UX_SPEC.md content guidelines).",
  "Progress nudges (P1).")

F("CMP-008", "Required-versus-current comparison", "P0",
  "Side-by-side comparison of required and current levels per competency.",
  "Makes gaps concrete.",
  "RoleCompetency; UserCompetency.",
  "None.",
  API + "Included in competency-gap response",
  "Accessible comparison chart with table view.",
  "Missing required level -> 'not configured'.",
  "Chart and table show identical values; both are keyboard and screen-reader accessible.",
  "Target-role comparison (ROLE-010).")

F("CMP-009", "Competency dependencies", "P2",
  "Models prerequisite relations between competencies.",
  "Enables prerequisite-aware paths.",
  "Competency relations.",
  "None / expert-authored.",
  API + "Not defined until P2 design.",
  "Dependency editor (P2).",
  "Cycles -> rejected.",
  "Relations authored by competency administrators only.",
  "Competency graph (CMP-014).")

F("CMP-010", "Competency progression", "P1",
  "Shows how estimates changed across attempts.",
  "Evidence of development over time.",
  "Historical UserCompetency snapshots.",
  "None.",
  API + "GET /api/v1/me/competency-history (P1)",
  "Progression chart with table.",
  "Method version changed -> series break annotated.",
  "Series breaks are annotated when method versions differ.",
  "Forecasting (P2).")

F("CMP-011", "Knowledge tracking", "P2",
  "Tracks mastery of individual knowledge components.",
  "Fine-grained personalisation.",
  "Response-level data.",
  "Knowledge tracing (FUT-004).",
  API + "Not defined until P2 design.",
  "Not defined until P2 design.",
  "Sparse data -> no estimate.",
  "Not built before P2 validation.",
  "BKT (FUT-005).")

F("CMP-012", "Topic tracking", "P1",
  "Tracks performance by topic across attempts.",
  "Targeted revision.",
  "Answers with topics.",
  "None.",
  API + "GET /api/v1/me/topic-progress (P1)",
  "Topic panel.",
  "Unreviewed topic tags -> excluded.",
  "Only reviewed topic tags are used.",
  "Weak-topic detection (AI-014).")

F("CMP-013", "Improvement tracking", "P1",
  "Quantifies change between baseline and later estimates.",
  "Demonstrates learning impact.",
  "Baseline and post estimates.",
  "None.",
  API + "GET /api/v1/me/improvement (P1)",
  "Improvement summary with caveats.",
  "Non-comparable assessments -> caveat.",
  "Improvement shown only between comparable assessments or with an explicit caveat.",
  "Training effectiveness analytics (ANA-008).")

F("CMP-014", "Competency graph", "P1",
  "Visual graph linking competencies, topics, courses and evidence.",
  "Explains relationships behind recommendations.",
  "Mappings.",
  "None.",
  API + "GET /api/v1/competency-graph (P1)",
  "Interactive graph with list alternative.",
  "Large graph -> filtered view.",
  "Every node reachable via a keyboard-accessible list view.",
  "Concept graph (MAT-024).")

F("CMP-015", "Skill passport", "P2",
  "Portable summary of verified competencies and evidence.",
  "Recognition across postings.",
  "Human-verified estimates.",
  "None.",
  API + "Not defined until P2 design.",
  "Not defined until P2 design.",
  "Unverified estimates -> excluded.",
  "Contains only human-verified entries; sharing controlled by the learner.",
  "Competency passport (FUT-008).")

F("CMP-016", "Evidence ledger", "P0",
  "Append-only record of evidence contributing to each competency estimate.",
  "Auditability and contestability.",
  "CompetencyEvidence (append-only with void markers).",
  "None.",
  API + "GET /api/v1/users/{id}/competencies/{competency_id}/evidence",
  "Evidence panel.",
  "Attempt to edit evidence -> blocked; voiding requires reason.",
  "Evidence records are never deleted or edited in place; voids record who, when and why.",
  "Verifiable credentials (P2).")

F("CMP-017", "Assessment history (competency view)", "P0",
  "Competency-filtered view of assessment history.",
  "Shows which attempts shaped each estimate.",
  "Attempts; evidence.",
  "None.",
  API + "GET /api/v1/me/attempts?competency_id=",
  "Filter in history list.",
  "None specific.",
  "Filtering shows only attempts with evidence for the competency.",
  "Timeline (PRO-013).",
  alias_of="ASM-032", deps="ASM-032")

F("CMP-018", "Learning evidence", "P1",
  "Records completed learning activities as supporting (non-assessment) evidence, clearly distinguished from assessed evidence.",
  "Recognises learning effort.",
  "LearningActivity.",
  "None.",
  API + "POST /api/v1/learning-activities (P1 evidence linkage)",
  "Evidence panel with type labels.",
  "Self-reported activity -> labelled self-reported.",
  "Learning evidence never changes a score without an assessment or human adjustment.",
  "Evidence timeline (PRO-014).")

F("CMP-019", "Human-reviewed competency adjustments", "P0",
  "Authorised reviewers adjust an estimate with a mandatory reason; the learner is notified and can request correction.",
  "Human oversight of automated estimates.",
  "Adjustment record as CompetencyEvidence; ReviewTask.",
  "None.",
  API + "POST /api/v1/user-competencies/{id}/adjustments",
  "Adjustment dialog in trainer/admin views; change visible on learner profile.",
  "Missing reason -> blocked; reviewer adjusting own record -> blocked.",
  "Every adjustment stores reviewer, reason, previous and new values; users cannot adjust their own estimates.",
  "Moderation panels (P1).",
  primary="Trainer", secondary="Competency framework administrator; Learner")

# ------------------------------------------------------- E. ROLE INTELLIGENCE
category(
    "E", "ROLE", "Role intelligence", "Role intelligence",
    "Competency framework administrator", "Organization administrator; Learner",
    "ADM-003 (role management); ADM-004 (competency management)",
    "Role-to-competency mappings are authored and approved by competency framework administrators; no official mapping exists in collected data (Requires human confirmation).",
    "Role configuration changes audited; role data scoped to organisation.",
    "Role selection usable with keyboard and screen reader; searchable lists.",
)

F("ROLE-001", "Job-role selection", "P0",
  "Learner selects department and job role during onboarding (changeable later with audit).",
  "Anchors requirements, assessments and recommendations.",
  "JobRole list; Department list.",
  "None in MVP (AI suggestion is AI-003, P1).",
  API + "GET /api/v1/job-roles; PUT /api/v1/me/job-role",
  "Onboarding role step; Settings.",
  "No roles configured -> onboarding blocked with administrator contact message.",
  "A learner cannot start the pre-assessment without a selected role; role changes are audited.",
  "AI role suggestion (AI-003).",
  primary="Learner", secondary="Department administrator")

F("ROLE-002", "Role-to-competency mapping", "P0",
  "Defines which competencies each job role needs and the required level for each.",
  "Required input for gap detection.",
  "RoleCompetency.",
  "None.",
  API + "GET /api/v1/job-roles/{id}/competencies; PUT /api/v1/job-roles/{id}/competencies",
  "Role editor in Admin dashboard.",
  "Mapping references inactive competency -> blocked.",
  "Mappings are versioned, approved by a competency framework administrator, and visible to learners of the role.",
  "Role versioning (ROLE-012).",
  status=HUMAN, status_note="no official role-to-competency mapping exists in collected data; must be authored and approved (ASSUMPTIONS_AND_OPEN_QUESTIONS.md).")

F("ROLE-003", "Role-to-course mapping", "P1",
  "Associates recommended or mandatory courses with job roles.",
  "Role-specific catalogues.",
  "RoleCourse link.",
  "None.",
  API + "PUT /api/v1/job-roles/{id}/courses (P1)",
  "Role editor tab.",
  "Course retired -> mapping flagged.",
  "Mandatory flags set only by authorised administrators.",
  "Role-specific paths (ROLE-006).")

F("ROLE-004", "Role-to-assessment mapping", "P0",
  "Links each job role to its initial assessment blueprint.",
  "Correct assessment per role without manual lookup.",
  "Assessment.job_role_id.",
  "None.",
  API + "Assessment blueprint job_role_id; GET /api/v1/job-roles/{id}/assessments",
  "Role editor shows linked assessments.",
  "No published assessment for role -> learner sees 'assessment not yet available'.",
  "Each role with learners has at most one active pre-assessment at a time.",
  "Multiple assessment tracks (P1).")

F("ROLE-005", "Role-to-skill mapping", "P1",
  "Maps finer-grained skills (topics) to roles.",
  "Topic-level targeting.",
  "Role-topic links.",
  "None.",
  API + "P1",
  "Role editor tab.",
  "Unreviewed topics -> excluded.",
  "Uses reviewed taxonomy terms only.",
  "Skill graph.")

F("ROLE-006", "Role-specific learning paths", "P1",
  "Curated default paths per role, personalised by gaps.",
  "Consistent baseline development per role.",
  "Role path templates.",
  "None.",
  API + "P1",
  "Path template editor.",
  "Template empty -> falls back to gap-based path.",
  "Personalised path always states which template it derives from.",
  "Career paths (FUT-003).")

F("ROLE-007", "Role-specific quizzes", "P0",
  "Quizzes scoped to a role's competencies (same capability as ASM-010 from the role perspective).",
  "Relevance of practice.",
  "RoleCompetency; approved questions.",
  "None.",
  API + "As ASM-010",
  "As ASM-010.",
  "As ASM-010.",
  "As ASM-010.",
  "As ASM-010.",
  alias_of="ASM-010", deps="ASM-010")

F("ROLE-008", "Role-readiness score", "P1",
  "Aggregated readiness for the learner's own current role, with evidence and caveats.",
  "Self-development planning.",
  "Estimates; critical flags.",
  "Rule-based aggregation.",
  API + "P1",
  "Readiness card with explanation.",
  "Insufficient evidence -> not shown.",
  "Shown only to the learner and their trainer; labelled as development guidance, not an eligibility decision.",
  "Target-role readiness (ROLE-010).",
  security="Must not be used for promotion or selection decisions (SECURITY_RESPONSIBLE_AI.md §HID).")

F("ROLE-009", "Career-development suggestions", "P2",
  "Suggests development directions based on interests and competencies.",
  "Long-term engagement.",
  "Profile; role catalogue.",
  "LLM suggestions with review.",
  API + "Not defined until P2 design.",
  "Not defined until P2 design.",
  "Unsupported suggestion -> suppressed.",
  "Advisory only; not linked to HR processes.",
  "Career pathways (FUT-003).")

F("ROLE-010", "Role transition pathways", "P2",
  "Shows competencies needed to move to another role.",
  "Voluntary career planning.",
  "Two role mappings.",
  "None.",
  API + "Not defined until P2 design.",
  "Not defined until P2 design.",
  "Target role not configured -> unavailable.",
  "Learner-initiated only.",
  "Capability planning (FUT-018).")

F("ROLE-011", "Role prerequisites", "P2",
  "Defines prerequisite roles or competencies.",
  "Structured progressions.",
  "Role relations.",
  "None.",
  API + "Not defined until P2 design.",
  "Not defined until P2 design.",
  "Cycles -> rejected.",
  "Authored by administrators only.",
  "Career pathways.")

F("ROLE-012", "Role versioning", "P1",
  "Versions role definitions and mappings so estimates reference the mapping version used.",
  "Historical comparability.",
  "JobRole version fields.",
  "None.",
  API + "P1",
  "Version history in role editor.",
  "Learners on old version -> migration prompt.",
  "Gap results store the role-mapping version.",
  "Scheduled role changes.")

F("ROLE-013", "Organization-specific role configuration", "P1",
  "Each organisation defines its own roles and mappings.",
  "Supports multiple statistical organisations.",
  "Organisation-scoped JobRole.",
  "None.",
  API + "P1 multi-organisation administration",
  "Organisation selector for platform administrators.",
  "Cross-organisation reference -> blocked.",
  "Roles never leak across organisations.",
  "Shared role templates.")

# -------------------------------------------------------- F. PERSONALIZATION
category(
    "F", "PER", "Personalization", "Personalization",
    "Learner", "Training manager; Trainer",
    "AI-004 (learning path); AI-005 (recommendations)",
    "Recommendations are explainable and dismissible; nothing becomes mandatory without a human assignment.",
    "Personalisation uses only the learner's own data and the organisation's approved catalogue.",
    "Plans and cards readable by screen readers; no motion-dependent interactions.",
)

F("PER-001", "Personalized dashboard", "P0",
  "Learner home showing role, baseline status, top gaps, continue-learning items, recommendations and recent activity.",
  "Immediate orientation and next action.",
  "Profile, gaps, path, progress.",
  "None (displays deterministic outputs).",
  API + "GET /api/v1/me/dashboard (aggregate)",
  "Learner dashboard screen.",
  "Partial data failure -> affected card shows its own error with retry.",
  "Dashboard loads with independent card states; no card shows another user's data.",
  "Customisable layout (P2).",
  deps="CMP-001; AI-004; PRO-001")

F("PER-002", "Personalized course recommendations", "P0",
  "Learner-facing view of AI-005 recommendations.",
  "See AI-005.", "See AI-005.", "See AI-005.", "See AI-005.", "Recommendation cards.",
  "See AI-005.", "See AI-005.", "See AI-005.",
  alias_of="AI-005", deps="AI-005")

F("PER-003", "Personalized learning paths", "P0",
  "Learner-facing view of AI-004 learning paths with item status controls.",
  "See AI-004.", "See AI-004.", "See AI-004.", "See AI-004.", "Learning path screen.",
  "See AI-004.", "See AI-004.", "See AI-004.",
  alias_of="AI-004", deps="AI-004")

F("PER-004", "Daily learning plan", "P2",
  "Short daily plan derived from the path and availability.",
  "Habit formation.",
  "Path; availability.",
  "Scheduling heuristics.",
  API + "Not defined until P2 design.",
  "Not defined until P2 design.",
  "No availability -> not generated.",
  "Opt-in only.",
  "Workload-aware planning (PER-018).")

F("PER-005", "Weekly learning plan", "P1",
  "Weekly grouping of path items with estimated effort.",
  "Realistic planning.",
  "Path items with durations.",
  "Rule-based scheduling.",
  API + "GET /api/v1/me/plans?period=week (P1)",
  "Weekly plan view.",
  "Unknown durations -> items unscheduled.",
  "Plans never mark items overdue without a learner-set goal.",
  "Calendar sync (UX-006).")

F("PER-006", "30-day learning plan", "P1",
  "Month-long plan toward selected gaps.",
  "Medium-term focus.",
  "Path; goals.",
  "Rule-based scheduling.",
  API + "GET /api/v1/me/plans?period=30d (P1)",
  "30-day plan view.",
  "As PER-005.",
  "As PER-005.",
  "Goal setting (PER-016).")

F("PER-007", "Prerequisite-based recommendations", "P1",
  "Orders recommendations by prerequisite relations.",
  "Avoids content the learner is not ready for.",
  "Course prerequisites.",
  "Rule-based.",
  API + "P1",
  "Prerequisite notes on cards.",
  "Missing prerequisites data -> ignored.",
  "Prerequisite rules visible in explanation.",
  "Competency dependencies (CMP-009).")

F("PER-008", "Difficulty-based recommendations", "P1",
  "Matches content difficulty to estimated level.",
  "Appropriate challenge.",
  "Content difficulty (reviewed).",
  "Rule-based.",
  API + "P1",
  "Difficulty labels.",
  "Uncalibrated difficulty -> not used.",
  "Uses reviewed difficulty only.",
  "Difficulty estimation (MAT-025).")

F("PER-009", "Performance-based recommendations", "P0",
  "Uses assessment performance (gaps and weak evidence) as the primary ranking signal.",
  "Focus on measured needs.",
  "Gaps; evidence bands.",
  "Rule-based (part of AI-005).",
  API + "Included in GET /api/v1/me/recommendations",
  "'Because of your result in …' reason text.",
  "No attempts -> role-based defaults.",
  "Reason text names the assessment result that triggered it.",
  "Weak-topic signals (AI-014).",
  deps="AI-005")

F("PER-010", "Competency-based recommendations", "P0",
  "Matches content via human-approved competency mappings.",
  "Relevance to role requirements.",
  "CourseCompetency links (approved).",
  "Rule-based (part of AI-005).",
  API + "Included in GET /api/v1/me/recommendations",
  "Competency chips on cards.",
  "Unapproved mappings -> ignored.",
  "Only approved mappings influence ranking.",
  "Competency graph explanations.",
  deps="AI-005")

F("PER-011", "Training-history-based recommendations", "P1",
  "Accounts for completed NSSTA programmes and courses.",
  "Avoids repeats.",
  "Learning history (internal; iGOT sync blocked).",
  "Rule-based.",
  API + "P1",
  "'Already completed' filters.",
  "History unavailable -> excluded silently only with notice.",
  "Excluded items are listed on request.",
  "iGOT history sync (IGOT-007).")

F("PER-012", "Study-plan generation", "P1",
  "Generates a study plan document with objectives and resources.",
  "Structured self-study.",
  "Path; materials.",
  "LLM drafting with citations and review.",
  API + "P1",
  "Study plan view/export.",
  "Unsupported claims -> removed.",
  "Plans cite resources; unreviewed plans labelled.",
  "Tutor integration.")

F("PER-013", "Revision recommendations", "P1",
  "Suggests revisiting materials linked to missed questions.",
  "Reinforces learning.",
  "Incorrect answers; citations.",
  "Rule-based.",
  API + "P1",
  "Revision list on results.",
  "Source unavailable -> skipped.",
  "Each suggestion cites the missed question's source.",
  "Spaced repetition (PER-015).")

F("PER-014", "Practice recommendations", "P1",
  "Suggests practice quizzes on weak topics.",
  "Low-stakes practice.",
  "Weak topics; approved questions.",
  "Rule-based.",
  API + "P1",
  "Practice card.",
  "No questions -> none.",
  "Practice results do not change estimates unless configured as evidence.",
  "Adaptive practice.")

F("PER-015", "Spaced repetition", "P2",
  "Schedules review based on forgetting curves.",
  "Retention.",
  "Response history.",
  "Scheduling algorithm.",
  API + "Not defined until P2 design.",
  "Not defined until P2 design.",
  "Sparse history -> default intervals.",
  "Opt-in.",
  "Knowledge tracing.")

F("PER-016", "Goal setting", "P1",
  "Learners set target levels and dates for competencies.",
  "Ownership of development.",
  "Goal records.",
  "None.",
  API + "POST /api/v1/me/goals (P1)",
  "Goal editor.",
  "Unrealistic date -> warning only.",
  "Goals are private to the learner unless shared.",
  "Deadline-aware planning.")

F("PER-017", "Deadline-aware planning", "P2",
  "Plans around assignment deadlines.",
  "Meets organisational timelines.",
  "Assignments; deadlines.",
  "Scheduling.",
  API + "Not defined until P2 design.",
  "Not defined until P2 design.",
  "Conflicting deadlines -> surfaced to trainer.",
  "No automatic escalation to supervisors.",
  "Workload-aware planning.")

F("PER-018", "Workload-aware planning", "P2",
  "Adjusts plans to declared workload.",
  "Sustainable learning.",
  "Learner-declared availability.",
  "Scheduling.",
  API + "Not defined until P2 design.",
  "Not defined until P2 design.",
  "No declaration -> defaults.",
  "Workload data is learner-declared, never inferred from work systems.",
  "Resource optimisation (FUT-015).")

# -------------------------------------------------------- G. AI LEARNING TUTOR
category(
    "G", "TUT", "AI learning tutor", "AI learning tutor",
    "Learner", "Trainer",
    "MAT-017 (document Q&A); RAI-001 (grounding); RAI-007 (prompt-injection protection)",
    "Tutor output is advisory; learners can flag responses; flagged responses are reviewable by trainers.",
    "Conversations are personal data with a retention policy; personal data redacted before provider calls; prompt-injection defences; no side-effecting tools.",
    "Chat is screen-reader friendly (live regions, message landmarks), keyboard operable, supports text resizing.",
)

TUT = [
    ("TUT-001", "Conversational tutor", "P1", "Multi-turn tutor grounded in approved materials.", "Interactive learning support beyond single questions.", "Conversation history; retrieved chunks.", "RAG over conversation with abstention.", "POST /api/v1/tutor/conversations; POST /api/v1/tutor/conversations/{id}/messages (P1)", "Tutor screen.", "Provider down -> tutor unavailable banner; off-topic -> redirect.", "Every factual answer is grounded with citations or the tutor abstains.", "Voice tutor (FUT-012)."),
    ("TUT-002", "Document-aware tutor", "P1", "Tutor scoped to a selected document or material set.", "Focused study of a manual.", "Selected material IDs.", "Scoped retrieval.", "Scope parameter on conversation (P1)", "Scope selector.", "Scope inaccessible -> blocked.", "Retrieval never exceeds the selected, accessible scope.", "Multi-document comparison."),
    ("TUT-003", "Explain concepts", "P1", "Explains a statistical concept from sources.", "Understanding of methodology.", "Chunks.", "Grounded explanation.", "Tutor message intent 'explain' (P1)", "Explain action on selected text.", "Concept absent from sources -> abstain.", "Explanations cite sources.", "Concept graph links."),
    ("TUT-004", "Simplify concepts", "P1", "Rephrases a passage in simpler language without changing meaning.", "Accessibility for newcomers.", "Selected passage.", "LLM rewrite constrained to source.", "Intent 'simplify' (P1)", "Simplify action.", "Meaning drift detected -> original shown.", "Simplified text shows the original passage alongside.", "Reading-level control."),
    ("TUT-005", "Beginner mode", "P2", "Default simpler explanations for new learners.", "Onboarding support.", "User preference.", "Prompt variant.", "User setting (P2)", "Settings toggle.", "None specific.", "Grounding rules unchanged.", "Adaptive level."),
    ("TUT-006", "Examples", "P1", "Provides examples drawn from or consistent with sources.", "Concrete understanding.", "Chunks.", "Grounded generation.", "Intent 'example' (P1)", "Example action.", "Invented statistics -> blocked (examples must not present fabricated official figures).", "Illustrative examples are labelled as illustrative and contain no invented official figures.", "Worked data exercises."),
    ("TUT-007", "Analogies", "P2", "Offers analogies for difficult concepts.", "Intuition building.", "Concept.", "LLM generation labelled as analogy.", "Not defined until P2 design.", "Not defined until P2 design.", "Misleading analogy -> learner flag.", "Labelled 'analogy - not from source'.", "None."),
    ("TUT-008", "Practice questions", "P1", "Generates practice questions in conversation (not used as evidence).", "Self-testing.", "Chunks.", "Generation with lightweight validation.", "Intent 'practice' (P1)", "Inline practice card.", "Validation fails -> not shown.", "Tutor practice questions never count as assessment evidence and are labelled unreviewed.", "Promotion to question bank via review."),
    ("TUT-009", "Summaries", "P1", "Summarises a section on request.", "Revision aid.", "Chunks.", "Grounded summarisation.", "Intent 'summarize' (P1)", "Summary card with citations.", "Citation verification fails -> withheld.", "Summaries carry citations.", "Reviewed summaries (MAT-021)."),
    ("TUT-010", "Notes", "P2", "Learner-saved notes from tutor sessions.", "Personal study record.", "Notes.", "None.", "Not defined until P2 design.", "Notes panel.", "None specific.", "Notes private to the learner.", "Export."),
    ("TUT-011", "Follow-up questions", "P1", "Suggests follow-up questions to deepen understanding.", "Guided exploration.", "Conversation.", "LLM suggestions.", "Included in tutor response (P1)", "Suggested question chips.", "Suggestion answer unavailable -> chip hidden.", "Suggestions answerable from accessible sources.", "Curriculum-aligned prompts."),
    ("TUT-012", "Conversation context", "P1", "Keeps bounded conversation history for coherent replies.", "Natural dialogue.", "Recent messages.", "Context window management.", "Conversation state (P1)", "Visible 'context used' indicator.", "Context overflow -> summarised with notice.", "Context never includes other users' conversations.", "Long-term memory (P2, opt-in)."),
    ("TUT-013", "Topic-aware responses", "P1", "Uses taxonomy topics to focus retrieval.", "Relevance.", "Topics.", "Filtered retrieval.", "Topic filter (P1)", "Topic chip.", "Unreviewed topics -> not used.", "Topic filter documented in response metadata.", "Competency awareness."),
    ("TUT-014", "Competency-aware tutoring", "P2", "Adapts to learner gaps.", "Personalised tutoring.", "Gaps.", "Prompt conditioning on structured gap data (no raw personal data).", "Not defined until P2 design.", "Not defined until P2 design.", "Missing gaps -> generic mode.", "Only structured competency identifiers sent to provider, never names.", "Knowledge tracing."),
    ("TUT-015", "Grounded responses", "P1", "Tutor inherits P0 grounding controls (RAI-001).", "Trustworthy tutoring.", "Chunks.", "RAG.", "As MAT-018", "Citations inline.", "As MAT-017.", "No ungrounded factual claims displayed without a 'not from sources' label.", "Claim-level verification."),
    ("TUT-016", "Citation display", "P1", "Inline citations in tutor messages.", "Verifiability.", "Citations.", "As MAT-019.", "Citation objects in messages (P1)", "Citation chips.", "Invalid citation -> removed and flagged.", "All citations resolve to accessible pages.", "Hover previews."),
    ("TUT-017", "Confidence display", "P1", "Shows grounding confidence band per answer.", "Calibrated trust.", "Retrieval scores; verification results.", "Rule-based bands.", "Confidence field (P1)", "Band label with explanation.", "Unknown -> 'low'.", "Bands defined in UI copy.", "Calibrated probabilities."),
    ("TUT-018", "I don't know behavior", "P1", "Tutor explicitly states when sources do not answer the question.", "Prevents fabricated answers.", "Retrieval results.", "Abstention (RAI-015).", "Abstention flag (P1)", "Abstention message with suggestion to ask a trainer.", "None.", "Unanswerable questions in evaluation set produce abstentions.", "Escalation to trainer queue."),
    ("TUT-019", "Prompt-injection resistance", "P1", "Tutor treats document content and user text as data and resists instruction override.", "Safety and integrity.", "Inputs.", "Defences per AI_SYSTEM_SPEC.md §36.", "Internal", "Warning when content was restricted.", "Injection detected -> restricted response and security log.", "Injection test suite passes before release.", "Classifier-based detection."),
    ("TUT-020", "Tutor conversation history", "P1", "Learners view and delete their conversations.", "Continuity and control.", "TutorConversation, TutorMessage.", "None.", "GET/DELETE /api/v1/tutor/conversations (P1)", "History sidebar.", "Deletion -> soft delete then purge per retention.", "Learners can delete their conversations; retention enforced.", "Export."),
]
for t in TUT:
    fid, name, p, d, v, data, ai, api, ui, fail, acc, fut = t
    F(fid, name, p, d, v, data, ai, API + api, ui, fail, acc, fut)

# ----------------------------------------------------------- H. iGOT
category(
    "H", "IGOT", "iGOT integration", "iGOT integration",
    "Platform administrator", "Learner; Training manager",
    "IGOT-010 (client abstraction); ADM-014 (configuration/feature flags)",
    "Any real integration requires written authorisation and official documentation from Karmayogi Bharat (IGOT_ACCESS_STATUS.md; API_REQUIREMENTS.md §6.4).",
    "No credentials in source control; no undocumented endpoints; learner iGOT data is personal data requiring authorisation and consent; mock data never presented as real.",
    "Integration and MOCK states communicated in text, not colour only.",
)

F("IGOT-001", "iGOT course search", "P1",
  "Search iGOT course catalogue through the adapter.",
  "Access to a large official catalogue.",
  "iGOT course metadata (real access UNKNOWN).",
  "None.",
  API + "GET /api/v1/integrations/igot/courses?q= (P1; mock only until access)",
  "Course discovery source filter.",
  "Adapter not connected -> source hidden with admin notice.",
  "Real search only via a verified adapter; mock results labelled MOCK.",
  "Federated search across providers.",
  status=BLOCK, status_note="no documented public/partner API (IGOT_ACCESS_STATUS.md); mock list_courses() exists without search.")

F("IGOT-002", "iGOT course recommendation", "P0",
  "Integration-side view of AI-006.",
  "See AI-006.", "See AI-006.", "See AI-006.", "See AI-006.", "MOCK badge on cards.",
  "See AI-006.", "See AI-006.", "See AI-006.",
  status=MOCK, status_note="mock catalogue only.", mvp="In MVP - mock data only, feature-flagged",
  alias_of="AI-006", deps="AI-006")

F("IGOT-003", "Competency-to-iGOT mapping", "P1",
  "Maps platform competencies to iGOT course competencies.",
  "Links gaps to iGOT content.",
  "iGOT competency metadata (format UNKNOWN); CSCD/FRAC references.",
  "Suggestions with review (MAT-026).",
  API + "P1",
  "Mapping review table.",
  "Unknown iGOT competency schema -> blocked.",
  "Mappings human-approved.",
  "FRAC alignment (Decision required).",
  status=BLOCK, status_note="iGOT competency data format unknown; FRAC page unreachable (docs/DATA_COLLECTION_RESULTS.md).")

F("IGOT-004", "Course deep links", "P1",
  "Links to iGOT course pages.",
  "One-click access.",
  "Verified iGOT URL pattern (not verified).",
  "None.",
  API + "Course.external_url (P1)",
  "'Open in iGOT' link.",
  "Link pattern unverified -> not shown.",
  "Only verified URLs displayed; no links fabricated from IDs.",
  "Return-to-platform flow.",
  status=BLOCK, status_note="URL pattern not verified.")

F("IGOT-005", "Course metadata synchronization", "P1",
  "Periodically imports course metadata.",
  "Up-to-date catalogue.",
  "Authorised catalogue feed.",
  "None.",
  API + "POST /api/v1/integrations/igot/sync-jobs (P1)",
  "Sync status on Integration health.",
  "Partial sync -> previous snapshot retained; never partial overwrite.",
  "Sync is transactional per batch with provenance.",
  "Delta sync.",
  status=BLOCK, status_note="requires authorised access.")

F("IGOT-006", "Completion synchronization", "P2",
  "Imports learner course completions with consent.",
  "Unified learning record.",
  "Personal learner data.",
  "None.",
  API + "Not defined until access and consent model exist.",
  "Consent screen; sync status.",
  "Consent missing -> no sync.",
  "Only with authorisation, consent and lawful basis.",
  "Bidirectional sync.",
  status=BLOCK, status_note="personal data; requires authorisation, consent model and lawful basis.")

F("IGOT-007", "Learning-history synchronization", "P2",
  "Imports learning history with consent.",
  "Better recommendations.",
  "Personal learner data.",
  "None.",
  API + "Not defined until access and consent model exist.",
  "Consent screen.",
  "As IGOT-006.",
  "As IGOT-006.",
  "None.",
  status=BLOCK, status_note="as IGOT-006.")

F("IGOT-008", "Authentication integration", "P2",
  "Delegated authentication with iGOT accounts.",
  "Single identity for learners.",
  "Official auth documentation.",
  "None.",
  API + "Not defined until official documentation exists.",
  "Login option.",
  "Token failure -> local login.",
  "Implemented only against officially documented flows.",
  "SSO federation.",
  status=BLOCK, status_note="no documented third-party auth (IGOT_ACCESS_STATUS.md §4).")

F("IGOT-009", "OAuth/SSO placeholder", "P1",
  "Design-level placeholder for OIDC/SSO providers behind the auth adapter; no live connection.",
  "Avoids rework when SSO is authorised.",
  "Provider metadata (future).",
  "None.",
  API + "Auth adapter interface (API_INTEGRATION_SPEC.md §Adapters)",
  "Hidden until configured.",
  "Misconfiguration -> disabled.",
  "Placeholder exposes no login option until a provider is configured and verified.",
  "Parichay or other government SSO (Decision required).",
  deps="SEC-004")

F("IGOT-010", "API client abstraction", "P0",
  "IGotClient interface with record types and errors; factory selects implementation by IGOT_CLIENT_MODE and refuses 'live'.",
  "Mock and real implementations are interchangeable.",
  "Course, CoursePage, Enrollment, Completion, LearningEvent record types.",
  "None.",
  API + "Backend service boundary; no public HTTP routes of its own",
  "None directly.",
  "Unknown mode -> ValueError; live -> AccessNotVerifiedError.",
  "All iGOT access goes through IGotClient; the factory defaults to mock and refuses live.",
  "Async interface and health/sync methods (API_INTEGRATION_SPEC.md §iGOT).",
  status=IMPL, status_note="clients/igot_client.py (interface, records, errors, factory); tested in tests/test_mock_igot_client.py. Health and sync methods not yet in the interface.",
  deps="ADM-014 (configuration/feature flags)",
  human_review="Not required for the interface; any real implementation requires written authorisation (API_REQUIREMENTS.md §6.4).")

F("IGOT-011", "Mock iGOT adapter", "P0",
  "MockIGotClient over data/samples/mock/MOCK_igot_fixtures.json; every record data_status MOCK; refuses non-MOCK fixtures; simulates authorisation.",
  "Enables development and demos without real access.",
  "Synthetic fixtures (4 courses, 3 users).",
  "None.",
  API + "Used behind GET /api/v1/integrations/igot/courses",
  "MOCK badge everywhere mock data appears.",
  "Fixture not fully MOCK-marked -> refuses to load.",
  "All five interface methods supported; every returned record is MOCK; tests pass.",
  "Contract tests shared with future real adapter (TESTING_STRATEGY.md).",
  status=MOCK, status_note="clients/mock_igot_client.py with 14 passing tests (re-run 2026-09-14).",
  human_review="Not required for synthetic fixtures; any display of mock data must carry the MOCK label.")

F("IGOT-012", "Real iGOT adapter", "P1",
  "Implementation of IGotClient against officially documented endpoints.",
  "Real catalogue and (with consent) learner data.",
  "Official documentation; credentials via environment.",
  "None.",
  API + "Adapter behind existing interface",
  "Connection state 'connected' on Integration health.",
  "Any unverified endpoint -> not implemented.",
  "Built only after API_REQUIREMENTS.md §6.4 preconditions are VERIFIED by a human; passes the shared contract tests.",
  "Additional providers.",
  status=BLOCK, status_note="no authorisation or documentation (IGOT_ACCESS_STATUS.md).")

F("IGOT-013", "Integration health checks", "P0",
  "Reports adapter mode and health: 'mock', 'not connected', 'connected', 'degraded'.",
  "Administrators know exactly what data source is active.",
  "Adapter mode; last check.",
  "None.",
  API + "GET /api/v1/integrations; GET /api/v1/integrations/igot/health",
  "Integration health screen.",
  "Health check error -> 'degraded' with reason.",
  "Mode 'mock' and 'not connected' are shown explicitly; a mock adapter never reports 'connected'.",
  "Alerting (OBSERVABILITY_SPEC.md).")

F("IGOT-014", "Retry handling", "P1",
  "Bounded retries with exponential backoff and jitter for real adapter calls.",
  "Resilience to transient failures.",
  "Error classification.",
  "None.",
  API + "Adapter internals (P1)",
  "Degraded state shown.",
  "Non-retryable errors -> no retry.",
  "Retries only on retryable errors; limits configurable.",
  "Circuit breaker.",
  status=BLOCK, status_note="applies to the real adapter.")

F("IGOT-015", "Rate-limit handling", "P1",
  "Honours documented rate limits and Retry-After.",
  "Good citizenship with government systems.",
  "Documented limits (unknown).",
  "None.",
  API + "Adapter internals (P1)",
  "Sync throttling indicator.",
  "429 -> backoff.",
  "Client stays below documented limits.",
  "Adaptive throttling.",
  status=BLOCK, status_note="limits unknown.")

F("IGOT-016", "Data synchronization logs", "P1",
  "Records every sync job with counts, errors and provenance.",
  "Auditability of external data.",
  "IntegrationSyncJob.",
  "None.",
  API + "GET /api/v1/integrations/igot/sync-jobs (P1)",
  "Sync log table.",
  "Log write failure -> sync aborted.",
  "No sync commits data without a sync log record.",
  "Export of logs.",
  status=BLOCK, status_note="no real sync possible.")

F("IGOT-017", "Integration failure states", "P0",
  "Explicit states and user messages for not-connected, refused, unauthorised and degraded adapters.",
  "No silent failures or silent data corruption.",
  "Adapter errors (AccessNotVerifiedError, AuthorizationRequiredError, NotFoundError).",
  "None.",
  API + "Problem responses (ERROR_HANDLING_SPEC.md) on integration routes",
  "Integration health; source-unavailable notices in Course discovery.",
  "Unhandled adapter error -> generic 'integration unavailable' and logged.",
  "Every adapter error maps to a documented error code; failures never write partial external data.",
  "Automatic recovery.",
  status=PART, status_note="error classes exist in clients/igot_client.py; no API or UI mapping.")

F("IGOT-018", "External-source provenance", "P0",
  "Tags every externally sourced record with source, adapter mode, retrieval time and data_status.",
  "Users and auditors can always tell real from mock and where data came from.",
  "Provenance fields on Course and sync records.",
  "None.",
  API + "provenance object on course and recommendation payloads",
  "Source/provenance badge.",
  "Missing provenance -> record rejected.",
  "No iGOT-sourced record is stored or displayed without provenance; mock records carry data_status MOCK end to end.",
  "Signed provenance.",
  status=PART, status_note="mock records carry data_status MOCK (clients/mock_igot_client.py); no application storage.")
