"""Feature registry: I (Administration), J (Analytics), K (Trainer), L (Multilingual/accessibility), M (Gamification), N (Progress)."""

from registry_common import F, category, IMPL, PART, MOCK, PLAN, BLOCK, HUMAN

API = "Planned internal API (docs/API_INTEGRATION_SPEC.md): "


def batch(rows):
    for r in rows:
        fid, name, p, d, v, data, ai, api, ui, fail, acc, fut, *extra = r
        kwargs = extra[0] if extra else {}
        F(fid, name, p, d, v, data, ai, API + api, ui, fail, acc, fut, **kwargs)


# ------------------------------------------------------------ I. ADMINISTRATION
category(
    "I", "ADM", "Administration", "Administration",
    "Organization administrator", "Department administrator; Competency framework administrator; Platform administrator",
    "SEC-001 (authentication); SEC-002 (RBAC); SEC-009 (audit logs)",
    "Approval workflows for AI-generated content; configuration changes affecting learners require an authorised administrator.",
    "Server-side authorisation on every action; every administrative change audited with before/after values.",
    "Admin tables and forms meet the table and form patterns in UI_UX_SPEC.md (keyboard, labels, error summaries).",
)

batch([
    ("ADM-001", "User management", "P0", "Create, deactivate and edit users and assign access roles within the organisation.", "Controlled access for a government deployment.", "User; access role assignments; Department.", "None.", "GET/POST /api/v1/users; GET/PATCH /api/v1/users/{id}; PUT /api/v1/users/{id}/access-roles", "Users table and user form in Admin dashboard.", "Duplicate email -> conflict error; last org admin removal -> blocked.", "Deactivated users cannot sign in; role changes are audited; an organisation always retains at least one organisation administrator.", "Bulk import; SSO provisioning (P1).", {"deps": "SEC-001; SEC-002"}),
    ("ADM-002", "Department management", "P0", "Maintain departments/divisions within an organisation.", "Scoping for administrators, analytics and learners.", "Department.", "None.", "GET/POST /api/v1/departments; PATCH /api/v1/departments/{id}", "Departments table.", "Department with active users deleted -> blocked (deactivate instead).", "Departments are soft-deactivated, never hard-deleted while referenced.", "Hierarchies (P1)."),
    ("ADM-003", "Role management", "P0", "Maintain job roles (not access roles) with descriptions and status.", "Basis for role selection and requirements.", "JobRole.", "None.", "GET/POST /api/v1/job-roles; PATCH /api/v1/job-roles/{id}", "Job roles table and editor.", "Role with learners deactivated -> learners prompted to reselect.", "Job roles are clearly distinguished from access roles in UI and API naming (DECISIONS.md DEC-012).", "Role versioning (ROLE-012).", {"primary": "Competency framework administrator"}),
    ("ADM-004", "Competency management", "P0", "Maintain competency frameworks, competencies and level scales, including imported reference frameworks with licence restrictions.", "Authoritative competency definitions for the organisation.", "CompetencyFramework; Competency; CompetencyLevel; SourceRecord.", "None.", "GET/POST /api/v1/competency-frameworks; GET/POST /api/v1/competencies; PATCH /api/v1/competencies/{id}", "Framework and competency editor.", "Importing restricted definitions -> blocked; definition fields left empty with source page reference.", "Imported CSCD entries show names and page references only (definitions not reproduced); functional statistical competencies must be authored and approved before use.", "Framework versioning; FRAC alignment.", {"primary": "Competency framework administrator", "status": PART, "status_note": "structure-only CSCD dataset (data/processed/competency_framework.json: 4 clusters, 25 competencies, no definitions); no functional statistical competencies; no admin application."}),
    ("ADM-005", "Course management", "P0", "Maintain the internal course catalogue, including seeded NSSTA programme listings and their competency/topic mappings.", "Recommendable, curated content.", "Course; CourseCompetency; provenance.", "None.", "GET/POST /api/v1/courses; GET/PATCH /api/v1/courses/{id}", "Course table and editor with provenance and review state.", "Seeded mapping unreviewed -> excluded from recommendations.", "Seeded courses keep source URL, organisation and data_status; NSSTA programmes are listings, not enrollable online courses.", "iGOT catalogue merge (IGOT-005).", {"primary": "Training manager", "status": PART, "status_note": "99 NSSTA programme records in data/processed/training_programmes.json (MACHINE_OBSERVED, unreviewed); no admin application."}),
    ("ADM-006", "Assessment management", "P0", "Create, publish and retire assessments and blueprints.", "Controlled assessment lifecycle.", "Assessment; blueprint.", "None.", "GET/POST /api/v1/assessments; PATCH /api/v1/assessments/{id}; POST /api/v1/assessments/{id}/publish", "Assessments table and blueprint editor.", "Publishing with unapproved items -> blocked.", "Only assessments composed of approved question versions can be published.", "Scheduling windows (P1).", {"primary": "Trainer"}),
    ("ADM-007", "Quiz management", "P0", "Administrative view of quizzes (assessments with purpose 'practice' or 'topic').", "See ADM-006.", "See ADM-006.", "See ADM-006.", "See ADM-006", "See ADM-006.", "See ADM-006.", "See ADM-006.", "See ADM-006.", {"alias_of": "ADM-006", "deps": "ADM-006"}),
    ("ADM-008", "Learning-material management", "P0", "Manage learning materials: metadata, licence notes, access scope, deactivation, reprocessing.", "Governed content library.", "LearningMaterial; Document.", "None.", "GET /api/v1/learning-materials; PATCH /api/v1/learning-materials/{id}; DELETE /api/v1/learning-materials/{id} (soft)", "Materials table in Document library (admin mode).", "Material cited by approved questions deactivated -> questions suspended and review tasks created.", "Deactivating a material immediately removes it from search, Q&A and generation.", "Retention policies per material (SEC-018)."),
    ("ADM-009", "AI-generated-content review", "P0", "Central review queue for all AI-generated artefacts requiring approval (questions in MVP).", "Human oversight at one place.", "ReviewTask.", "None.", "GET /api/v1/review-tasks; POST /api/v1/review-tasks/{id}/decision", "Quiz review screen; review counters on Trainer/Admin dashboards.", "Reviewer unavailable -> tasks reassignable.", "No AI-generated artefact requiring approval is learner-visible before a decision.", "Summaries and tutor flags (P1).", {"primary": "Trainer", "alias_of": "ASM-027", "deps": "ASM-027"}),
    ("ADM-010", "Approval workflows", "P0", "Configurable single-step approval with optional second reviewer for question approval.", "Proportionate control.", "Approval policy; Approval.", "None.", "GET/PATCH /api/v1/admin/settings (approval policy)", "Settings section.", "Policy change mid-review -> applies to new tasks only.", "Policy changes are audited and do not alter past decisions.", "Multi-stage workflows (P1)."),
    ("ADM-011", "Assignment workflows", "P1", "Assign learning items or assessments to learners or departments.", "Organisational training programmes.", "Assignment.", "None.", "POST /api/v1/assignments (P1)", "Assignment dialog.", "Assignment to inaccessible users -> blocked.", "Assignments are visible to learners with due dates and assigner.", "Deadline-aware planning (PER-017)."),
    ("ADM-012", "Learner progress monitoring", "P0", "Scoped view of learners' assessment status, gaps and path progress for trainers and training managers.", "Timely support for learners.", "Progress; attempts; gaps (scoped).", "None.", "GET /api/v1/users/{id}/progress; GET /api/v1/progress?department_id= (scoped)", "Learner list with status in Trainer dashboard.", "Out-of-scope user requested -> 403.", "Monitoring shows only users within the viewer's scope; no rankings of individuals.", "Weak-learner support views (TRN-011).", {"primary": "Trainer", "secondary": "Training manager; Department administrator"}),
    ("ADM-013", "Department analytics", "P1", "Aggregated department capability and progress analytics.", "Planning training at department level.", "Aggregates with minimum group size.", "None.", "GET /api/v1/analytics/departments/{id} (P1)", "Department analytics view.", "Small groups -> suppressed.", "Aggregates suppress groups below minimum size.", "Heatmaps (ANA-001).", {"primary": "Department administrator"}),
    ("ADM-014", "Configuration management", "P0", "Organisation settings and feature flags (including iGOT adapter visibility and mock-mode display).", "Safe, auditable configuration.", "Setting; FeatureFlag.", "None.", "GET/PATCH /api/v1/admin/settings", "Settings screen (admin sections).", "Invalid setting -> validation error; secrets never editable via UI.", "Every change audited; secrets are environment-managed and never returned by the API.", "Environment promotion.", {"primary": "Platform administrator"}),
    ("ADM-015", "Taxonomy management", "P1", "Maintain topic taxonomy terms and review auto-tags.", "Quality of linkage.", "Topic.", "None.", "POST/PATCH /api/v1/topics (P1); GET /api/v1/topics (P0 read)", "Taxonomy editor.", "Term in use deleted -> blocked.", "Terms are versioned; seeded taxonomy is ASSUMED until reviewed.", "Multilingual labels.", {"status": PART, "status_note": "project-defined taxonomy v0.1.2 in scripts/processing/topic_taxonomy.json and data/processed/topics.json (ASSUMED)."}),
    ("ADM-016", "Permission management", "P1", "Custom permission sets beyond the fixed MVP access roles.", "Fit organisational structures.", "Permissions.", "None.", "P1", "Permission editor.", "Privilege escalation attempt -> blocked and audited.", "Users cannot grant permissions they do not hold.", "Attribute-based access (P2)."),
    ("ADM-017", "Audit-log access", "P0", "Search and view audit logs and AI interaction logs according to role.", "Accountability and investigations.", "AuditLog; AIInteractionLog.", "None.", "GET /api/v1/audit-logs; GET /api/v1/ai-interactions; GET /api/v1/ai-interactions/{id}", "Audit logs screen.", "Export of sensitive content -> restricted to auditor role.", "Audit logs are read-only; access to them is itself audited.", "Tamper-evident log chain (P1).", {"primary": "System auditor", "deps": "SEC-009; SEC-011"}),
    ("ADM-018", "Data-retention configuration", "P1", "Configure retention periods per data class.", "Compliance with retention policy once decided.", "Retention policy.", "None.", "PATCH /api/v1/admin/settings (retention, P1)", "Retention settings.", "Retention below legal minimum -> blocked (minimums: Decision required).", "Retention jobs log what was purged.", "Legal holds.", {"primary": "Platform administrator"}),
])

# ------------------------------------------------------------ J. ANALYTICS
category(
    "J", "ANA", "Analytics", "Analytics",
    "Training manager", "Department administrator; Organization administrator",
    "PRO-005 (learning history); SEC-002 (RBAC)",
    "Analytics are decision support with interpretation notes; they never trigger employment actions.",
    "Aggregates suppress groups below a minimum size; no individual rankings; access scoped by role.",
    "Every chart has a data table alternative and text summary.",
)

batch([
    ("ANA-001", "Competency heatmaps", "P1", "Organisation/department heatmaps (see CMP-003).", "See CMP-003.", "See CMP-003.", "See CMP-003.", "GET /api/v1/analytics/competency-heatmap (P1)", "Department heatmap screen.", "See CMP-003.", "See CMP-003.", "See CMP-003.", {"alias_of": "CMP-003"}),
    ("ANA-002", "Organization skill gaps", "P1", "Most common gaps across the organisation.", "Prioritises central training investment.", "Aggregated gaps.", "None.", "GET /api/v1/analytics/gaps (P1)", "Gap summary chart.", "Insufficient data -> not shown.", "Counts only estimates with sufficient evidence.", "Demand forecasting (ANA-012)."),
    ("ANA-003", "Department comparisons", "P1", "Compares aggregated indicators between departments.", "Targeted support.", "Aggregates.", "None.", "GET /api/v1/analytics/departments/compare (P1)", "Comparison view with caveats.", "Different role mixes -> caveat.", "Comparisons include context caveats and suppression.", "Normalised comparisons."),
    ("ANA-004", "Course completion analytics", "P1", "Completion rates of courses and path items.", "Catalogue effectiveness.", "Progress records.", "None.", "GET /api/v1/analytics/courses (P1)", "Completion chart.", "External completions unknown -> internal only.", "Source of completion data stated.", "iGOT completions (IGOT-006)."),
    ("ANA-005", "Assessment performance", "P1", "Aggregated assessment outcomes.", "Assessment and training design.", "Attempts.", "None.", "GET /api/v1/analytics/assessments (P1)", "Performance distribution.", "Small samples -> suppressed.", "No individual identification in aggregate views.", "Item analysis (ASM-026)."),
    ("ANA-006", "Engagement analytics", "P1", "Active use and learning activity trends.", "Adoption monitoring.", "LearningActivity.", "None.", "GET /api/v1/analytics/engagement (P1)", "Engagement trends.", "Tracking disabled -> partial.", "Uses product analytics events only (PRD.md §19).", "Cohort analysis."),
    ("ANA-007", "Improvement analytics", "P1", "Aggregated baseline-to-post change.", "Evidence of programme impact.", "Comparable estimates.", "None.", "GET /api/v1/analytics/improvement (P1)", "Before/after aggregate.", "Non-comparable -> excluded.", "Only comparable assessments aggregated.", "Training effectiveness (ANA-008)."),
    ("ANA-008", "Training effectiveness", "P1", "Links training completion to later improvement (associational, not causal).", "Informs training design.", "Completions; improvement.", "None.", "GET /api/v1/analytics/training-effectiveness (P1)", "Effectiveness view with causal caveat.", "Confounding -> caveat.", "Displays 'association, not causation' caveat.", "Controlled evaluations."),
    ("ANA-009", "Training ROI placeholders", "P2", "Placeholder metrics pending an agreed ROI method.", "Future budgeting insight.", "Cost data (not available).", "None.", "Not defined until P2 design.", "Placeholder panel.", "No cost data -> placeholder only.", "No ROI figures shown until method approved.", "Cost models."),
    ("ANA-010", "Trend analysis", "P2", "Longitudinal trends of capability indicators.", "Strategic planning.", "Historical aggregates.", "Time-series methods.", "Not defined until P2 design.", "Trend charts.", "Method changes -> series breaks.", "Series breaks annotated.", "Forecasting."),
    ("ANA-011", "Demand prediction", "P2", "Predicts future training demand.", "Capacity planning.", "Historical demand.", "Forecasting models.", "Not defined until P2 design.", "Not defined until P2 design.", "Insufficient history -> unavailable.", "Validated before display.", "Skill-demand forecasting."),
    ("ANA-012", "Skill-demand forecasting", "P2", "Forecasts future competency needs.", "Workforce planning.", "Role changes; external signals.", "Forecasting.", "Not defined until P2 design.", "Not defined until P2 design.", "As ANA-011.", "As ANA-011.", "FUT-002.", {"alias_of": "FUT-002"}),
    ("ANA-013", "Recommendation effectiveness", "P1", "Acceptance, dismissal and completion rates of recommendations.", "Improves recommendation rules.", "Recommendation feedback.", "None.", "GET /api/v1/analytics/recommendations (P1)", "Effectiveness dashboard.", "Low volume -> not computed.", "Metrics defined in PRD.md §18.", "A/B evaluation (P2)."),
    ("ANA-014", "Learning-path effectiveness", "P2", "Outcome of learners following paths vs not.", "Path design.", "Paths; improvement.", "Causal methods.", "Not defined until P2 design.", "Not defined until P2 design.", "Confounding -> caveat.", "Methodology reviewed.", "Experiments."),
    ("ANA-015", "Assessment quality analytics", "P1", "Item statistics and reviewer rejection reasons.", "Question bank quality.", "Answers; rejections.", "None.", "GET /api/v1/analytics/assessment-quality (P1)", "Item quality table.", "Small samples -> suppressed.", "Statistics shown with sample sizes.", "IRT diagnostics."),
    ("ANA-016", "AI quality analytics", "P1", "Validation pass rates, reviewer rejection rates, abstention and citation-verification rates.", "Monitors AI behaviour over time.", "AIInteractionLog; validations; review decisions.", "None.", "GET /api/v1/analytics/ai-quality (P1)", "AI quality dashboard.", "Logging gaps -> flagged.", "Metrics computed from logged data only; no untested accuracy claims.", "Drift detection.", {"primary": "Platform administrator", "secondary": "System auditor"}),
])

# ------------------------------------------------------------ K. TRAINER
category(
    "K", "TRN", "Trainer workspace", "Trainer workspace",
    "Trainer", "Training manager",
    "SEC-002 (RBAC); ASM-027 (review workflow)",
    "Trainers review and approve AI-generated content; trainer decisions are audited.",
    "Trainers see only assigned learners/departments and materials within scope.",
    "Dense review screens remain keyboard-first with visible focus and shortcuts documented.",
)

batch([
    ("TRN-001", "Trainer dashboard", "P0", "Trainer home: pending review tasks, generation jobs, recent uploads, learners needing attention (scoped).", "Trainers see their work queue at a glance.", "ReviewTask; jobs; scoped progress.", "None.", "GET /api/v1/trainer/dashboard (aggregate)", "Trainer dashboard screen.", "Partial data failure -> per-card error.", "Shows only scoped data; review counts match the review queue.", "Workload balancing (P1).", {"deps": "ADM-009; ADM-012"}),
    ("TRN-002", "Material upload", "P0", "Trainer-facing upload (see MAT-001/002/004).", "See MAT-001.", "See MAT-001.", "See MAT-001.", "See MAT-001", "Upload from Trainer dashboard.", "See MAT-001.", "See MAT-001.", "See MAT-001.", {"alias_of": "MAT-001"}),
    ("TRN-003", "Quiz generation", "P0", "Trainer-facing generation (see AI-007).", "See AI-007.", "See AI-007.", "See AI-007.", "See AI-007", "Quiz builder.", "See AI-007.", "See AI-007.", "See AI-007.", {"alias_of": "AI-007"}),
    ("TRN-004", "Quiz review", "P0", "Trainer-facing review (see ASM-027).", "See ASM-027.", "See ASM-027.", "See ASM-027.", "See ASM-027", "Quiz review screen.", "See ASM-027.", "See ASM-027.", "See ASM-027.", {"alias_of": "ASM-027"}),
    ("TRN-005", "Quiz editing", "P0", "Trainer-facing editing (see ASM-030).", "See ASM-030.", "See ASM-030.", "See ASM-030.", "See ASM-030", "Inline editor.", "See ASM-030.", "See ASM-030.", "See ASM-030.", {"alias_of": "ASM-030"}),
    ("TRN-006", "Quiz approval", "P0", "Trainer-facing approval (see ASM-028).", "See ASM-028.", "See ASM-028.", "See ASM-028.", "See ASM-028", "Approve action.", "See ASM-028.", "See ASM-028.", "See ASM-028.", {"alias_of": "ASM-028"}),
    ("TRN-007", "Quiz rejection", "P0", "Trainer-facing rejection (see ASM-029).", "See ASM-029.", "See ASM-029.", "See ASM-029.", "See ASM-029", "Reject action.", "See ASM-029.", "See ASM-029.", "See ASM-029.", {"alias_of": "ASM-029"}),
    ("TRN-008", "Manual question creation", "P0", "Trainers author questions manually with mandatory citation, entering the same review workflow.", "Assessment continues even where AI generation is unsuitable or unavailable.", "Question; Citation.", "Optional validation checks (ASM-022 to ASM-024).", "POST /api/v1/questions", "Question editor in Quiz builder.", "Missing citation -> cannot submit for review.", "Manually created questions are marked human-authored, require a citation, and follow the review policy.", "Question import (P1).", {"human_review": "Required per approval policy (second reviewer when configured)."}),
    ("TRN-009", "Assignment creation", "P1", "Trainer assigns assessments or materials (see ADM-011).", "See ADM-011.", "See ADM-011.", "See ADM-011.", "See ADM-011", "Assignment dialog.", "See ADM-011.", "See ADM-011.", "See ADM-011.", {"alias_of": "ADM-011"}),
    ("TRN-010", "Learner performance", "P1", "Detailed scoped learner performance views beyond MVP monitoring.", "Targeted coaching.", "Attempts; estimates (scoped).", "None.", "GET /api/v1/trainer/learners/{id}/performance (P1)", "Learner detail page.", "Out of scope -> 403.", "No ranking tables of individuals.", "Coaching notes."),
    ("TRN-011", "Weak-learner identification", "P1", "Highlights learners who may need support based on gaps and inactivity, framed as support signals.", "Early help.", "Gaps; activity (scoped).", "Rule-based signals.", "GET /api/v1/trainer/support-signals (P1)", "Support signal list with reasons.", "Insufficient evidence -> no signal.", "Signals are visible only to assigned trainers, state their reasons, and are labelled as support prompts, not performance judgements.", "Intervention tracking.", {"security": "Must not feed appraisal or disciplinary processes (SECURITY_RESPONSIBLE_AI.md §HID)."}),
    ("TRN-012", "Progress reports", "P1", "Trainer-level progress reports (see REP-007).", "See REP-007.", "See REP-007.", "See REP-007.", "See REP-007", "Reports screen.", "See REP-007.", "See REP-007.", "See REP-007.", {"alias_of": "REP-007"}),
    ("TRN-013", "Course effectiveness", "P1", "Trainer view of course effectiveness (see REP-006 / ANA-008).", "See ANA-008.", "See ANA-008.", "See ANA-008.", "See ANA-008", "Effectiveness view.", "See ANA-008.", "See ANA-008.", "See ANA-008.", {"alias_of": "ANA-008"}),
    ("TRN-014", "Feedback collection", "P1", "Collects learner feedback on courses, materials and questions.", "Continuous improvement.", "Feedback records.", "Optional LLM theme summarisation with review (P1).", "POST /api/v1/feedback (P1)", "Feedback forms.", "Abusive content -> moderation.", "Feedback can be anonymous where configured.", "Sentiment trends."),
    ("TRN-015", "Training recommendations", "P2", "Recommends training programmes to organise based on aggregate gaps.", "Programme planning.", "Aggregated gaps.", "Rule-based / forecasting.", "Not defined until P2 design.", "Not defined until P2 design.", "Low data -> none.", "Advisory only.", "Capability planning (FUT-018)."),
])

# ------------------------------------------- L. MULTILINGUAL AND ACCESSIBILITY
category(
    "L", "ACC", "Multilingual and accessibility", "Multilingual and accessibility",
    "Learner", "All users",
    "UX-001 (responsive design)",
    "Machine translations reviewed before publication; translated content keeps source provenance.",
    "No additional data exposure; speech features (P2) require consent for audio processing.",
    "Target WCAG 2.1 AA; GIGW applicability to be confirmed (DECISIONS.md DEC-026).",
)

batch([
    ("ACC-001", "English", "P0", "Complete English user interface.", "Primary working language of source materials.", "UI strings.", "None.", "Accept-Language / user locale", "All screens.", "Missing string -> key fallback logged.", "No hard-coded user-facing strings outside the i18n catalogue.", "Additional languages."),
    ("ACC-002", "Hindi", "P1", "Hindi user interface and support for Hindi content.", "Reach across Central and State officials.", "Translated strings; Hindi content.", "Machine translation with review (P1).", "Locale 'hi' (P1)", "Language switcher.", "Untranslated string -> English fallback labelled.", "Hindi UI reviewed by a human before release; Hindi rendering tested.", "Other Indian languages."),
    ("ACC-003", "Indian-language support architecture", "P0", "Internationalisation architecture: externalised strings, Unicode-safe storage, locale-aware formatting, font fallback for Indic scripts.", "Avoids costly retrofitting for Hindi and other languages.", "i18n catalogue.", "None.", "Locale negotiation", "Locale-ready components.", "Script rendering issues -> caught by visual tests.", "All UI text externalised; UTF-8 end to end; no language other than English claimed as supported in MVP.", "Language packs.", {"mvp": "In MVP - architecture only; no translations"}),
    ("ACC-004", "Translation workflow", "P1", "Draft translation, review and publish workflow for UI and content.", "Quality of translated material.", "Translation records.", "Machine translation drafts.", "P1", "Translation review screen.", "Terminology errors -> glossary.", "No machine translation published without review.", "Statistical glossary."),
    ("ACC-005", "Multilingual quizzes", "P1", "Questions available in Hindi with linked source language versions.", "Assessment in preferred language.", "Question translations.", "Translation drafts with review.", "P1", "Language toggle in assessments.", "Translation not reviewed -> English only.", "Translated items reviewed and linked to the source-language version.", "Other languages."),
    ("ACC-006", "Multilingual tutor", "P2", "Tutor in Hindi and other languages.", "Accessible tutoring.", "Multilingual retrieval.", "Multilingual models.", "Not defined until P2 design.", "Not defined until P2 design.", "Low-quality language -> fallback.", "Evaluated per language before enabling.", "Voice (FUT-012)."),
    ("ACC-007", "Text-to-speech", "P2", "Reads content aloud.", "Accessibility and low-literacy support.", "Text.", "TTS service.", "Not defined until P2 design.", "Play controls.", "Service down -> hidden.", "Consent and provider data terms verified.", "Voice interface."),
    ("ACC-008", "Speech-to-text", "P2", "Voice input.", "Accessibility.", "Audio.", "STT service.", "Not defined until P2 design.", "Mic control.", "Recognition errors -> editable text.", "Audio not retained without consent.", "Voice tutor."),
    ("ACC-009", "Screen-reader compatibility", "P0", "Semantic HTML, ARIA only where needed, live regions for async status.", "Usable by visually impaired officials.", "None.", "None.", "N/A", "All screens.", "Custom widget inaccessible -> replaced by accessible primitive.", "Automated axe checks pass and manual screen-reader test of core journeys completed before MVP release.", "Periodic audits."),
    ("ACC-010", "Keyboard navigation", "P0", "All functionality operable by keyboard with visible focus.", "Accessibility and power-user efficiency.", "None.", "None.", "N/A", "All screens.", "Focus trap -> test failure.", "Core journeys completable keyboard-only; focus order logical.", "Shortcut customisation."),
    ("ACC-011", "Font-size controls", "P1", "User-adjustable text size beyond browser zoom.", "Readability.", "User preference.", "None.", "PATCH /api/v1/me (preferences, P1)", "Settings control.", "Layout breaks -> responsive fixes.", "UI usable at 200% text size.", "Reading mode."),
    ("ACC-012", "High-contrast mode", "P1", "High-contrast theme.", "Low-vision support.", "Theme tokens.", "None.", "User preference (P1)", "Theme toggle.", "Contrast failures -> token fix.", "Meets enhanced contrast for text.", "System preference sync."),
    ("ACC-013", "Captions", "P2", "Captions for video/audio content.", "Hearing accessibility.", "Media transcripts.", "Optional STT drafts with review.", "Not defined until P2 design.", "Caption track.", "Missing captions -> media flagged.", "Media not published without captions.", "Transcript search."),
    ("ACC-014", "Accessible forms", "P0", "Labels, instructions, error summaries and inline errors linked to fields.", "Error-free data entry for all users.", "None.", "None.", "Validation errors mapped to fields (ERROR_HANDLING_SPEC.md)", "All forms.", "Unlabelled field -> lint failure.", "Every input has a programmatic label; errors announced and linked.", "Autosave."),
    ("ACC-015", "Accessible charts", "P0", "Charts with text summaries, data tables and non-colour encodings.", "Analytics usable by everyone.", "Chart data.", "None.", "N/A", "All charts.", "Chart library limitation -> table fallback.", "Every chart has a table alternative and meets contrast rules.", "Sonification (P2)."),
    ("ACC-016", "Reduced-motion support", "P0", "Respects prefers-reduced-motion; no essential motion.", "Vestibular accessibility.", "None.", "None.", "N/A", "Animations.", "Motion without fallback -> test failure.", "No animation is required to understand content.", "None."),
    ("ACC-017", "Low-bandwidth considerations", "P1", "Lightweight pages, lazy loading, text-first fallbacks, resumable uploads.", "Usable from field offices with poor connectivity.", "None.", "None.", "Pagination and compression", "Lite states.", "Slow network -> skeletons and retries.", "Core pages usable on a throttled connection profile defined in TESTING_STRATEGY.md.", "Offline mode (FUT-009)."),
])

# ------------------------------------------------------------ M. GAMIFICATION
category(
    "M", "GAM", "Gamification", "Gamification",
    "Learner", "Training manager",
    "PRO-001 (progress); ADM-014 (configuration)",
    "Rules configured by administrators; recognition awarded manually where it has any organisational significance.",
    "Opt-in; no public exposure of individual performance without consent; never used in appraisal.",
    "Badges and progress have text equivalents; no flashing effects.",
)

batch([
    ("GAM-001", "Points", "P1", "Points for completing learning activities (not for assessment scores).", "Motivation.", "LearningActivity.", "None.", "P1", "Points indicator.", "Gaming behaviour -> anti-gaming rules.", "Points never derived from competency scores.", "Levels."),
    ("GAM-002", "Badges", "P1", "Badges for milestones.", "Recognition.", "Badge definitions.", "None.", "GET /api/v1/me/badges (P1)", "Badge shelf.", "Duplicate award -> idempotent.", "Badge criteria visible.", "Verifiable badges."),
    ("GAM-003", "Streaks", "P1", "Consecutive learning-day streaks (see PRO-009).", "Habit building.", "Activity dates.", "None.", "P1", "Streak counter.", "Timezone issues -> user timezone.", "Streaks can be hidden by the learner.", "Streak freezes."),
    ("GAM-004", "Milestones", "P1", "Milestones such as baseline completed or path completed.", "Progress recognition.", "Progress events.", "None.", "P1", "Milestone timeline.", "None specific.", "Milestones based on objective events.", "Certificates."),
    ("GAM-005", "Levels", "P2", "Engagement levels.", "Long-term motivation.", "Points.", "None.", "Not defined until P2 design.", "Level indicator.", "Confusion with competency levels -> distinct naming.", "Never named like competency levels.", "None."),
    ("GAM-006", "Certificates", "P1", "Completion certificates for internal programmes.", "Formal recognition.", "Certificate records.", "None.", "GET /api/v1/me/certificates (P1)", "Certificate view/download.", "Revocation -> certificate marked revoked.", "Issued only on objective completion criteria; verifiable ID.", "AI certification (FUT-007)."),
    ("GAM-007", "Goals", "P1", "Engagement goals (see PER-016).", "See PER-016.", "See PER-016.", "See PER-016.", "See PER-016", "Goal widgets.", "See PER-016.", "See PER-016.", "See PER-016.", {"alias_of": "PER-016"}),
    ("GAM-008", "Professional leaderboards", "P2", "Opt-in leaderboards of learning activity (not competency).", "Friendly motivation where culturally appropriate.", "Opt-in activity data.", "None.", "Not defined until P2 design.", "Leaderboard.", "Non-consenting user shown -> blocked.", "Opt-in only, activity-based, aggregated by team where possible; never shows competency scores.", "Team challenges.", {"security": "High sensitivity: requires consent model and ethics review; excluded from MVP."}),
    ("GAM-009", "Team challenges", "P2", "Department-level learning challenges.", "Collective engagement.", "Aggregates.", "None.", "Not defined until P2 design.", "Challenge page.", "Small teams -> suppressed.", "Aggregate-only.", "None."),
    ("GAM-010", "Recognition", "P2", "Trainer-issued recognition notes.", "Human recognition.", "Recognition records.", "None.", "Not defined until P2 design.", "Recognition feed.", "Misuse -> moderation.", "Human-issued only.", "None."),
    ("GAM-011", "Anti-gaming safeguards", "P1", "Detects implausible activity patterns and prevents rewards for trivial actions.", "Keeps gamification meaningful.", "Activity logs.", "Rule-based.", "Internal (P1)", "None.", "False positive -> no penalty, only no reward.", "Safeguards never penalise learners, only withhold rewards.", "Anomaly detection."),
    ("GAM-012", "Optional gamification settings", "P1", "Organisation and user-level toggles.", "Respects organisational culture and preferences.", "Settings.", "None.", "PATCH /api/v1/admin/settings; PATCH /api/v1/me (P1)", "Toggles.", "None specific.", "Gamification off by default until enabled by organisation.", "Per-department settings."),
])

# ------------------------------------------------------- N. PROGRESS TRACKING
category(
    "N", "PRO", "Progress tracking", "Progress tracking",
    "Learner", "Trainer; Training manager",
    "SEC-002 (RBAC); AUT-012 (background jobs)",
    "Not required for objective progress records; corrections by administrators are audited.",
    "Progress data is personal data: self, assigned trainer and scoped managers only.",
    "Progress indicators have text values; charts have tables.",
)

batch([
    ("PRO-001", "Course progress", "P0", "Status of each course/path item: not started, in progress, completed (learner-marked or system-recorded).", "Learners and trainers see advancement.", "ProgressRecord; LearningPathItem.", "None.", "PATCH /api/v1/learning-path-items/{id}; GET /api/v1/me/progress", "Status controls in Learning path; progress bars.", "Offline completion (e.g. NSSTA programme) -> learner self-report labelled self-reported.", "Every status change records source (system / self-reported / administrator).", "iGOT completion sync (IGOT-006)."),
    ("PRO-002", "Quiz progress", "P0", "In-progress and completed attempts per assessment.", "Resume and completion visibility.", "AssessmentAttempt.", "None.", "GET /api/v1/me/attempts", "Attempt status on dashboard.", "Expired attempt -> marked expired.", "Resumable attempts clearly indicated.", "Attempt analytics."),
    ("PRO-003", "Competency progress", "P0", "Current estimate vs baseline per competency.", "Shows development direction.", "UserCompetency history (baseline + current).", "None.", "Included in GET /api/v1/me/competency-profile", "Baseline marker on profile.", "No baseline -> baseline pending.", "Baseline is immutable; changes shown with method-version caveats.", "Growth graphs (PRO-007)."),
    ("PRO-004", "Learning hours", "P1", "Estimated learning time from item durations and activity.", "Workload visibility.", "Durations; activity.", "None.", "P1", "Hours summary.", "Unknown durations -> excluded with note.", "Hours labelled as estimates.", "Calendar integration."),
    ("PRO-005", "Learning history", "P0", "Chronological record of the learner's completed items and attempts.", "Personal record of development.", "ProgressRecord; attempts.", "None.", "GET /api/v1/me/progress/history", "History list.", "Deleted content -> history entry retained with title snapshot.", "History entries keep title snapshots so deleted content does not break the record.", "Evidence timeline (PRO-014)."),
    ("PRO-006", "Scores", "P0", "Assessment scores within progress views.", "Quick performance recall.", "Attempts.", "None.", "GET /api/v1/me/attempts", "Scores column.", "Rescored -> updated with note.", "Rescoring noted.", "Trends."),
    ("PRO-007", "Growth graphs", "P1", "Charts of competency change over time.", "Visible improvement.", "Estimate history.", "None.", "GET /api/v1/me/competency-history (P1)", "Line charts with tables.", "Series breaks annotated.", "Accessible chart pattern used.", "Forecast overlays (P2)."),
    ("PRO-008", "Before-vs-after comparisons", "P1", "Baseline vs post-assessment comparison.", "Demonstrates learning impact.", "Pre/post estimates.", "None.", "GET /api/v1/me/improvement (P1)", "Before/after view.", "Non-comparable -> caveat.", "Caveats shown when item pools differ.", "Equated forms."),
    ("PRO-009", "Streaks", "P1", "Progress-side view of streaks (see GAM-003).", "See GAM-003.", "See GAM-003.", "See GAM-003.", "See GAM-003", "Streak counter.", "See GAM-003.", "See GAM-003.", "See GAM-003.", {"alias_of": "GAM-003"}),
    ("PRO-010", "Completed items", "P0", "List of completed path items and assessments.", "Sense of accomplishment; avoids repeats.", "ProgressRecord.", "None.", "GET /api/v1/me/progress?status=completed", "Completed tab.", "None specific.", "Completed items excluded from recommendations.", "Certificates."),
    ("PRO-011", "Pending items", "P0", "List of not-started and in-progress items.", "Clear to-do list.", "LearningPathItem.", "None.", "GET /api/v1/me/progress?status=pending", "Pending tab; Continue learning.", "None specific.", "Pending list matches the current learning path.", "Due dates (P1)."),
    ("PRO-012", "Recommended items", "P0", "Recommended items not yet in the path.", "Discovery.", "Recommendation.", "None.", "GET /api/v1/me/recommendations", "Recommended tab.", "None specific.", "Each item links to its reason.", "Saved items."),
    ("PRO-013", "Assessment timeline", "P0", "Chronological view of assessments and resulting estimate changes.", "Understand how estimates evolved.", "Attempts; evidence.", "None.", "GET /api/v1/me/attempts (timeline view)", "Timeline component on Competency profile.", "None specific.", "Timeline entries link to results and evidence.", "Learning evidence timeline."),
    ("PRO-014", "Learning evidence timeline", "P1", "Combined timeline of assessment and learning evidence.", "Holistic development record.", "Evidence; activities.", "None.", "P1", "Timeline with type filters.", "Self-reported items labelled.", "Evidence types visually and textually distinguished.", "Skill passport."),
])
