"""Feature registry: categories A (Core AI), B (Learning material), C (Quiz and assessment)."""

from registry_common import F, category, PART, MOCK, PLAN, BLOCK, HUMAN

API = "Planned internal API (docs/API_INTEGRATION_SPEC.md): "

# ---------------------------------------------------------------- A. CORE AI
category(
    "A", "AI", "Core AI intelligence", "Core AI intelligence",
    "Learner", "Trainer; Competency framework administrator",
    "SEC-002 (RBAC); CMP-001 (competency profile)",
    "Required: estimates and generated artefacts are reviewable and correctable by authorised humans; never used for automated employment decisions (SECURITY_RESPONSIBLE_AI.md §HID).",
    "Organisation-scoped data; learner personal data never sent to an AI provider without authorisation (RAI-016); every AI call logged (SEC-011).",
    "Results readable by screen readers; charts have table equivalents; plain-language explanations.",
)

F("AI-001", "AI-based competency assessment", "P0",
  "Runs a role-based initial assessment built only from human-approved questions and converts the results into per-competency estimates. AI assists question creation; the score calculation itself is deterministic in MVP.",
  "Gives each learner an evidence-based starting point instead of a self-declared skill list.",
  "Approved Question records tagged to competency, topic and difficulty; RoleCompetency required levels; AssessmentAttempt and Answer records.",
  "Indirect: questions are AI-generated then human-approved (AI-007, ASM-027). Scoring is rule-based (AI_SYSTEM_SPEC.md §25).",
  API + "POST /api/v1/assessments/{id}/attempts; PUT /api/v1/attempts/{id}/answers/{question_id}; POST /api/v1/attempts/{id}/submit; GET /api/v1/attempts/{id}/result",
  "Assessment screen; Assessment results screen (UI_UX_SPEC.md).",
  "Too few approved questions for a competency -> that competency is reported as 'insufficient evidence'. Session interrupted -> attempt resumable until expiry.",
  "An attempt produces estimates only from approved questions; each estimate links to its evidence; competencies below the minimum item count show 'insufficient evidence' instead of a score.",
  "Adaptive item selection (AI-008); IRT calibration (FUT-006).",
  deps="ROLE-002; ASM-011; ASM-027; AI-012")

F("AI-002", "Competency-gap detection", "P0",
  "Compares each estimated competency level with the level required by the learner's selected job role and lists gaps by size.",
  "Turns assessment results into a concrete, prioritised development need.",
  "UserCompetency estimates with evidence sufficiency; RoleCompetency required levels.",
  "None in MVP: deterministic comparison (AI_SYSTEM_SPEC.md §25).",
  API + "GET /api/v1/me/competency-gaps; GET /api/v1/users/{id}/competency-gaps (scoped roles)",
  "Competency-gap analysis screen.",
  "No job role selected -> prompt to select one. Role has no required levels -> 'role not configured' shown to learner and competency administrator.",
  "A gap is shown only when a required level exists and evidence sufficiency is at least 'medium'; each gap shows required level, estimated level, evidence link and suggested next step.",
  "Critical-skill weighting (CMP-005); competency dependencies (CMP-010).",
  deps="AI-012; ROLE-002; AI-017")

F("AI-003", "Role mapping", "P1",
  "Suggests the most likely configured job role from department, designation and a free-text description of responsibilities.",
  "Speeds onboarding where designations do not map cleanly to configured roles.",
  "JobRole names and descriptions; user-entered responsibilities text.",
  "LLM classification against configured roles with stated reasons.",
  API + "POST /api/v1/job-roles/suggestions (P1)",
  "Suggestion panel inside Onboarding with accept / choose another.",
  "Low-confidence classification -> no suggestion; free text containing personal data -> redacted before provider call.",
  "A suggestion never changes the user's role without explicit confirmation; reasons are shown for every suggestion.",
  "Role transition pathways (ROLE-010).",
  deps="ROLE-001; RAI-016",
  human_review="Required: the user or an administrator confirms every suggested role.")

F("AI-004", "Personalized learning-path generation", "P0",
  "Builds an ordered learning path of courses, NSSTA programme listings and approved materials addressing the learner's largest gaps.",
  "Converts gaps into an actionable sequence rather than an unordered list.",
  "Gaps (AI-002); Course and LearningMaterial with human-approved competency/topic mappings; completion status.",
  "Rule-based ranking with template explanations in MVP; no LLM (AI_SYSTEM_SPEC.md §26-27).",
  API + "GET /api/v1/me/learning-path; POST /api/v1/me/learning-path/regenerate; PATCH /api/v1/learning-path-items/{id}",
  "Learning path screen; 'Continue learning' card on Learner dashboard.",
  "No approved content mapped to a gap -> item 'No approved content yet' plus a signal to the training manager.",
  "Every item states the gap it addresses and the rule that selected it; regenerating with unchanged inputs yields the same ordering.",
  "Time-boxed plans (PER-005/006); prerequisite ordering (PER-007).",
  deps="AI-002; AI-005; ADM-005")

F("AI-005", "AI course recommendation", "P0",
  "Recommends internal courses, NSSTA programme listings and approved learning materials relevant to the learner's gaps and role.",
  "Directs limited training time to the most relevant content.",
  "Course, LearningMaterial, CourseCompetency/topic mappings (human-approved), gaps, completion history.",
  "Deterministic scoring in MVP (gap severity x competency/topic match, completed items excluded). LLM re-ranking is P1 and requires evaluation first.",
  API + "GET /api/v1/me/recommendations; POST /api/v1/recommendations/{id}/feedback",
  "Recommendation cards on Learner dashboard and Course discovery, each with a 'Why recommended' explanation.",
  "Empty catalogue -> empty state; mapping unreviewed (e.g. ASSUMED topic tags from data/processed) -> item excluded.",
  "Each recommendation shows reason, source organisation and provenance badge; iGOT items from the mock adapter carry a MOCK badge; dismissed items are not re-shown for the configured period.",
  "Collaborative signals and LLM re-ranking (P1, after offline evaluation).",
  deps="AI-002; ADM-005; RAI-011")

F("AI-006", "iGOT course recommendation", "P0",
  "Includes courses returned by the iGOT adapter in recommendations. Only the mock adapter exists, so in MVP these are mock records labelled as such.",
  "Demonstrates the integration path without claiming real iGOT access.",
  "Records from IGotClient.list_courses(); every mock record has data_status MOCK.",
  "Same deterministic scoring as AI-005.",
  API + "GET /api/v1/me/recommendations?source=igot; GET /api/v1/integrations/igot/courses",
  "MOCK badge and 'Not real iGOT data' text on every iGOT-sourced card.",
  "Adapter mode 'live' -> refused (AccessNotVerifiedError) and source hidden; mock disabled by flag -> source hidden, admins see 'not connected'.",
  "With IGOT_CLIENT_MODE=mock every iGOT-sourced item is visibly labelled MOCK; no code path presents mock data as real; the feature flag can disable the source entirely.",
  "Real recommendations after authorised access (IGOT-012).",
  status=MOCK, status_note="mock catalogue via clients/mock_igot_client.py (tests pass); recommendation logic not built.",
  mvp="In MVP - mock data only, feature-flagged",
  deps="IGOT-010; IGOT-011; AI-005",
  security="Never present mock data as external data; disable in production unless a verified real adapter exists (API_INTEGRATION_SPEC.md §iGOT).")

F("AI-007", "Quiz and MCQ generation", "P0",
  "Generates candidate multiple-choice questions from licence-permitted, approved document chunks using structured output; every candidate goes through validation and human review.",
  "Reduces trainer effort to create source-grounded question banks.",
  "DocumentChunk text from materials whose licence permits derivative use; Topic; Competency; generation parameters.",
  "LLM structured generation behind the provider interface (AI_SYSTEM_SPEC.md §21).",
  API + "POST /api/v1/question-generation-jobs; GET /api/v1/question-generation-jobs/{id}",
  "Quiz builder (select sources, topic, competency, count, difficulty) with job progress.",
  "Provider timeout -> retry with backoff; schema-invalid output -> discarded and logged; zero valid questions -> job completes with reasons.",
  "Every generated question stores source chunk IDs, evidence span, model, prompt version, timestamp and validation status, and starts as 'pending_validation'; none is learner-visible before approval.",
  "True/false, fill-in-the-blank, scenario types (ASM-002 to ASM-005); multilingual generation (ACC-005).",
  deps="MAT-010; ASM-022; ASM-027; RAI-019",
  human_review="Required: no generated question is used in an assessment before approval.")

F("AI-008", "Adaptive assessment", "P1",
  "Chooses the next question based on responses so far, stepping difficulty up or down within a competency.",
  "Shorter assessments with better precision at the learner's level.",
  "Approved questions with calibrated difficulty; response history.",
  "Rule-based staircase in P1; IRT-based selection is FUT-006.",
  API + "POST /api/v1/attempts/{id}/next-question (P1)",
  "Assessment screen shows progress without revealing difficulty.",
  "Item pool exhausted -> assessment ends with evidence-sufficiency note.",
  "Adaptive rules are documented and versioned; an attempt can be replayed to reproduce the item sequence.",
  "IRT (FUT-006); knowledge tracing (FUT-004).",
  deps="AI-001; ASM-026")

F("AI-009", "Answer evaluation", "P0",
  "Scores objective answers (MCQ in MVP) against the approved answer key.",
  "Immediate, consistent scoring.",
  "Approved question version and answer key; Answer.",
  "None: deterministic.",
  API + "POST /api/v1/attempts/{id}/submit",
  "Assessment results screen.",
  "Answer key later corrected -> affected attempts re-scored with an audit record and learner notice.",
  "Scoring uses the question version shown to the learner; re-scoring after a key correction is logged and visible to the learner.",
  "Short-answer and scenario evaluation (AI-010, AI-011).",
  deps="ASM-031; ASM-017",
  human_review="Not required for deterministic scoring; answer-key corrections are human actions and audited.")

F("AI-010", "Short-answer evaluation", "P1",
  "Scores short free-text answers against an approved rubric and reference answer, citing the rubric criteria met.",
  "Assesses understanding beyond recognition.",
  "Rubric, reference answer, source citations, learner answer.",
  "LLM rubric scoring with structured output and evidence spans.",
  API + "POST /api/v1/attempts/{id}/submit (async evaluation job, P1)",
  "Result shows criteria met / not met and 'pending review' state.",
  "Low-confidence or out-of-rubric answer -> routed to manual evaluation (ASM-018).",
  "No LLM score contributes to a competency estimate until confirmed by a human during pilot; rubric version and model metadata stored.",
  "Calibration against human graders; multilingual answers.",
  deps="ASM-018; RAI-006")

F("AI-011", "Scenario evaluation", "P1",
  "Evaluates responses to scenario or case questions against a structured rubric.",
  "Assesses applied judgement in statistical work contexts.",
  "Scenario, rubric, reference points, learner response.",
  "LLM rubric scoring (same controls as AI-010).",
  API + "POST /api/v1/attempts/{id}/submit (P1)",
  "Rubric breakdown view.",
  "Ambiguous response -> manual evaluation.",
  "Human confirmation before contributing to competency estimates.",
  "Simulation-based learning (FUT-017).",
  deps="ASM-004; AI-010")

F("AI-012", "Competency score calculation", "P0",
  "Calculates a per-competency score from correct answers to approved questions, weighted by difficulty, and maps it to the framework's level scale.",
  "Consistent, reproducible, explainable scores.",
  "Answers; question difficulty and competency tags; configurable level thresholds per framework.",
  "None: deterministic, versioned method (AI_SYSTEM_SPEC.md §25). Thresholds are provisional until confirmed (ASSUMPTIONS_AND_OPEN_QUESTIONS.md).",
  API + "GET /api/v1/me/competency-profile; GET /api/v1/users/{id}/competency-profile",
  "Competency profile and Assessment results.",
  "Thresholds not configured for a framework -> score shown without a level plus 'levels not configured'.",
  "Same inputs always produce the same score; method version is stored with each estimate; the explanation lists contributing questions.",
  "IRT scoring (FUT-006); BKT (FUT-005).",
  deps="AI-009; ADM-004",
  human_review="Method and thresholds approved by competency framework administrator; individual adjustments via CMP-019.")

F("AI-013", "Learning-outcome prediction", "P2",
  "Predicts the likelihood that a learner reaches a target level given a learning plan.",
  "Helps plan realistic development timelines.",
  "Historical attempts and outcomes (none exist today).",
  "Statistical/ML model requiring validation data.",
  API + "Not defined until P2 design.",
  "Not defined until P2 design.",
  "Insufficient history -> feature unavailable.",
  "Not built until validated historical data exists and a fairness review is complete.",
  "Workforce intelligence (FUT-013).",
  deps="PRO-005; RAI-010",
  human_review="Required: predictions are advisory and never used for employment decisions.")

F("AI-014", "Weak-topic detection", "P1",
  "Aggregates incorrect answers by topic to highlight topics needing revision.",
  "Finer-grained guidance than competency-level gaps.",
  "Answers with topic tags.",
  "Rule-based aggregation.",
  API + "GET /api/v1/me/weak-topics (P1)",
  "Weak topics panel on Competency profile.",
  "Too few answers per topic -> topic not flagged.",
  "A topic is flagged only above a minimum answer count; each flag links to the answers behind it.",
  "Spaced repetition (PER-015).",
  deps="AI-009; ADM-015")

F("AI-015", "Reassessment recommendations", "P1",
  "Suggests reassessment when path items for a gap are completed or a configured interval has passed.",
  "Closes the loop between learning and measured improvement.",
  "Learning path completion; last attempt dates.",
  "Rule-based triggers.",
  API + "GET /api/v1/me/recommendations?type=reassessment (P1)",
  "Reassessment card on Learner dashboard.",
  "No eligible post-assessment -> no suggestion.",
  "Suggestions state the trigger that produced them.",
  "Reminders via notifications (AUT-006).",
  deps="ASM-012; AI-004")

F("AI-016", "Evidence-based competency estimation", "P0",
  "Backs every competency estimate with explicit evidence records (attempt answers, human adjustments) and refuses to estimate without evidence.",
  "Estimates can be inspected, challenged and corrected.",
  "CompetencyEvidence linked to Answer, AssessmentAttempt, adjustment records.",
  "None: estimates are derived from evidence records.",
  API + "GET /api/v1/users/{id}/competencies/{competency_id}/evidence",
  "Evidence panel in Competency profile.",
  "Evidence voided (e.g. question withdrawn) -> estimate recomputed and change logged.",
  "No estimate exists without at least one evidence record; each estimate lists its evidence; voiding evidence recomputes the estimate with an audit entry.",
  "Evidence ledger and skill passport (CMP-016, CMP-015).",
  deps="AI-012; CMP-016")

F("AI-017", "Confidence scoring", "P0",
  "Assigns each estimate an evidence-sufficiency band (insufficient / low / medium / high) from item count and validation status. It is not a statistical accuracy claim.",
  "Prevents over-interpretation of thin evidence.",
  "Item counts per competency; question validation statuses.",
  "None: rule-based bands with provisional thresholds.",
  API + "Included in competency profile and gap responses.",
  "Band label with definition tooltip and plain-language limitation text.",
  "Thresholds not configured -> default provisional thresholds displayed as provisional.",
  "Every displayed estimate shows its band and the definition of that band; 'insufficient' estimates never produce gaps.",
  "Statistical confidence intervals after calibration (FUT-006).",
  deps="AI-012")

F("AI-018", "Explainable competency results", "P0",
  "Shows how each estimate was produced: method version, evidence, required level, limitations, how to improve and how to request a correction.",
  "Supports trust, contestability and human oversight.",
  "Estimate, evidence, method version, required level, limitation text.",
  "None in MVP (template-based explanation).",
  API + "GET /api/v1/me/competency-profile (includes explanation block)",
  "'How was this calculated?' panel on Competency profile and Assessment results.",
  "Missing evidence metadata -> estimate hidden and flagged to administrators.",
  "Every estimate has an explanation panel with method, evidence, limitations and a correction-request action.",
  "Natural-language explanations generated from structured evidence (P1, reviewed).",
  deps="AI-016; RAI-018")

# ---------------------------------------------------- B. LEARNING MATERIAL
category(
    "B", "MAT", "Learning material intelligence", "Learning material intelligence",
    "Trainer", "Learner; Organization administrator",
    "SEC-012 (document ACL); AUT-012 (background jobs)",
    "Uploader attests right-to-use and absence of personal data; materials with restricted licences are excluded from AI generation (DATA_PROVENANCE.md).",
    "File-type and signature validation, size limits, malware-scanning placeholder, document ACLs, no execution of embedded content (SECURITY_RESPONSIBLE_AI.md §Upload).",
    "Upload and processing status keyboard-operable with live-region announcements; text alternatives for document previews.",
)

F("MAT-001", "PDF upload", "P0",
  "Uploads PDF learning materials into a learning material record for processing.",
  "PDF is the dominant format of NSSTA and MoSPI material.",
  "File bytes; uploader; material metadata (title, organisation, licence/usage notes, access scope).",
  "None at upload.",
  API + "POST /api/v1/learning-materials; POST /api/v1/learning-materials/{id}/documents (multipart)",
  "Upload dialog in Document library with licence attestation.",
  "Wrong type or failed %PDF- signature -> rejected; over size limit -> rejected; duplicate SHA-256 -> linked to existing document.",
  "Only files passing MIME, signature and size checks are stored; SHA-256 recorded; a processing job is queued and its status visible.",
  "Bulk upload; version supersession (MAT-027).",
  status=PART, status_note="offline collector downloads public PDFs with signature/size checks (scripts/collectors/fetch_documents.py); no user upload.")

F("MAT-002", "DOCX upload", "P0",
  "Uploads Word documents for processing.",
  "Trainer-authored material is often in DOCX.",
  "File bytes and material metadata.",
  "None at upload.",
  API + "POST /api/v1/learning-materials/{id}/documents",
  "Same upload dialog as MAT-001.",
  "Macro-enabled or malformed files rejected.",
  "DOCX accepted after type validation; macro-enabled formats (.docm) rejected.",
  "Tracked-change handling.")

F("MAT-003", "PPT/PPTX upload", "P1",
  "Uploads presentation files, extracting slide text and speaker notes.",
  "Training decks are common in NSSTA programmes.",
  "File bytes; slide structure.",
  "None at upload.",
  API + "POST /api/v1/learning-materials/{id}/documents (P1 types)",
  "Upload dialog; slide-level viewer.",
  "Image-only slides -> require OCR (MAT-006).",
  "Slide numbers preserved for citations.",
  "Slide-level summaries.")

F("MAT-004", "TXT upload", "P0",
  "Uploads plain-text materials.",
  "Lowest-risk format for notes and extracted text.",
  "File bytes (UTF-8 required) and metadata.",
  "None at upload.",
  API + "POST /api/v1/learning-materials/{id}/documents",
  "Same upload dialog.",
  "Non-UTF-8 encoding -> rejected with guidance.",
  "UTF-8 text accepted; encoding errors rejected with a clear message.",
  "Markdown support.")

F("MAT-005", "Image upload", "P1",
  "Uploads images (scans, charts) for OCR-based extraction.",
  "Captures scanned material such as NSSTA-DOC-004/006.",
  "Image bytes.",
  "OCR (MAT-006).",
  API + "POST /api/v1/learning-materials/{id}/documents (P1 types)",
  "Upload dialog with OCR notice.",
  "Unreadable image -> 'no text extracted'.",
  "Images are processed only through OCR and stored with the same ACL as documents.",
  "Chart description with review.",
  deps="MAT-006")

F("MAT-006", "OCR", "P1",
  "Extracts text from scanned PDFs and images, including Hindi where the OCR engine supports it.",
  "Two collected NSSTA documents are scanned and currently unreadable.",
  "Page images.",
  "OCR engine (candidate: Tesseract - Decision required, TECH_STACK.md).",
  API + "Processing job step (P1)",
  "OCR-confidence indicator in Document viewer.",
  "Low OCR confidence -> text flagged 'OCR - verify' and excluded from question generation.",
  "OCR output is marked as OCR-derived with confidence and is excluded from generation until reviewed.",
  "Layout-aware OCR; table extraction.",
  status_note="not available; 2 collected NSSTA PDFs have no text layer (docs/DATA_COLLECTION_RESULTS.md).")

F("MAT-007", "Text extraction", "P0",
  "Extracts text with page numbers from uploaded PDF, DOCX and TXT files.",
  "Foundation for search, Q&A and question generation.",
  "Stored document file.",
  "None: parser-based.",
  API + "Processing job step; GET /api/v1/documents/{id}",
  "Processing status and 'no text layer' warning.",
  "No text layer -> status 'needs_ocr'; parser error -> status 'failed' with retry.",
  "Extracted text keeps page boundaries; documents without a text layer are flagged, not silently indexed as empty.",
  "Layout and table extraction.",
  status=PART, status_note="pypdf extraction for collected PDFs in an offline script (scripts/utils/extract_pdf_metadata.py); no application pipeline.")

F("MAT-008", "Text cleaning", "P0",
  "Removes repeated headers/footers, hyphenation artefacts and control characters while preserving page mapping.",
  "Improves retrieval and question quality.",
  "Extracted page text.",
  "None: rule-based.",
  API + "Processing job step",
  "None beyond processing status.",
  "Over-aggressive cleaning -> original text retained alongside cleaned text for audit.",
  "Cleaning is reversible (original retained) and rules are versioned.",
  "Language-specific cleaning for Hindi.")

F("MAT-009", "Document normalization", "P0",
  "Converts all formats into one internal representation (document -> pages -> text blocks) with character offsets.",
  "One downstream pipeline for all formats; stable citation offsets.",
  "Cleaned text per page.",
  "None.",
  API + "Processing job step",
  "None.",
  "Offsets inconsistent -> job fails validation.",
  "Every block has page number and character offsets usable by citations.",
  "Structural elements (headings, tables).")

F("MAT-010", "Chunking", "P0",
  "Splits normalised text into retrieval chunks that never lose their page span, with configurable size and overlap.",
  "Retrieval quality and page-level citations.",
  "Normalised blocks.",
  "None: deterministic chunker (AI_SYSTEM_SPEC.md §12).",
  API + "Processing job step",
  "Chunk count shown in document details (admin).",
  "Oversized block -> split at sentence boundaries.",
  "Each chunk stores page_start, page_end, char offsets and chunker version; re-chunking the same input is deterministic.",
  "Structure-aware chunking.")

F("MAT-011", "Metadata enrichment", "P0",
  "Attaches organisation, licence, topics, competencies, language and provenance metadata to documents and chunks.",
  "Enables filtered retrieval and licence-aware generation.",
  "Material metadata; topic taxonomy; source provenance.",
  "Rule-based topic tagging in MVP (marked ASSUMED until reviewed).",
  API + "PATCH /api/v1/learning-materials/{id}",
  "Metadata panel in Document viewer with review state of each tag.",
  "Unreviewed tags -> not used for recommendations.",
  "Every tag records its method and review status; licence metadata is required before AI generation is enabled.",
  "LLM-assisted tagging with review (MAT-022).",
  status=PART, status_note="rule-based topic tags and PDF metadata exist in offline scripts (scripts/processing/topic_taxonomy.json, ASSUMED).")

F("MAT-012", "Embedding generation", "P0",
  "Creates vector embeddings for chunks through the embedding provider interface, recording model and dimension.",
  "Enables semantic search and RAG.",
  "Chunk text.",
  "Embedding model behind an interface (embedding provider: Decision required, DECISIONS.md DEC-006).",
  API + "Processing job step",
  "None beyond status.",
  "Provider unavailable -> retry with backoff; model change -> re-embedding job.",
  "Every embedding stores model ID, dimension and created_at; switching models never mixes vectors from different models in one index.",
  "Multilingual embeddings for Hindi.",
  status_note="no application code; embedding provider not selected.")

F("MAT-013", "Vector storage", "P0",
  "Stores embeddings in PostgreSQL with pgvector, scoped by organisation and document ACL.",
  "One database for relational and vector data.",
  "Embedding vectors.",
  "None.",
  API + "Internal service",
  "None.",
  "Index build failure -> search degrades to keyword mode with notice.",
  "Vector queries always filter by organisation and access scope; index type documented (DATA_MODEL.md).",
  "Dedicated vector store only if scale requires it (SYSTEM_ARCHITECTURE.md).")

F("MAT-014", "Semantic search", "P0",
  "Finds passages by meaning across documents the user may access.",
  "Discovers relevant content without exact keywords.",
  "Embeddings; ACLs.",
  "Embedding similarity.",
  API + "POST /api/v1/search (mode=semantic)",
  "Search in Document library with page-linked results.",
  "Embedding service down -> fall back to keyword search with visible notice.",
  "Results never include documents the user cannot access; each result links to document and page.",
  "Hybrid ranking (MAT-016).")

F("MAT-015", "Keyword search", "P0",
  "Full-text search using PostgreSQL text search, important for acronyms such as PLFS, CPI and NSS.",
  "Exact-term lookup for statistical terminology.",
  "Chunk text with full-text index.",
  "None.",
  API + "POST /api/v1/search (mode=keyword)",
  "Search mode toggle in Document library.",
  "Query syntax error -> treated as plain text.",
  "Exact acronyms are found; ACL filtering identical to semantic search.",
  "Hindi text-search configuration.")

F("MAT-016", "Hybrid search", "P1",
  "Combines semantic and keyword results with a fusion ranking.",
  "Better recall and precision than either mode alone.",
  "Both indexes.",
  "Rank fusion (e.g. reciprocal rank fusion) - to be evaluated.",
  API + "POST /api/v1/search (mode=hybrid, P1)",
  "Default search mode after evaluation.",
  "One mode fails -> results from the other mode with notice.",
  "Adopted only if offline evaluation shows improvement over P0 modes.",
  "Reranking model (AI_SYSTEM_SPEC.md §15).")

F("MAT-017", "Document Q&A", "P0",
  "Answers a user's question using only retrieved passages from accessible documents, with citations, or abstains.",
  "Fast, source-grounded answers from official material.",
  "Retrieved chunks; question.",
  "RAG with LLM behind provider interface (AI_SYSTEM_SPEC.md §11).",
  API + "POST /api/v1/document-qa",
  "Document Q&A screen with citation list and confidence/abstention display.",
  "No sufficiently relevant passage -> abstain; citation verification fails -> answer withheld and abstention shown.",
  "Every displayed answer has at least one verified citation to an accessible document page; otherwise the system abstains; every interaction is logged.",
  "Conversational tutor (TUT-001).",
  deps="MAT-014; MAT-019; RAI-001; RAI-015")

F("MAT-018", "RAG responses", "P0",
  "Orchestrates retrieval, prompt assembly, generation, citation verification and abstention for grounded answers.",
  "Single controlled pipeline for all grounded generation.",
  "Chunks, prompt template versions.",
  "LLM generation with retrieved context treated as untrusted data.",
  API + "Internal service used by POST /api/v1/document-qa",
  "None directly.",
  "Provider error -> safe error state; prompt-injection indicators -> response restricted and flagged.",
  "Pipeline logs retrieved chunk IDs, prompt version, model, citations and verification result for every response.",
  "Tool-augmented retrieval (P2).",
  deps="MAT-013; RAI-007; RAI-019")

F("MAT-019", "Source citations", "P0",
  "Attaches citations (document, page, quoted span) to generated answers and questions.",
  "Users can verify every claim against official material.",
  "Chunk provenance; source URL and organisation.",
  "Citation generation plus automated verification (AI_SYSTEM_SPEC.md §16-17).",
  API + "Citation objects in document-qa and question responses",
  "Citation chips opening Document viewer at the cited page.",
  "Cited span not found in chunk -> citation rejected.",
  "Every citation resolves to an existing, accessible chunk and its quoted span matches the source text.",
  "Paragraph-level anchors.",
  deps="MAT-010; RAI-002")

F("MAT-020", "Page-level citations where possible", "P0",
  "Shows page numbers for citations whenever page boundaries are known (PDF); formats without pages cite section or offset.",
  "Precise verification in long manuals (e.g. 353-page NAS Sources and Methods).",
  "Chunk page spans.",
  "None beyond MAT-019.",
  API + "Citation.page_start / page_end",
  "'p. 12' labels; viewer opens at page.",
  "Page unknown -> citation shows section/offset and no page claim.",
  "A page number is never shown unless derived from the source page mapping.",
  "Line-level highlighting.",
  deps="MAT-019")

F("MAT-021", "Document summaries", "P1",
  "Generates reviewed summaries of documents or sections with citations.",
  "Faster orientation in long documents.",
  "Chunks.",
  "LLM summarisation with citations.",
  API + "POST /api/v1/documents/{id}/summaries (P1)",
  "Summary tab in Document viewer with review badge.",
  "Citation verification failure -> summary not displayed.",
  "Summaries show citations and review status; unreviewed summaries are labelled.",
  "Section-level summaries.",
  deps="MAT-019; RAI-006")

F("MAT-022", "Topic extraction", "P1",
  "Suggests topics from the taxonomy for documents and chunks.",
  "Better filtering and linkage to competencies.",
  "Chunks; topic taxonomy.",
  "LLM or classifier suggestions; keyword rules exist today.",
  API + "POST /api/v1/learning-materials/{id}/topic-suggestions (P1)",
  "Tag suggestions with accept/reject.",
  "Low-confidence suggestion -> not proposed.",
  "Suggested topics are ASSUMED until accepted by a reviewer.",
  "Taxonomy expansion proposals.",
  status=PART, status_note="keyword rules only (scripts/processing/topic_taxonomy.json), ASSUMED status, offline.")

F("MAT-023", "Keyword extraction", "P1",
  "Extracts key terms per document for search facets.",
  "Improves discoverability.",
  "Chunks.",
  "Statistical term extraction; optional LLM.",
  API + "Processing job step (P1)",
  "Keyword facets in Document library.",
  "Noisy terms -> filtered by stop-list.",
  "Keywords shown with method label.",
  "Glossary building.")

F("MAT-024", "Concept extraction", "P2",
  "Identifies statistical concepts and relations for a knowledge graph.",
  "Foundation for competency graph and knowledge tracing.",
  "Chunks; concept vocabulary.",
  "LLM extraction with review.",
  API + "Not defined until P2 design.",
  "Not defined until P2 design.",
  "Hallucinated concepts -> rejected by source-span check.",
  "Every concept links to a source span.",
  "Competency graph (CMP-014).")

F("MAT-025", "Difficulty estimation", "P2",
  "Estimates reading difficulty of materials.",
  "Matches material to learner level.",
  "Text statistics; learner outcomes.",
  "Readability metrics plus calibration.",
  API + "Not defined until P2 design.",
  "Difficulty badge.",
  "Uncalibrated -> not shown.",
  "Shown only after calibration against learner data.",
  "Difficulty-based recommendations (PER-008).")

F("MAT-026", "Course categorization", "P1",
  "Suggests categories and competencies for courses and materials.",
  "Faster catalogue curation.",
  "Course metadata; taxonomy.",
  "Classifier/LLM suggestions with review.",
  API + "POST /api/v1/courses/{id}/category-suggestions (P1)",
  "Suggestion review in course management.",
  "Conflicting categories -> reviewer decides.",
  "No category is applied without reviewer acceptance.",
  "Automatic mapping of iGOT courses (IGOT-003).")

F("MAT-027", "Document versioning", "P1",
  "Links new uploads as versions of an existing material and marks superseded versions.",
  "Keeps citations stable while content evolves (e.g. revised CPI series).",
  "Document SHA-256; version chain.",
  "None.",
  API + "POST /api/v1/learning-materials/{id}/documents (version), GET /api/v1/learning-materials/{id}/versions (P1)",
  "Version history in Document viewer.",
  "Questions citing a superseded version -> flagged for review.",
  "Citations always reference the exact version used; superseded versions stay viewable to authorised users.",
  "Diff view.",
  human_review="Required when superseding a version cited by approved questions.")

F("MAT-028", "Document access control", "P0",
  "Restricts document visibility by organisation, department and access scope; enforced in search, Q&A, generation and download.",
  "Prevents exposure of restricted training material.",
  "Material access scope; user access roles.",
  "Retrieval filters exclude inaccessible chunks before any AI call.",
  API + "Enforced on all document, search, qa and generation endpoints",
  "Access scope selector on upload; 'restricted' indicators.",
  "ACL misconfiguration -> default deny.",
  "A user can never retrieve, cite or download a chunk from a document outside their scope; covered by automated authorisation tests.",
  "Attribute-based policies (P2).",
  deps="SEC-002; SEC-012")

F("MAT-029", "Processing status", "P0",
  "Tracks each document through uploaded -> extracting -> chunking -> embedding -> ready / needs_ocr / failed.",
  "Users know when material is usable.",
  "BackgroundJob records.",
  "None.",
  API + "GET /api/v1/documents/{id}; GET /api/v1/jobs/{id}",
  "Status chips and progress in Document library.",
  "Stuck job -> timeout marks failed with reason.",
  "Status reflects the latest job state within one polling interval; failures show a reason and retry action.",
  "Push updates (P1).",
  status=PART, status_note="offline collection logs record statuses (data/interim/*/collection_log.json); no application pipeline.")

F("MAT-030", "Failed-processing recovery", "P0",
  "Retries failed processing steps idempotently and allows manual reprocessing.",
  "Transient failures do not lose uploads.",
  "Job attempts and errors.",
  "None.",
  API + "POST /api/v1/documents/{id}/reprocess",
  "Retry button on failed documents.",
  "Repeated failure -> dead-letter state visible to platform administrator.",
  "Reprocessing never duplicates chunks or embeddings; retry count and errors recorded.",
  "Automatic remediation hints.",
  deps="AUT-013; AUT-015")

F("MAT-031", "Duplicate-document detection", "P0",
  "Detects exact duplicates by SHA-256 at upload; near-duplicate detection is future work.",
  "Avoids duplicate indexing and conflicting citations.",
  "File hashes.",
  "None.",
  API + "Upload response indicates duplicate_of",
  "Duplicate notice with link to existing material.",
  "Hash collision (theoretical) -> byte comparison.",
  "Uploading identical bytes links to the existing document instead of re-processing.",
  "Near-duplicate detection via embeddings (P1).",
  status=PART, status_note="SHA-256 checksums in collector sidecars (data/raw/*/*.meta.json); no upload flow.")

# ------------------------------------------------- C. QUIZ AND ASSESSMENT
category(
    "C", "ASM", "Quiz and assessment engine", "Quiz and assessment engine",
    "Learner", "Trainer; Competency framework administrator",
    "AI-007 (generation); ASM-027 (approval); SEC-002 (RBAC)",
    "Required for every AI-generated question before use; edits create new versions.",
    "Answer keys never sent to the client before submission; attempts bound to the authenticated user; organisation scoping; audit of edits and approvals.",
    "All question types operable by keyboard and screen reader; timers configurable with accommodations; no colour-only feedback.",
)

F("ASM-001", "MCQs", "P0",
  "Single-correct multiple-choice questions with four options, explanation and source citation.",
  "Objective, scalable measurement for initial assessment.",
  "Question, QuestionOption, Citation.",
  "Generated by AI-007 or authored manually (TRN-008).",
  API + "GET/POST /api/v1/questions; GET /api/v1/questions/{id}",
  "Assessment screen radio group; Quiz review editor.",
  "Fewer than two options or no correct option -> validation error.",
  "An MCQ is usable only with exactly one correct option, an explanation, a citation and approved status.",
  "Multi-select MCQ (P1).",
  deps="AI-007; ASM-027")

F("ASM-002", "True/false questions", "P1",
  "Binary statements with explanation and citation.",
  "Quick checks of factual understanding.",
  "Question.",
  "Generation P1.",
  API + "Question type 'true_false' (P1)",
  "Two-option control.",
  "Ambiguous statement -> validation flag.",
  "Same approval and citation rules as MCQ.",
  "Confidence-weighted answers.")

F("ASM-003", "Fill-in-the-blank questions", "P1",
  "Short exact or pattern-matched answers.",
  "Tests recall of definitions and terms.",
  "Question with accepted answers.",
  "Generation P1.",
  API + "Question type 'fill_blank' (P1)",
  "Text input with accessible label.",
  "Multiple valid spellings -> accepted-answer list.",
  "Accepted answers reviewed by a human.",
  "Numeric-tolerance answers.")

F("ASM-004", "Scenario-based questions", "P1",
  "Short work scenarios from statistical practice with structured choices or rubric answers.",
  "Measures applied judgement.",
  "Scenario text; rubric.",
  "Generation P1; evaluation AI-011.",
  API + "Question type 'scenario' (P1)",
  "Scenario panel with question.",
  "Scenario not grounded in sources -> rejected.",
  "Scenarios cite the methodology they draw on.",
  "Simulations (FUT-017).")

F("ASM-005", "Case-based questions", "P1",
  "Question sets sharing a longer case.",
  "Deeper assessment of analytical reasoning.",
  "Case, linked questions.",
  "Generation P1.",
  API + "Question type 'case' (P1)",
  "Case pane with question navigation.",
  "Case edited after approval -> linked questions re-reviewed.",
  "All questions of a case share one approved case version.",
  "Data-exercise cases.")

F("ASM-006", "Difficulty levels", "P0",
  "Tags each question as foundational, intermediate or advanced (reviewer-confirmed).",
  "Weighted scoring and balanced assessments.",
  "Question.difficulty.",
  "Proposed by generator; confirmed by reviewer.",
  API + "difficulty field on questions and generation jobs",
  "Difficulty selector in Quiz builder and review.",
  "Missing difficulty -> cannot approve.",
  "Every approved question has a reviewer-confirmed difficulty.",
  "Empirical difficulty (ASM-026).")

F("ASM-007", "Custom question count", "P0",
  "Lets trainers choose how many questions to generate or include (within configured limits).",
  "Fits assessments to available time.",
  "Generation parameters.",
  "None.",
  API + "count parameter on generation jobs and assessment blueprints",
  "Numeric input with min/max hints.",
  "Requested count above available approved questions -> warning and actual count shown.",
  "The assessment never silently contains fewer questions than configured without a visible warning.",
  "Blueprint templates.")

F("ASM-008", "Topic-based quizzes", "P0",
  "Builds quizzes restricted to selected topics.",
  "Targeted practice on specific methodology areas.",
  "Question topic tags (reviewed).",
  "None.",
  API + "POST /api/v1/assessments (blueprint with topic filters)",
  "Topic multi-select in Quiz builder.",
  "No approved questions for topic -> blocked with message.",
  "Quizzes contain only approved questions with the selected topics.",
  "Adaptive topic mixing.")

F("ASM-009", "Competency-based quizzes", "P0",
  "Builds quizzes covering selected competencies with per-competency minimum item counts.",
  "Produces sufficient evidence for competency estimates.",
  "Question competency tags.",
  "None.",
  API + "POST /api/v1/assessments (blueprint with competency filters)",
  "Competency selector showing available approved item counts.",
  "Insufficient items -> blueprint cannot be published.",
  "A competency-based quiz can be published only when each competency meets its minimum approved-item count.",
  "Adaptive assessment (AI-008).")

F("ASM-010", "Role-based quizzes", "P0",
  "Generates the initial assessment blueprint from the competencies required by a job role.",
  "One-click initial assessment per role.",
  "RoleCompetency; approved questions.",
  "None.",
  API + "POST /api/v1/assessments (blueprint from job_role_id)",
  "Role selector in Quiz builder.",
  "Role without mapped competencies -> blocked.",
  "Blueprint covers every competency mapped to the role or lists the competencies lacking items.",
  "Role readiness (ROLE-008).",
  deps="ROLE-002; ROLE-004")

F("ASM-011", "Pre-assessment", "P0",
  "Initial assessment taken after role selection, establishing baseline estimates.",
  "Baseline for gaps and later before-vs-after comparison.",
  "Assessment with purpose 'pre'.",
  "None.",
  API + "Assessment.purpose = 'pre'",
  "Onboarding step and dashboard prompt.",
  "Learner skips -> dashboard shows 'baseline pending'.",
  "A learner's first completed pre-assessment is stored as the baseline and never overwritten.",
  "Post-assessment (ASM-012).")

F("ASM-012", "Post-assessment", "P1",
  "Reassessment after learning to measure change against baseline.",
  "Evidence of improvement.",
  "Assessment purpose 'post'; baseline.",
  "None.",
  API + "Assessment.purpose = 'post' (P1)",
  "Before-vs-after view (PRO-008).",
  "Different item pools -> comparison caveat shown.",
  "Comparisons show caveats when item pools differ.",
  "Equated forms via IRT (FUT-006).")

F("ASM-013", "Certification assessment", "P2",
  "Formal assessments leading to certificates.",
  "Recognised credentials.",
  "Secure item pools; proctoring policy.",
  "None decided.",
  API + "Not defined until P2 design.",
  "Not defined until P2 design.",
  "Integrity breach -> attempt invalidated by human decision.",
  "Not built until governance for certification is approved.",
  "AI certification (FUT-007).",
  human_review="Required: certification outcomes need human sign-off.")

F("ASM-014", "Randomization", "P0",
  "Randomises question order and option order per attempt, recorded for reproducibility.",
  "Reduces answer sharing and position bias.",
  "Attempt seed.",
  "None.",
  API + "Attempt stores randomisation seed",
  "None visible.",
  "Seed missing -> attempt invalid.",
  "Each attempt stores its seed; the delivered order can be reconstructed exactly.",
  "Parallel forms.")

F("ASM-015", "Timers", "P1",
  "Optional time limits with accessibility extensions.",
  "Standardised conditions where required.",
  "Assessment time limit; accommodations.",
  "None.",
  API + "Assessment.time_limit (P1)",
  "Accessible countdown with warnings.",
  "Connection loss -> server-side time is authoritative.",
  "Timer extensions can be granted per user and are audited.",
  "Pause policies.")

F("ASM-016", "Attempt limits", "P1",
  "Limits the number of attempts per assessment.",
  "Prevents trial-and-error gaming.",
  "Attempt counts.",
  "None.",
  API + "Assessment.max_attempts (P1)",
  "Remaining attempts indicator.",
  "Limit reached -> start disabled with explanation.",
  "Limits enforced server-side.",
  "Cool-down periods.")

F("ASM-017", "Auto-evaluation", "P0",
  "Automatically scores objective questions on submission.",
  "Immediate results.",
  "Answers; keys.",
  "None (see AI-009).",
  API + "POST /api/v1/attempts/{id}/submit",
  "Results screen.",
  "Scoring error -> attempt marked 'scoring_failed' and retried.",
  "Submission returns a result or a retryable pending state; never a partial silent score.",
  "Short-answer evaluation (AI-010).",
  deps="AI-009",
  human_review="Not required for objective items.")

F("ASM-018", "Manual evaluation", "P1",
  "Trainer scoring of subjective answers with rubric.",
  "Human judgement where automation is unsuitable.",
  "Answers; rubrics.",
  "None (AI may pre-score in P1).",
  API + "POST /api/v1/answers/{id}/evaluations (P1)",
  "Grading queue for trainers.",
  "Grader conflict -> second review.",
  "Manual scores record grader and rationale.",
  "Moderation workflows.")

F("ASM-019", "Feedback", "P0",
  "Shows per-question correctness after submission (when the assessment policy allows).",
  "Learning from assessment.",
  "Answers; keys.",
  "None.",
  API + "GET /api/v1/attempts/{id}/result",
  "Result list with correct/incorrect indicators (icon + text).",
  "Policy hides answers -> only scores shown.",
  "Feedback visibility follows the assessment policy and never exposes other learners' data.",
  "Personalised feedback (P1).")

F("ASM-020", "Explanations", "P0",
  "Each approved question includes an explanation of the correct answer.",
  "Turns assessment into learning.",
  "Question.explanation.",
  "Drafted by generator; reviewed.",
  API + "Explanation included in result when policy allows",
  "Expandable explanation under each result item.",
  "Missing explanation -> question cannot be approved.",
  "Every approved question has a reviewed explanation.",
  "Explanations at multiple levels (TUT-005).")

F("ASM-021", "Source evidence", "P0",
  "Each approved question cites the document page and passage it is based on.",
  "Verifiability of every assessed fact.",
  "Citation linked to question version.",
  "Generated citations verified automatically (RAI-002).",
  API + "Citations included in question and result payloads",
  "'Source' link opening Document viewer.",
  "Cited document access revoked -> question suspended from use.",
  "An approved question always has a verified citation to an accessible document version.",
  "Multiple-source evidence.",
  deps="MAT-019")

F("ASM-022", "Duplicate detection", "P0",
  "Detects exact and near-duplicate questions within the question bank before review.",
  "Keeps the bank clean and assessments fair.",
  "Normalised question text; embeddings.",
  "Text normalisation hash + embedding similarity (threshold to be calibrated).",
  API + "Validation result on question",
  "Duplicate warning with link in Quiz review.",
  "Embedding unavailable -> exact-duplicate check only, flagged.",
  "Exact duplicates are blocked; suspected near-duplicates are flagged for the reviewer.",
  "Cross-language duplicates.",
  deps="MAT-012")

F("ASM-023", "Incorrect-answer detection", "P0",
  "An independent validation call answers the question from the cited source without seeing the key; disagreement flags the question.",
  "Catches wrong answer keys before review.",
  "Question, options, cited chunk.",
  "Independent LLM validation (AI_SYSTEM_SPEC.md §22).",
  API + "Validation result on question",
  "'Key disputed by validator' flag in Quiz review.",
  "Validator unavailable -> question marked 'validation_incomplete' and cannot be approved without explicit reviewer override.",
  "Disagreement between validator and key is always shown to the reviewer.",
  "Multi-validator consensus.")

F("ASM-024", "Hallucination detection", "P0",
  "Checks that the question's evidence span exists verbatim in the cited chunk and that the correct answer is supported by it.",
  "Blocks questions not grounded in sources.",
  "Evidence span; chunk text.",
  "Deterministic span match plus LLM support check.",
  API + "Validation result on question",
  "'Unsupported by source' flag.",
  "Span not found -> automatic rejection before review.",
  "No question with an unmatched evidence span reaches the review queue.",
  "Claim-level entailment models.",
  deps="RAI-004")

F("ASM-025", "Question quality scoring", "P1",
  "Scores clarity, distractor plausibility and alignment.",
  "Prioritises reviewer attention.",
  "Question; validator outputs.",
  "LLM rubric plus heuristics.",
  API + "Quality fields on question (P1)",
  "Quality badge in review queue.",
  "Unscored -> neutral.",
  "Quality score never approves a question on its own.",
  "Learner-response analytics (ASM-026).")

F("ASM-026", "Difficulty scoring", "P1",
  "Estimates empirical difficulty from learner responses.",
  "Calibrates weights and adaptive selection.",
  "Answer statistics.",
  "Classical test statistics (P1); IRT (P2).",
  API + "Question statistics (P1)",
  "Item statistics in question details.",
  "Too few responses -> not computed.",
  "Statistics computed only above a minimum response count.",
  "IRT (FUT-006).")

F("ASM-027", "Question review workflow", "P0",
  "Routes validated questions into a review queue with validator findings, source and history.",
  "Human oversight of all AI-generated assessment content.",
  "ReviewTask; QuestionValidation.",
  "None in the workflow itself.",
  API + "GET /api/v1/review-tasks; GET /api/v1/review-tasks/{id}; POST /api/v1/review-tasks/{id}/decision",
  "Quiz review screen.",
  "Reviewer lacks access to source -> task reassigned.",
  "Every AI-generated question passes through a review task; queue shows validator flags and source passage side by side.",
  "Dual review for certification items (P2).",
  human_review="This feature is the human review.")

F("ASM-028", "Question approval", "P0",
  "Reviewer approves a question version for use.",
  "Only reviewed content reaches learners.",
  "Approval record.",
  "None.",
  API + "POST /api/v1/review-tasks/{id}/decision (approve)",
  "Approve action with confirmation.",
  "Unresolved validation flags -> approval requires a written override reason.",
  "Approval records reviewer, timestamp, version and override reasons; self-approval of one's own manual questions is blocked when a second reviewer is configured.",
  "Approval policies per assessment type.")

F("ASM-029", "Question rejection", "P0",
  "Reviewer rejects a question with a reason category.",
  "Improves generation through feedback.",
  "Approval record with reason.",
  "Rejection reasons feed evaluation datasets.",
  API + "POST /api/v1/review-tasks/{id}/decision (reject)",
  "Reject action with reason picker.",
  "Missing reason -> blocked.",
  "Every rejection has a reason; rejected questions are never used.",
  "Automatic prompt improvement proposals (P1).")

F("ASM-030", "Question editing", "P0",
  "Reviewer edits a question; the edit creates a new version that is re-validated.",
  "Fix small issues without regenerating.",
  "Question versions.",
  "Re-validation of edited version.",
  API + "PATCH /api/v1/questions/{id} (creates version)",
  "Inline editor in Quiz review.",
  "Edit breaks evidence match -> re-validation flags it.",
  "Edits never modify an approved version in place; AI-generated vs human-edited fields are distinguishable.",
  "Suggested edits.")

F("ASM-031", "Question versioning", "P0",
  "Immutable versions of questions referenced by attempts and approvals.",
  "Auditability and correct re-scoring.",
  "Question version chain.",
  "None.",
  API + "GET /api/v1/questions/{id}/versions",
  "Version history panel.",
  "Attempt references missing version -> integrity error.",
  "Attempts always reference the exact version delivered.",
  "Version diffs.")

F("ASM-032", "Assessment history", "P0",
  "Lists a learner's attempts with dates, scores and assessment versions.",
  "Transparency and progress tracking.",
  "AssessmentAttempt.",
  "None.",
  API + "GET /api/v1/me/attempts; GET /api/v1/users/{id}/attempts (scoped roles)",
  "History list on Competency profile.",
  "Deleted assessment -> history retained read-only.",
  "Learners see all their own attempts; scoped roles see only permitted users.",
  "Assessment timeline (PRO-013).",
  primary="Learner")
