"""Learning experience: course modules, lessons, prerequisites, progress, activity log, learning paths (Phase 4B).

From the approved lessons proposal (phase-c-learning-experience-proposal.md) with the Phase 4 amendments:
- ``course_modules`` / ``lessons``: course structure; lesson bodies are Markdown written for this platform.
- ``course_prerequisites``: advisory ordering for the learning path; nothing is locked.
- ``progress_records``: current state per learner and target, with ``resume_lesson_id`` for courses.
- ``learning_activities``: append-only (trigger reuses ``forbid_update_delete`` from 0003); identifiers and counts only.
- ``learning_paths`` / ``learning_path_items``: generated by rule ``path-v1``; one active path per learner.
- ``courses.content_origin`` (``synthetic``, ``official_source``, ``provider``) and ``courses.completion_criteria``.
  Backfill: NSSTA programme listings become ``official_source`` (they come from an official source document and stay
  hidden from learners until reviewed); every other existing course is ``synthetic``.

Rollback drops the new tables and the two course columns; no earlier data depends on them.
Autogenerated, then edited by hand: actor foreign keys (``use_alter``), the course CHECK, the backfill and the trigger.

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-15
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('course_modules',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_course_modules_status')),
    sa.CheckConstraint('position > 0', name=op.f('ck_course_modules_position_positive')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_modules_course_id_courses')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_course_modules_created_by_users'), use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_course_modules_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_course_modules_updated_by_users'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_modules')),
    sa.UniqueConstraint('course_id', 'position', name=op.f('uq_course_modules_course_id_position'))
    )
    op.create_index(op.f('ix_course_modules_course_id'), 'course_modules', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_modules_organization_id'), 'course_modules', ['organization_id'], unique=False)
    op.create_table('course_prerequisites',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('prerequisite_course_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('course_id <> prerequisite_course_id', name=op.f('ck_course_prerequisites_not_self')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_prerequisites_course_id_courses')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_course_prerequisites_created_by_users'), use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_course_prerequisites_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prerequisite_course_id'], ['courses.id'], name=op.f('fk_course_prerequisites_prerequisite_course_id_courses')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_course_prerequisites_updated_by_users'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_prerequisites')),
    sa.UniqueConstraint('course_id', 'prerequisite_course_id', name=op.f('uq_course_prerequisites_course_id_prerequisite_course_id'))
    )
    op.create_index(op.f('ix_course_prerequisites_course_id'), 'course_prerequisites', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_prerequisites_organization_id'), 'course_prerequisites', ['organization_id'], unique=False)
    op.create_table('learning_activities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("activity_type IN ('course_started', 'lesson_opened', 'lesson_completed', 'course_completed', 'path_generated')", name=op.f('ck_learning_activities_activity_type')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_learning_activities_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_activities_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_activities'))
    )
    op.create_index(op.f('ix_learning_activities_organization_id'), 'learning_activities', ['organization_id'], unique=False)
    op.create_index('ix_learning_activities_user_occurred', 'learning_activities', ['user_id', 'occurred_at'], unique=False)
    op.create_table('learning_paths',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_role_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('rule_version', sa.Text(), nullable=False),
    sa.Column('input_snapshot_hash', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("input_snapshot_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_learning_paths_input_hash_is_sha256')),
    sa.CheckConstraint("status IN ('active', 'superseded')", name=op.f('ck_learning_paths_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_learning_paths_created_by_users'), use_alter=True),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], name=op.f('fk_learning_paths_job_role_id_job_roles')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_learning_paths_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_learning_paths_updated_by_users'), use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_paths_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_paths'))
    )
    op.create_index(op.f('ix_learning_paths_organization_id'), 'learning_paths', ['organization_id'], unique=False)
    op.create_index(op.f('ix_learning_paths_user_id'), 'learning_paths', ['user_id'], unique=False)
    op.create_index('uq_learning_paths_user_active', 'learning_paths', ['user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('lessons',
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('lesson_type', sa.Text(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('content_kind', sa.Text(), server_default=sa.text("'inline_markdown'"), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=True),
    sa.Column('learning_material_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("content_kind <> 'inline_markdown' OR body_markdown IS NOT NULL", name=op.f('ck_lessons_inline_body_present')),
    sa.CheckConstraint("content_kind IN ('inline_markdown', 'learning_material')", name=op.f('ck_lessons_content_kind')),
    sa.CheckConstraint("lesson_type IN ('reading', 'worked_example', 'practice_check')", name=op.f('ck_lessons_lesson_type')),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_lessons_status')),
    sa.CheckConstraint('estimated_minutes BETWEEN 1 AND 240', name=op.f('ck_lessons_estimated_minutes_range')),
    sa.CheckConstraint('position > 0', name=op.f('ck_lessons_position_positive')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_lessons_course_id_courses')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_lessons_created_by_users'), use_alter=True),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], name=op.f('fk_lessons_module_id_course_modules')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_lessons_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_lessons_updated_by_users'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons')),
    sa.UniqueConstraint('module_id', 'position', name=op.f('uq_lessons_module_id_position'))
    )
    op.create_index(op.f('ix_lessons_course_id'), 'lessons', ['course_id'], unique=False)
    op.create_index(op.f('ix_lessons_module_id'), 'lessons', ['module_id'], unique=False)
    op.create_index(op.f('ix_lessons_organization_id'), 'lessons', ['organization_id'], unique=False)
    op.create_table('progress_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('title_snapshot', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('status_source', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resume_lesson_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("resume_lesson_id IS NULL OR target_type = 'course'", name=op.f('ck_progress_records_resume_only_for_courses')),
    sa.CheckConstraint("status <> 'completed' OR completed_at IS NOT NULL", name=op.f('ck_progress_records_completed_has_timestamp')),
    sa.CheckConstraint("status IN ('not_started', 'in_progress', 'completed')", name=op.f('ck_progress_records_status')),
    sa.CheckConstraint("status_source IN ('system', 'self_reported', 'administrator')", name=op.f('ck_progress_records_status_source')),
    sa.CheckConstraint("target_type IN ('course', 'lesson', 'learning_path_item')", name=op.f('ck_progress_records_target_type')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_progress_records_course_id_courses')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_progress_records_created_by_users'), use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_progress_records_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resume_lesson_id'], ['lessons.id'], name=op.f('fk_progress_records_resume_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_progress_records_updated_by_users'), use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_progress_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_records')),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name=op.f('uq_progress_records_user_id_target_type_target_id'))
    )
    op.create_index(op.f('ix_progress_records_organization_id'), 'progress_records', ['organization_id'], unique=False)
    op.create_index('ix_progress_records_user_course', 'progress_records', ['user_id', 'course_id'], unique=False)
    op.create_index('ix_progress_records_user_status', 'progress_records', ['user_id', 'status'], unique=False)
    op.create_table('learning_path_items',
    sa.Column('learning_path_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('gap_competency_id', sa.UUID(), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'not_started'"), nullable=False),
    sa.Column('status_source', sa.Text(), server_default=sa.text("'system'"), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("item_type <> 'course' OR target_id IS NOT NULL", name=op.f('ck_learning_path_items_course_item_has_target')),
    sa.CheckConstraint("item_type IN ('course', 'no_content_placeholder')", name=op.f('ck_learning_path_items_item_type')),
    sa.CheckConstraint("status IN ('not_started', 'in_progress', 'completed')", name=op.f('ck_learning_path_items_status')),
    sa.CheckConstraint("status_source IN ('system', 'self_reported', 'administrator')", name=op.f('ck_learning_path_items_status_source')),
    sa.CheckConstraint('position > 0', name=op.f('ck_learning_path_items_position_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_learning_path_items_created_by_users'), use_alter=True),
    sa.ForeignKeyConstraint(['gap_competency_id'], ['competencies.id'], name=op.f('fk_learning_path_items_gap_competency_id_competencies')),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], name=op.f('fk_learning_path_items_learning_path_id_learning_paths')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_learning_path_items_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_learning_path_items_updated_by_users'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_path_items')),
    sa.UniqueConstraint('learning_path_id', 'position', name=op.f('uq_learning_path_items_learning_path_id_position'))
    )
    op.create_index(op.f('ix_learning_path_items_learning_path_id'), 'learning_path_items', ['learning_path_id'], unique=False)
    op.create_index(op.f('ix_learning_path_items_organization_id'), 'learning_path_items', ['organization_id'], unique=False)
    op.add_column('courses', sa.Column('content_origin', sa.Text(), server_default=sa.text("'synthetic'"), nullable=False))
    op.add_column('courses', sa.Column('completion_criteria', sa.Text(), nullable=True))
    op.create_foreign_key(op.f('fk_course_modules_created_by_users'), 'course_modules', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_course_modules_updated_by_users'), 'course_modules', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_course_prerequisites_created_by_users'), 'course_prerequisites', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_course_prerequisites_updated_by_users'), 'course_prerequisites', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_learning_paths_created_by_users'), 'learning_paths', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_learning_paths_updated_by_users'), 'learning_paths', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_lessons_created_by_users'), 'lessons', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_lessons_updated_by_users'), 'lessons', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_progress_records_created_by_users'), 'progress_records', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_progress_records_updated_by_users'), 'progress_records', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_learning_path_items_created_by_users'), 'learning_path_items', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_learning_path_items_updated_by_users'), 'learning_path_items', 'users', ['updated_by'], ['id'])
    op.create_check_constraint(op.f('ck_courses_content_origin'), 'courses',
                               "content_origin IN ('synthetic', 'official_source', 'provider')")
    op.execute("UPDATE courses SET content_origin = 'official_source' WHERE course_type = 'nssta_programme_listing'")
    op.execute("""
CREATE TRIGGER trg_learning_activities_append_only BEFORE UPDATE OR DELETE ON learning_activities
  FOR EACH ROW EXECUTE FUNCTION forbid_update_delete();
""")


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_learning_activities_append_only ON learning_activities")
    op.drop_constraint(op.f('ck_courses_content_origin'), 'courses', type_='check')
    op.drop_column('courses', 'completion_criteria')
    op.drop_column('courses', 'content_origin')
    op.drop_index(op.f('ix_learning_path_items_organization_id'), table_name='learning_path_items')
    op.drop_index(op.f('ix_learning_path_items_learning_path_id'), table_name='learning_path_items')
    op.drop_table('learning_path_items')
    op.drop_index('ix_progress_records_user_status', table_name='progress_records')
    op.drop_index('ix_progress_records_user_course', table_name='progress_records')
    op.drop_index(op.f('ix_progress_records_organization_id'), table_name='progress_records')
    op.drop_table('progress_records')
    op.drop_index(op.f('ix_lessons_organization_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_module_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_course_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index('uq_learning_paths_user_active', table_name='learning_paths', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_learning_paths_user_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_organization_id'), table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index('ix_learning_activities_user_occurred', table_name='learning_activities')
    op.drop_index(op.f('ix_learning_activities_organization_id'), table_name='learning_activities')
    op.drop_table('learning_activities')
    op.drop_index(op.f('ix_course_prerequisites_organization_id'), table_name='course_prerequisites')
    op.drop_index(op.f('ix_course_prerequisites_course_id'), table_name='course_prerequisites')
    op.drop_table('course_prerequisites')
    op.drop_index(op.f('ix_course_modules_organization_id'), table_name='course_modules')
    op.drop_index(op.f('ix_course_modules_course_id'), table_name='course_modules')
    op.drop_table('course_modules')
