"""Demo reset (attempt voiding) and versioned seed pack registry (DEC-052).

Autogenerated from the models, then completed by hand (autogenerate does not compare CHECK
constraints or partial-index predicates):
- ``assessment_attempts.status`` gains ``voided``, with ``voided_at``/``void_reason`` required together;
- the one-baseline-per-user index ignores voided attempts, so a reset learner can take a new baseline;
- ``seed_pack_applications`` records which versioned seed pack each organisation has received.

Nothing is deleted by a reset: attempts are voided, evidence rows use their existing void columns.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-15
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('seed_pack_applications',
    sa.Column('pack_code', sa.Text(), nullable=False),
    sa.Column('pack_version', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("pack_code ~ '^[a-z0-9][a-z0-9-]*$'", name=op.f('ck_seed_pack_applications_pack_code_format')),
    sa.CheckConstraint('pack_version >= 1', name=op.f('ck_seed_pack_applications_pack_version_positive')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_seed_pack_applications_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seed_pack_applications')),
    sa.UniqueConstraint('organization_id', 'pack_code', name=op.f('uq_seed_pack_applications_organization_id_pack_code'))
    )
    op.create_index(op.f('ix_seed_pack_applications_organization_id'), 'seed_pack_applications', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_seed_pack_applications_created_by_users'), 'seed_pack_applications', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_seed_pack_applications_updated_by_users'), 'seed_pack_applications', 'users', ['updated_by'], ['id'])
    op.add_column('assessment_attempts', sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assessment_attempts', sa.Column('void_reason', sa.Text(), nullable=True))

    op.drop_constraint(op.f('ck_assessment_attempts_status'), 'assessment_attempts', type_='check')
    op.create_check_constraint(op.f('ck_assessment_attempts_status'), 'assessment_attempts',
        "status IN ('in_progress', 'submitted', 'scored', 'scoring_failed', 'expired', 'voided')",
    )
    op.create_check_constraint(op.f('ck_assessment_attempts_voided_complete'), 'assessment_attempts',
        "(status = 'voided') = (voided_at IS NOT NULL AND void_reason IS NOT NULL)",
    )
    op.drop_index('uq_assessment_attempts_one_baseline', table_name='assessment_attempts', postgresql_where=sa.text('is_baseline'))
    op.create_index('uq_assessment_attempts_one_baseline', 'assessment_attempts', ['user_id'], unique=True,
                    postgresql_where=sa.text("is_baseline AND status <> 'voided'"))


def downgrade() -> None:
    # Voided attempts cannot be represented before 0004. They become 'expired' and lose the baseline flag,
    # so the stricter constraints can be restored. Local/ci demo data only (resets are refused elsewhere).
    op.drop_index('uq_assessment_attempts_one_baseline', table_name='assessment_attempts',
                  postgresql_where=sa.text("is_baseline AND status <> 'voided'"))
    op.drop_constraint(op.f('ck_assessment_attempts_voided_complete'), 'assessment_attempts', type_='check')
    op.drop_constraint(op.f('ck_assessment_attempts_status'), 'assessment_attempts', type_='check')
    op.execute("UPDATE assessment_attempts SET status = 'expired', is_baseline = false WHERE status = 'voided'")
    op.create_check_constraint(op.f('ck_assessment_attempts_status'), 'assessment_attempts',
        "status IN ('in_progress', 'submitted', 'scored', 'scoring_failed', 'expired')",
    )
    op.create_index('uq_assessment_attempts_one_baseline', 'assessment_attempts', ['user_id'], unique=True,
                    postgresql_where=sa.text('is_baseline'))
    op.drop_column('assessment_attempts', 'void_reason')
    op.drop_column('assessment_attempts', 'voided_at')
    op.drop_index(op.f('ix_seed_pack_applications_organization_id'), table_name='seed_pack_applications')
    op.drop_table('seed_pack_applications')
