"""Reference schema: organisation, identity, competency, catalogue and audit tables.

Autogenerated from the models, then reviewed by hand (DATA_MODEL.md §14):
- actor foreign keys (created_by/updated_by -> users) are created after all tables;
- integrity triggers enforce rules that CHECK constraints cannot express.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-14
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('organizations',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('settings_row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("code ~ '^[a-z0-9][a-z0-9-]{1,62}$'", name=op.f('ck_organizations_code_slug')),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_organizations_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('code', name=op.f('uq_organizations_code'))
    )
    op.create_index('uq_organizations_lower_name', 'organizations', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('departments',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_departments_status')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_departments_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index(op.f('ix_departments_organization_id'), 'departments', ['organization_id'], unique=False)
    op.create_index('uq_departments_org_lower_name', 'departments', ['organization_id', sa.literal_column('lower(name)')], unique=True)
    op.create_table('source_records',
    sa.Column('registry_source_id', sa.Text(), nullable=False),
    sa.Column('source_document_id', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_organisation', sa.Text(), nullable=False),
    sa.Column('retrieval_date', sa.Date(), nullable=True),
    sa.Column('access_method', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=True),
    sa.Column('raw_local_path', sa.Text(), nullable=True),
    sa.Column('canonical_dataset', sa.Text(), nullable=True),
    sa.Column('canonical_record_id', sa.Text(), nullable=True),
    sa.Column('canonical_dataset_sha256', sa.Text(), nullable=True),
    sa.Column('data_status', sa.Text(), nullable=False),
    sa.Column('licence_status', sa.Text(), nullable=False),
    sa.Column('licence_notes', sa.Text(), nullable=False),
    sa.Column('attribution_text', sa.Text(), nullable=False),
    sa.Column('review_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("canonical_dataset_sha256 IS NULL OR canonical_dataset_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_source_records_canonical_dataset_sha256_format')),
    sa.CheckConstraint("data_status <> 'MOCK' AND licence_status <> 'MOCK'", name=op.f('ck_source_records_not_mock')),
    sa.CheckConstraint("data_status IN ('VERIFIED', 'UNKNOWN', 'UNAVAILABLE', 'MOCK', 'ASSUMED', 'MACHINE_OBSERVED', 'UNVERIFIED_SECONDHAND', 'EXCLUDED_BY_POLICY', 'NOT_APPLICABLE')", name=op.f('ck_source_records_data_status')),
    sa.CheckConstraint("licence_status IN ('VERIFIED', 'UNKNOWN', 'UNAVAILABLE', 'MOCK', 'ASSUMED', 'MACHINE_OBSERVED', 'UNVERIFIED_SECONDHAND', 'EXCLUDED_BY_POLICY', 'NOT_APPLICABLE')", name=op.f('ck_source_records_licence_status')),
    sa.CheckConstraint("source_sha256 IS NULL OR source_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_source_records_source_sha256_format')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_source_records_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_records')),
    sa.UniqueConstraint('organization_id', 'canonical_dataset', 'canonical_record_id', name=op.f('uq_source_records_organization_id_canonical_dataset_canonical_record_id'))
    )
    op.create_index(op.f('ix_source_records_organization_id'), 'source_records', ['organization_id'], unique=False)
    op.create_table('topics',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('taxonomy_version', sa.Text(), nullable=False),
    sa.Column('data_status', sa.Text(), nullable=False),
    sa.Column('review_status', sa.Text(), server_default=sa.text("'unreviewed'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("data_status <> 'MOCK'", name=op.f('ck_topics_not_mock')),
    sa.CheckConstraint("data_status IN ('VERIFIED', 'UNKNOWN', 'UNAVAILABLE', 'MOCK', 'ASSUMED', 'MACHINE_OBSERVED', 'UNVERIFIED_SECONDHAND', 'EXCLUDED_BY_POLICY', 'NOT_APPLICABLE')", name=op.f('ck_topics_data_status')),
    sa.CheckConstraint("review_status IN ('unreviewed', 'approved', 'retired')", name=op.f('ck_topics_review_status')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_topics_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('organization_id', 'code', name=op.f('uq_topics_organization_id_code'))
    )
    op.create_index(op.f('ix_topics_organization_id'), 'topics', ['organization_id'], unique=False)
    op.create_table('courses',
    sa.Column('course_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider_organisation', sa.Text(), nullable=False),
    sa.Column('programme_family', sa.Text(), nullable=True),
    sa.Column('cohort', sa.Text(), nullable=True),
    sa.Column('target_group', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('batch_size_min', sa.Integer(), nullable=True),
    sa.Column('batch_size_max', sa.Integer(), nullable=True),
    sa.Column('venue', sa.Text(), nullable=True),
    sa.Column('fiscal_year', sa.Text(), nullable=True),
    sa.Column('schedule_status', sa.Text(), nullable=True),
    sa.Column('external_ref', sa.Text(), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('source_record_id', sa.UUID(), nullable=True),
    sa.Column('data_status', sa.Text(), nullable=False),
    sa.Column('review_status', sa.Text(), server_default=sa.text("'unreviewed'"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("course_type <> 'nssta_programme_listing' OR source_record_id IS NOT NULL", name=op.f('ck_courses_listing_has_provenance')),
    sa.CheckConstraint("course_type IN ('internal', 'nssta_programme_listing')", name=op.f('ck_courses_course_type')),
    sa.CheckConstraint("data_status <> 'MOCK'", name=op.f('ck_courses_not_mock')),
    sa.CheckConstraint("data_status IN ('VERIFIED', 'UNKNOWN', 'UNAVAILABLE', 'MOCK', 'ASSUMED', 'MACHINE_OBSERVED', 'UNVERIFIED_SECONDHAND', 'EXCLUDED_BY_POLICY', 'NOT_APPLICABLE')", name=op.f('ck_courses_data_status')),
    sa.CheckConstraint("review_status IN ('unreviewed', 'approved', 'rejected')", name=op.f('ck_courses_review_status')),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_courses_status')),
    sa.CheckConstraint('batch_size_min IS NULL OR batch_size_max IS NULL OR batch_size_min <= batch_size_max', name=op.f('ck_courses_batch_size_order')),
    sa.CheckConstraint('duration_days IS NULL OR duration_days > 0', name=op.f('ck_courses_duration_positive')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_courses_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_courses_source_record_id_source_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('organization_id', 'source_record_id', name=op.f('uq_courses_organization_id_source_record_id'))
    )
    op.create_index('ix_courses_org_type_status', 'courses', ['organization_id', 'course_type', 'status'], unique=False)
    op.create_index(op.f('ix_courses_organization_id'), 'courses', ['organization_id'], unique=False)
    op.create_table('job_roles',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_job_roles_status')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_job_roles_department_id_departments')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_job_roles_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_roles'))
    )
    op.create_index(op.f('ix_job_roles_organization_id'), 'job_roles', ['organization_id'], unique=False)
    op.create_index('uq_job_roles_org_lower_name', 'job_roles', ['organization_id', sa.literal_column('lower(name)')], unique=True)
    op.create_table('course_topics',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'suggested'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("method IN ('keyword_rule', 'human')", name=op.f('ck_course_topics_method')),
    sa.CheckConstraint("status IN ('suggested', 'approved', 'rejected')", name=op.f('ck_course_topics_status')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_topics_course_id_courses')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_course_topics_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_course_topics_topic_id_topics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_topics')),
    sa.UniqueConstraint('course_id', 'topic_id', name=op.f('uq_course_topics_course_id_topic_id'))
    )
    op.create_index(op.f('ix_course_topics_organization_id'), 'course_topics', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('designation', sa.Text(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('job_role_id', sa.UUID(), nullable=True),
    sa.Column('locale', sa.Text(), server_default=sa.text("'en'"), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'invited'"), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("locale IN ('en', 'hi')", name=op.f('ck_users_locale')),
    sa.CheckConstraint("status IN ('invited', 'active', 'locked', 'inactive')", name=op.f('ck_users_status')),
    sa.CheckConstraint('failed_login_count >= 0', name=op.f('ck_users_failed_login_count_non_negative')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments')),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], name=op.f('fk_users_job_role_id_job_roles')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('ix_users_org_department', 'users', ['organization_id', 'department_id'], unique=False)
    op.create_index('ix_users_org_job_role', 'users', ['organization_id', 'job_role_id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index('uq_users_org_email', 'users', ['organization_id', 'email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_roles', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("action ~ '^[a-z_]+(\\.[a-z_]+)+$'", name=op.f('ck_audit_logs_action_format')),
    sa.CheckConstraint("outcome IN ('success', 'denied', 'failure')", name=op.f('ck_audit_logs_outcome')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor_occurred', 'audit_logs', ['actor_user_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_logs_correlation', 'audit_logs', ['correlation_id'], unique=False)
    op.create_index('ix_audit_logs_org_occurred', 'audit_logs', ['organization_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index('ix_audit_logs_target', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('competency_frameworks',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('framework_type', sa.Text(), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('version_label', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('definitions_restricted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source_record_id', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("framework_type IN ('reference_behavioural', 'functional')", name=op.f('ck_competency_frameworks_framework_type')),
    sa.CheckConstraint("status <> 'approved' OR (approved_by IS NOT NULL AND approved_at IS NOT NULL)", name=op.f('ck_competency_frameworks_approval_recorded')),
    sa.CheckConstraint("status IN ('draft', 'approved', 'retired')", name=op.f('ck_competency_frameworks_status')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_competency_frameworks_approved_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_competency_frameworks_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_competency_frameworks_source_record_id_source_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competency_frameworks')),
    sa.UniqueConstraint('organization_id', 'code', 'version_label', name=op.f('uq_competency_frameworks_organization_id_code_version_label'))
    )
    op.create_index(op.f('ix_competency_frameworks_organization_id'), 'competency_frameworks', ['organization_id'], unique=False)
    op.create_table('user_access_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('department_scope_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("role <> 'department_admin' OR department_scope_id IS NOT NULL", name=op.f('ck_user_access_roles_department_admin_requires_scope')),
    sa.CheckConstraint("role IN ('learner', 'trainer', 'department_admin', 'org_admin', 'competency_admin', 'training_manager', 'auditor', 'platform_admin')", name=op.f('ck_user_access_roles_role')),
    sa.ForeignKeyConstraint(['department_scope_id'], ['departments.id'], name=op.f('fk_user_access_roles_department_scope_id_departments')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_user_access_roles_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_access_roles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_access_roles'))
    )
    op.create_index(op.f('ix_user_access_roles_organization_id'), 'user_access_roles', ['organization_id'], unique=False)
    op.create_index('uq_user_access_roles_user_role_scope', 'user_access_roles', ['user_id', 'role', sa.literal_column("coalesce(department_scope_id, '00000000-0000-0000-0000-000000000000'::uuid)")], unique=True)
    op.create_table('competency_clusters',
    sa.Column('framework_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('source_page IS NULL OR source_page >= 1', name=op.f('ck_competency_clusters_source_page_positive')),
    sa.ForeignKeyConstraint(['framework_id'], ['competency_frameworks.id'], name=op.f('fk_competency_clusters_framework_id_competency_frameworks')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_competency_clusters_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competency_clusters')),
    sa.UniqueConstraint('framework_id', 'code', name=op.f('uq_competency_clusters_framework_id_code'))
    )
    op.create_index(op.f('ix_competency_clusters_organization_id'), 'competency_clusters', ['organization_id'], unique=False)
    op.create_table('competency_levels',
    sa.Column('framework_id', sa.UUID(), nullable=False),
    sa.Column('level_number', sa.SmallInteger(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('threshold_status', sa.Text(), server_default=sa.text("'provisional'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("threshold_status IN ('provisional', 'approved')", name=op.f('ck_competency_levels_threshold_status')),
    sa.CheckConstraint('level_number >= 1', name=op.f('ck_competency_levels_level_number_positive')),
    sa.CheckConstraint('min_score IS NULL OR (min_score >= 0 AND min_score <= 1)', name=op.f('ck_competency_levels_min_score_range')),
    sa.ForeignKeyConstraint(['framework_id'], ['competency_frameworks.id'], name=op.f('fk_competency_levels_framework_id_competency_frameworks')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_competency_levels_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competency_levels')),
    sa.UniqueConstraint('framework_id', 'level_number', name=op.f('uq_competency_levels_framework_id_level_number'))
    )
    op.create_index(op.f('ix_competency_levels_organization_id'), 'competency_levels', ['organization_id'], unique=False)
    op.create_table('competencies',
    sa.Column('framework_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_variants', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition_source_page', sa.Integer(), nullable=True),
    sa.Column('detail_source_page', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('data_status', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("data_status <> 'MOCK'", name=op.f('ck_competencies_not_mock')),
    sa.CheckConstraint("data_status IN ('VERIFIED', 'UNKNOWN', 'UNAVAILABLE', 'MOCK', 'ASSUMED', 'MACHINE_OBSERVED', 'UNVERIFIED_SECONDHAND', 'EXCLUDED_BY_POLICY', 'NOT_APPLICABLE')", name=op.f('ck_competencies_data_status')),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_competencies_status')),
    sa.ForeignKeyConstraint(['cluster_id'], ['competency_clusters.id'], name=op.f('fk_competencies_cluster_id_competency_clusters')),
    sa.ForeignKeyConstraint(['framework_id'], ['competency_frameworks.id'], name=op.f('fk_competencies_framework_id_competency_frameworks')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_competencies_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competencies')),
    sa.UniqueConstraint('framework_id', 'code', name=op.f('uq_competencies_framework_id_code'))
    )
    op.create_index(op.f('ix_competencies_organization_id'), 'competencies', ['organization_id'], unique=False)
    op.create_table('course_competencies',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('relevance', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'suggested'"), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("method IN ('human', 'keyword_rule')", name=op.f('ck_course_competencies_method')),
    sa.CheckConstraint("relevance IN ('primary', 'secondary')", name=op.f('ck_course_competencies_relevance')),
    sa.CheckConstraint("status <> 'approved' OR (approved_by IS NOT NULL AND approved_at IS NOT NULL)", name=op.f('ck_course_competencies_approval_recorded')),
    sa.CheckConstraint("status IN ('suggested', 'approved', 'rejected')", name=op.f('ck_course_competencies_status')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_course_competencies_approved_by_users')),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], name=op.f('fk_course_competencies_competency_id_competencies')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_competencies_course_id_courses')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_course_competencies_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_competencies')),
    sa.UniqueConstraint('course_id', 'competency_id', name=op.f('uq_course_competencies_course_id_competency_id'))
    )
    op.create_index(op.f('ix_course_competencies_organization_id'), 'course_competencies', ['organization_id'], unique=False)
    op.create_table('role_competencies',
    sa.Column('job_role_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('required_level_number', sa.SmallInteger(), nullable=False),
    sa.Column('mapping_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("status <> 'approved' OR (approved_by IS NOT NULL AND approved_at IS NOT NULL)", name=op.f('ck_role_competencies_approval_recorded')),
    sa.CheckConstraint("status IN ('draft', 'approved', 'retired')", name=op.f('ck_role_competencies_status')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_role_competencies_approved_by_users')),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], name=op.f('fk_role_competencies_competency_id_competencies')),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], name=op.f('fk_role_competencies_job_role_id_job_roles')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_role_competencies_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_competencies')),
    sa.UniqueConstraint('job_role_id', 'competency_id', 'mapping_version', name=op.f('uq_role_competencies_job_role_id_competency_id_mapping_version'))
    )
    op.create_index(op.f('ix_role_competencies_organization_id'), 'role_competencies', ['organization_id'], unique=False)
    op.create_index('uq_role_competencies_one_approved', 'role_competencies', ['job_role_id', 'competency_id'], unique=True, postgresql_where=sa.text("status = 'approved'"))
    # Actor foreign keys are added after every table exists (users <-> organizations cycle).
    op.create_foreign_key(op.f('fk_organizations_created_by_users'), 'organizations', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_organizations_updated_by_users'), 'organizations', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_departments_created_by_users'), 'departments', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_departments_updated_by_users'), 'departments', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_source_records_created_by_users'), 'source_records', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_source_records_updated_by_users'), 'source_records', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_topics_created_by_users'), 'topics', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_topics_updated_by_users'), 'topics', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_courses_created_by_users'), 'courses', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_courses_updated_by_users'), 'courses', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_job_roles_created_by_users'), 'job_roles', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_job_roles_updated_by_users'), 'job_roles', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_course_topics_created_by_users'), 'course_topics', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_course_topics_updated_by_users'), 'course_topics', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_users_created_by_users'), 'users', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_users_updated_by_users'), 'users', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_competency_frameworks_created_by_users'), 'competency_frameworks', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_competency_frameworks_updated_by_users'), 'competency_frameworks', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_user_access_roles_created_by_users'), 'user_access_roles', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_user_access_roles_updated_by_users'), 'user_access_roles', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_competency_clusters_created_by_users'), 'competency_clusters', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_competency_clusters_updated_by_users'), 'competency_clusters', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_competency_levels_created_by_users'), 'competency_levels', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_competency_levels_updated_by_users'), 'competency_levels', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_competencies_created_by_users'), 'competencies', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_competencies_updated_by_users'), 'competencies', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_course_competencies_created_by_users'), 'course_competencies', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_course_competencies_updated_by_users'), 'course_competencies', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_role_competencies_created_by_users'), 'role_competencies', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_role_competencies_updated_by_users'), 'role_competencies', 'users', ['updated_by'], ['id'])

    _create_integrity_triggers()


def downgrade() -> None:
    _drop_integrity_triggers()
    op.drop_constraint(op.f('fk_organizations_created_by_users'), 'organizations', type_='foreignkey')
    op.drop_constraint(op.f('fk_organizations_updated_by_users'), 'organizations', type_='foreignkey')
    op.drop_constraint(op.f('fk_departments_created_by_users'), 'departments', type_='foreignkey')
    op.drop_constraint(op.f('fk_departments_updated_by_users'), 'departments', type_='foreignkey')
    op.drop_constraint(op.f('fk_source_records_created_by_users'), 'source_records', type_='foreignkey')
    op.drop_constraint(op.f('fk_source_records_updated_by_users'), 'source_records', type_='foreignkey')
    op.drop_constraint(op.f('fk_topics_created_by_users'), 'topics', type_='foreignkey')
    op.drop_constraint(op.f('fk_topics_updated_by_users'), 'topics', type_='foreignkey')
    op.drop_constraint(op.f('fk_courses_created_by_users'), 'courses', type_='foreignkey')
    op.drop_constraint(op.f('fk_courses_updated_by_users'), 'courses', type_='foreignkey')
    op.drop_constraint(op.f('fk_job_roles_created_by_users'), 'job_roles', type_='foreignkey')
    op.drop_constraint(op.f('fk_job_roles_updated_by_users'), 'job_roles', type_='foreignkey')
    op.drop_constraint(op.f('fk_course_topics_created_by_users'), 'course_topics', type_='foreignkey')
    op.drop_constraint(op.f('fk_course_topics_updated_by_users'), 'course_topics', type_='foreignkey')
    op.drop_constraint(op.f('fk_users_created_by_users'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('fk_users_updated_by_users'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('fk_competency_frameworks_created_by_users'), 'competency_frameworks', type_='foreignkey')
    op.drop_constraint(op.f('fk_competency_frameworks_updated_by_users'), 'competency_frameworks', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_access_roles_created_by_users'), 'user_access_roles', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_access_roles_updated_by_users'), 'user_access_roles', type_='foreignkey')
    op.drop_constraint(op.f('fk_competency_clusters_created_by_users'), 'competency_clusters', type_='foreignkey')
    op.drop_constraint(op.f('fk_competency_clusters_updated_by_users'), 'competency_clusters', type_='foreignkey')
    op.drop_constraint(op.f('fk_competency_levels_created_by_users'), 'competency_levels', type_='foreignkey')
    op.drop_constraint(op.f('fk_competency_levels_updated_by_users'), 'competency_levels', type_='foreignkey')
    op.drop_constraint(op.f('fk_competencies_created_by_users'), 'competencies', type_='foreignkey')
    op.drop_constraint(op.f('fk_competencies_updated_by_users'), 'competencies', type_='foreignkey')
    op.drop_constraint(op.f('fk_course_competencies_created_by_users'), 'course_competencies', type_='foreignkey')
    op.drop_constraint(op.f('fk_course_competencies_updated_by_users'), 'course_competencies', type_='foreignkey')
    op.drop_constraint(op.f('fk_role_competencies_created_by_users'), 'role_competencies', type_='foreignkey')
    op.drop_constraint(op.f('fk_role_competencies_updated_by_users'), 'role_competencies', type_='foreignkey')
    op.drop_index('uq_role_competencies_one_approved', table_name='role_competencies', postgresql_where=sa.text("status = 'approved'"))
    op.drop_index(op.f('ix_role_competencies_organization_id'), table_name='role_competencies')
    op.drop_table('role_competencies')
    op.drop_index(op.f('ix_course_competencies_organization_id'), table_name='course_competencies')
    op.drop_table('course_competencies')
    op.drop_index(op.f('ix_competencies_organization_id'), table_name='competencies')
    op.drop_table('competencies')
    op.drop_index(op.f('ix_competency_levels_organization_id'), table_name='competency_levels')
    op.drop_table('competency_levels')
    op.drop_index(op.f('ix_competency_clusters_organization_id'), table_name='competency_clusters')
    op.drop_table('competency_clusters')
    op.drop_index('uq_user_access_roles_user_role_scope', table_name='user_access_roles')
    op.drop_index(op.f('ix_user_access_roles_organization_id'), table_name='user_access_roles')
    op.drop_table('user_access_roles')
    op.drop_index(op.f('ix_competency_frameworks_organization_id'), table_name='competency_frameworks')
    op.drop_table('competency_frameworks')
    op.drop_index('ix_audit_logs_target', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_occurred', table_name='audit_logs')
    op.drop_index('ix_audit_logs_correlation', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_occurred', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_users_org_email', table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index('ix_users_org_job_role', table_name='users')
    op.drop_index('ix_users_org_department', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_course_topics_organization_id'), table_name='course_topics')
    op.drop_table('course_topics')
    op.drop_index('uq_job_roles_org_lower_name', table_name='job_roles')
    op.drop_index(op.f('ix_job_roles_organization_id'), table_name='job_roles')
    op.drop_table('job_roles')
    op.drop_index(op.f('ix_courses_organization_id'), table_name='courses')
    op.drop_index('ix_courses_org_type_status', table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_topics_organization_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_source_records_organization_id'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index('uq_departments_org_lower_name', table_name='departments')
    op.drop_index(op.f('ix_departments_organization_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index('uq_organizations_lower_name', table_name='organizations')
    op.drop_table('organizations')


# --- Integrity triggers ------------------------------------------------------
# Errors use SQLSTATE 23514 (check_violation) so callers can treat them like CHECK failures.

_TRIGGERS_SQL = r"""
CREATE FUNCTION competencies_restricted_definition() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.description IS NOT NULL AND EXISTS (
    SELECT 1 FROM competency_frameworks f WHERE f.id = NEW.framework_id AND f.definitions_restricted
  ) THEN
    RAISE EXCEPTION 'restricted_definition: framework definitions are licence-restricted; description must be null'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER trg_competencies_restricted_definition
  BEFORE INSERT OR UPDATE OF description, framework_id ON competencies
  FOR EACH ROW EXECUTE FUNCTION competencies_restricted_definition();

CREATE FUNCTION competency_frameworks_restriction_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.definitions_restricted AND NOT OLD.definitions_restricted AND EXISTS (
    SELECT 1 FROM competencies c WHERE c.framework_id = NEW.id AND c.description IS NOT NULL
  ) THEN
    RAISE EXCEPTION 'restricted_definition: remove competency descriptions before restricting the framework'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER trg_competency_frameworks_restriction_change
  BEFORE UPDATE OF definitions_restricted ON competency_frameworks
  FOR EACH ROW EXECUTE FUNCTION competency_frameworks_restriction_change();

CREATE FUNCTION competency_levels_min_score_order() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM competency_levels lo JOIN competency_levels hi
      ON hi.framework_id = lo.framework_id AND hi.level_number > lo.level_number
    WHERE lo.framework_id = NEW.framework_id
      AND lo.min_score IS NOT NULL AND hi.min_score IS NOT NULL AND lo.min_score >= hi.min_score
  ) THEN
    RAISE EXCEPTION 'min_score_order: min_score must increase with level_number' USING ERRCODE = '23514';
  END IF;
  RETURN NULL;
END $$;

-- Deferred so a whole level scale can be written in one transaction in any order.
CREATE CONSTRAINT TRIGGER trg_competency_levels_min_score_order
  AFTER INSERT OR UPDATE ON competency_levels DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION competency_levels_min_score_order();

CREATE FUNCTION role_competencies_required_level() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM competencies c JOIN competency_levels l ON l.framework_id = c.framework_id
    WHERE c.id = NEW.competency_id AND l.level_number = NEW.required_level_number
  ) THEN
    RAISE EXCEPTION 'required_level_not_in_scale: level % is not in the competency framework scale',
      NEW.required_level_number USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER trg_role_competencies_required_level
  BEFORE INSERT OR UPDATE OF required_level_number, competency_id ON role_competencies
  FOR EACH ROW EXECUTE FUNCTION role_competencies_required_level();

CREATE FUNCTION audit_logs_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'append_only: audit_logs rows cannot be modified or deleted' USING ERRCODE = '23514';
END $$;

CREATE TRIGGER trg_audit_logs_no_update_delete
  BEFORE UPDATE OR DELETE ON audit_logs
  FOR EACH ROW EXECUTE FUNCTION audit_logs_append_only();

CREATE TRIGGER trg_audit_logs_no_truncate
  BEFORE TRUNCATE ON audit_logs
  FOR EACH STATEMENT EXECUTE FUNCTION audit_logs_append_only();
"""

_TRIGGER_FUNCTIONS = (
    "audit_logs_append_only",
    "role_competencies_required_level",
    "competency_levels_min_score_order",
    "competency_frameworks_restriction_change",
    "competencies_restricted_definition",
)


def _create_integrity_triggers() -> None:
    op.execute(_TRIGGERS_SQL)


def _drop_integrity_triggers() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_no_truncate ON audit_logs")
    op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_no_update_delete ON audit_logs")
    op.execute("DROP TRIGGER IF EXISTS trg_role_competencies_required_level ON role_competencies")
    op.execute("DROP TRIGGER IF EXISTS trg_competency_levels_min_score_order ON competency_levels")
    op.execute("DROP TRIGGER IF EXISTS trg_competency_frameworks_restriction_change ON competency_frameworks")
    op.execute("DROP TRIGGER IF EXISTS trg_competencies_restricted_definition ON competencies")
    for name in _TRIGGER_FUNCTIONS:
        op.execute(f"DROP FUNCTION IF EXISTS {name}()")
