"""Content workflow: question drafts and source references, review tasks and approvals, course publishing (Phase 4C).

- ``questions.status`` gains ``draft`` (human author's unsubmitted work).
- ``question_source_references``: where a question version's content comes from (synthetic declaration, imported
  source record, or author-provided external reference). Append-only with its version (trigger).
- ``review_tasks``: one open task per target; ``approvals``: append-only human decisions (trigger).
- ``courses.published_at`` / ``courses.published_by``: set when an approved course goes live.

Rollback drops the new tables and columns and restores the previous status CHECK; any ``draft`` questions are moved
to ``rejected`` first so the old CHECK can be recreated (drafts are never learner-visible).
Autogenerated, then edited by hand: actor foreign keys, the status CHECK, and the append-only triggers.

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-15
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('review_tasks',
    sa.Column('task_type', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('target_version_id', sa.UUID(), nullable=True),
    sa.Column('title_snapshot', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eligible_capability', sa.Text(), nullable=False),
    sa.Column('required_decisions', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submission_note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("status <> 'decided' OR decided_at IS NOT NULL", name=op.f('ck_review_tasks_decided_has_time')),
    sa.CheckConstraint("status IN ('open', 'decided', 'cancelled')", name=op.f('ck_review_tasks_status')),
    sa.CheckConstraint("task_type IN ('question_version_review', 'course_review')", name=op.f('ck_review_tasks_task_type')),
    sa.CheckConstraint('required_decisions IN (1, 2)', name=op.f('ck_review_tasks_required_decisions')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_review_tasks_created_by_users'), use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_review_tasks_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_review_tasks_submitted_by_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_review_tasks_updated_by_users'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_tasks'))
    )
    op.create_index('ix_review_tasks_org_status_type', 'review_tasks', ['organization_id', 'status', 'task_type'], unique=False)
    op.create_index(op.f('ix_review_tasks_organization_id'), 'review_tasks', ['organization_id'], unique=False)
    op.create_index('uq_review_tasks_open_target', 'review_tasks', ['target_type', 'target_id'], unique=True, postgresql_where=sa.text("status = 'open'"))
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('review_task_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.SmallInteger(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=False),
    sa.Column('target_version_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("decision = 'approve' OR reason_text IS NOT NULL", name=op.f('ck_approvals_reason_required')),
    sa.CheckConstraint("decision IN ('approve', 'reject', 'request_changes')", name=op.f('ck_approvals_decision')),
    sa.CheckConstraint('sequence IN (1, 2)', name=op.f('ck_approvals_sequence')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_approvals_decided_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_approvals_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_task_id'], ['review_tasks.id'], name=op.f('fk_approvals_review_task_id_review_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals')),
    sa.UniqueConstraint('review_task_id', 'sequence', name=op.f('uq_approvals_review_task_id_sequence'))
    )
    op.create_index(op.f('ix_approvals_organization_id'), 'approvals', ['organization_id'], unique=False)
    op.create_table('question_source_references',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('question_version_id', sa.UUID(), nullable=False),
    sa.Column('source_kind', sa.Text(), nullable=False),
    sa.Column('source_record_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('locator', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("source_kind <> 'external_reference' OR (title IS NOT NULL AND publisher IS NOT NULL)", name=op.f('ck_question_source_references_external_has_title_publisher')),
    sa.CheckConstraint("source_kind <> 'source_record' OR source_record_id IS NOT NULL", name=op.f('ck_question_source_references_record_has_id')),
    sa.CheckConstraint("source_kind <> 'synthetic' OR note IS NOT NULL", name=op.f('ck_question_source_references_synthetic_has_note')),
    sa.CheckConstraint("source_kind IN ('synthetic', 'source_record', 'external_reference')", name=op.f('ck_question_source_references_source_kind')),
    sa.CheckConstraint("url IS NULL OR url ~ '^https?://'", name=op.f('ck_question_source_references_url_scheme')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_question_source_references_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_question_source_references_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], name=op.f('fk_question_source_references_question_version_id_question_versions')),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_question_source_references_source_record_id_source_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_source_references'))
    )
    op.create_index(op.f('ix_question_source_references_organization_id'), 'question_source_references', ['organization_id'], unique=False)
    op.create_index(op.f('ix_question_source_references_question_version_id'), 'question_source_references', ['question_version_id'], unique=False)
    op.add_column('courses', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('courses', sa.Column('published_by', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_courses_published_by_users'), 'courses', 'users', ['published_by'], ['id'])
    op.create_foreign_key(op.f('fk_review_tasks_created_by_users'), 'review_tasks', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_review_tasks_updated_by_users'), 'review_tasks', 'users', ['updated_by'], ['id'])
    op.drop_constraint(op.f('ck_questions_status'), 'questions', type_='check')
    op.create_check_constraint(op.f('ck_questions_status'), 'questions', "status IN ('draft', 'pending_validation', 'failed_validation', 'validation_incomplete', 'in_review', 'approved', 'rejected', 'suspended', 'retired')")
    op.execute("""
CREATE TRIGGER trg_approvals_append_only BEFORE UPDATE OR DELETE ON approvals
  FOR EACH ROW EXECUTE FUNCTION forbid_update_delete();
CREATE TRIGGER trg_question_source_references_append_only BEFORE UPDATE OR DELETE ON question_source_references
  FOR EACH ROW EXECUTE FUNCTION forbid_update_delete();
""")


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_question_source_references_append_only ON question_source_references")
    op.execute("DROP TRIGGER IF EXISTS trg_approvals_append_only ON approvals")
    op.execute("UPDATE questions SET status = 'rejected' WHERE status = 'draft'")
    op.drop_constraint(op.f('ck_questions_status'), 'questions', type_='check')
    op.create_check_constraint(op.f('ck_questions_status'), 'questions', "status IN ('pending_validation', 'failed_validation', 'validation_incomplete', 'in_review', 'approved', 'rejected', 'suspended', 'retired')")
    op.drop_constraint(op.f('fk_courses_published_by_users'), 'courses', type_='foreignkey')
    op.drop_column('courses', 'published_by')
    op.drop_column('courses', 'published_at')
    op.drop_index(op.f('ix_question_source_references_question_version_id'), table_name='question_source_references')
    op.drop_index(op.f('ix_question_source_references_organization_id'), table_name='question_source_references')
    op.drop_table('question_source_references')
    op.drop_index(op.f('ix_approvals_organization_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('uq_review_tasks_open_target', table_name='review_tasks', postgresql_where=sa.text("status = 'open'"))
    op.drop_index(op.f('ix_review_tasks_organization_id'), table_name='review_tasks')
    op.drop_index('ix_review_tasks_org_status_type', table_name='review_tasks')
    op.drop_table('review_tasks')
