"""Descriptive course difficulty and learning objectives (DEC-051).

Display and catalogue filtering only: the recommendation rule rec-v1 does not read these columns.
Autogenerated, with the CHECK constraint added by hand (autogenerate does not compare CHECK constraints).

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-15
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column('courses', sa.Column('difficulty', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('learning_objectives', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False))
    op.create_check_constraint(op.f('ck_courses_difficulty'), 'courses',
                               "difficulty IS NULL OR difficulty IN ('foundational', 'intermediate', 'advanced')")


def downgrade() -> None:
    op.drop_constraint(op.f('ck_courses_difficulty'), 'courses', type_='check')
    op.drop_column('courses', 'learning_objectives')
    op.drop_column('courses', 'difficulty')
