"""Accounts: registration ID, must-change-password flag, one-time set-password tokens (Phase 4A).

- ``users.registration_id`` (citext, optional): learner or staff identifier; unique per organisation when present;
  format ``^[A-Za-z0-9][A-Za-z0-9/-]{2,39}$`` (D4-2). Existing users stay null; the demo seed fills synthetic accounts.
- ``users.must_change_password`` (boolean, default false).
- ``password_reset_tokens``: administrator-issued one-time tokens for account setup or password reset
  (SECURITY_RESPONSIBLE_AI.md §3). Only the SHA-256 of the token is stored; ``used_at`` makes a token single-use.

Rollback drops the table, index and columns; no existing data depends on them.
Autogenerated, with the registration ID CHECK added by hand.

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-15
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

REGISTRATION_ID_CHECK = "registration_id IS NULL OR registration_id ~ '^[A-Za-z0-9][A-Za-z0-9/-]{2,39}$'"


def upgrade() -> None:
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('issued_by', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("purpose IN ('account_setup', 'password_reset')", name=op.f('ck_password_reset_tokens_purpose')),
    sa.CheckConstraint("token_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_password_reset_tokens_token_hash_is_sha256')),
    sa.CheckConstraint('used_at IS NULL OR used_at >= created_at', name=op.f('ck_password_reset_tokens_used_after_created')),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], name=op.f('fk_password_reset_tokens_issued_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_password_reset_tokens_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_index(op.f('ix_password_reset_tokens_organization_id'), 'password_reset_tokens', ['organization_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.add_column('users', sa.Column('registration_id', postgresql.CITEXT(), nullable=True))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_check_constraint(op.f('ck_users_registration_id_format'), 'users', REGISTRATION_ID_CHECK)
    op.create_index('uq_users_org_registration_id', 'users', ['organization_id', 'registration_id'], unique=True,
                    postgresql_where=sa.text('registration_id IS NOT NULL'))


def downgrade() -> None:
    op.drop_index('uq_users_org_registration_id', table_name='users', postgresql_where=sa.text('registration_id IS NOT NULL'))
    op.drop_constraint(op.f('ck_users_registration_id_format'), 'users', type_='check')
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'registration_id')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_organization_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
