"""Vertical slice 1: sessions, notice acknowledgements, assessments, evidence and estimates.

Autogenerated from the models, then reviewed by hand:
- deferred foreign keys are created after all tables (questions <-> question_versions cycle, actor columns);
- append-only triggers protect question versions, options, delivered questions, notice acknowledgements
  and the competency evidence ledger (void columns may be set once).

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-15
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('questions',
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending_validation'"), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('approved_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("origin IN ('ai_generated', 'human_authored', 'demo_seed')", name=op.f('ck_questions_origin')),
    sa.CheckConstraint("status <> 'approved' OR approved_version_id IS NOT NULL", name=op.f('ck_questions_approved_has_version')),
    sa.CheckConstraint("status IN ('pending_validation', 'failed_validation', 'validation_incomplete', 'in_review', 'approved', 'rejected', 'suspended', 'retired')", name=op.f('ck_questions_status')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_questions_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_index('ix_questions_org_status', 'questions', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_questions_organization_id'), 'questions', ['organization_id'], unique=False)
    op.create_table('assessments',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('job_role_id', sa.UUID(), nullable=True),
    sa.Column('blueprint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feedback_policy', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("feedback_policy IN ('score_only', 'correctness', 'correctness_and_explanations')", name=op.f('ck_assessments_feedback_policy')),
    sa.CheckConstraint("purpose <> 'pre' OR job_role_id IS NOT NULL", name=op.f('ck_assessments_pre_requires_job_role')),
    sa.CheckConstraint("purpose IN ('pre', 'practice', 'topic', 'competency')", name=op.f('ck_assessments_purpose')),
    sa.CheckConstraint("status <> 'published' OR published_at IS NOT NULL", name=op.f('ck_assessments_published_has_time')),
    sa.CheckConstraint("status IN ('draft', 'published', 'retired')", name=op.f('ck_assessments_status')),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], name=op.f('fk_assessments_job_role_id_job_roles')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_assessments_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], name=op.f('fk_assessments_published_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments'))
    )
    op.create_index('ix_assessments_org_status', 'assessments', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_assessments_organization_id'), 'assessments', ['organization_id'], unique=False)
    op.create_index('uq_assessments_one_published_pre_per_role', 'assessments', ['job_role_id'], unique=True, postgresql_where=sa.text("purpose = 'pre' AND status = 'published'"))
    op.create_table('notice_acknowledgements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notice_type', sa.Text(), nullable=False),
    sa.Column('notice_version', sa.Text(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("notice_type IN ('privacy_ai_use')", name=op.f('ck_notice_acknowledgements_notice_type')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_notice_acknowledgements_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notice_acknowledgements_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notice_acknowledgements')),
    sa.UniqueConstraint('user_id', 'notice_type', 'notice_version', name=op.f('uq_notice_acknowledgements_user_id_notice_type_notice_version'))
    )
    op.create_index(op.f('ix_notice_acknowledgements_organization_id'), 'notice_acknowledgements', ['organization_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idle_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reauthenticated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_hash', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("id ~ '^[0-9a-f]{64}$'", name=op.f('ck_sessions_id_is_sha256')),
    sa.CheckConstraint('idle_expires_at <= absolute_expires_at', name=op.f('ck_sessions_idle_within_absolute')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sessions_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_absolute_expires_at'), 'sessions', ['absolute_expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_organization_id'), 'sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('assessment_attempts',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'in_progress'"), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score_total', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rescored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("status <> 'scored' OR (scored_at IS NOT NULL AND score_total IS NOT NULL)", name=op.f('ck_assessment_attempts_scored_complete')),
    sa.CheckConstraint("status IN ('in_progress', 'submitted', 'scored', 'scoring_failed', 'expired')", name=op.f('ck_assessment_attempts_status')),
    sa.CheckConstraint('score_total IS NULL OR (score_total >= 0 AND score_total <= 1)', name=op.f('ck_assessment_attempts_score_total_range')),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_attempts_assessment_id_assessments')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_assessment_attempts_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assessment_attempts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_attempts'))
    )
    op.create_index(op.f('ix_assessment_attempts_organization_id'), 'assessment_attempts', ['organization_id'], unique=False)
    op.create_index('ix_assessment_attempts_user_assessment', 'assessment_attempts', ['user_id', 'assessment_id'], unique=False)
    op.create_index('uq_assessment_attempts_one_baseline', 'assessment_attempts', ['user_id'], unique=True, postgresql_where=sa.text('is_baseline'))
    op.create_index('uq_assessment_attempts_one_open', 'assessment_attempts', ['user_id', 'assessment_id'], unique=True, postgresql_where=sa.text("status = 'in_progress'"))
    op.create_table('question_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Text(), server_default=sa.text("'mcq_single'"), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Text(), nullable=False),
    sa.Column('difficulty_confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('edited_from_version_id', sa.UUID(), nullable=True),
    sa.Column('human_edited_fields', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('language', sa.Text(), server_default=sa.text("'en'"), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("content_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_question_versions_content_hash_format')),
    sa.CheckConstraint("difficulty IN ('foundational', 'intermediate', 'advanced')", name=op.f('ck_question_versions_difficulty')),
    sa.CheckConstraint("language = 'en'", name=op.f('ck_question_versions_language')),
    sa.CheckConstraint("question_type = 'mcq_single'", name=op.f('ck_question_versions_question_type')),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], name=op.f('fk_question_versions_competency_id_competencies')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_question_versions_created_by_users')),
    sa.ForeignKeyConstraint(['edited_from_version_id'], ['question_versions.id'], name=op.f('fk_question_versions_edited_from_version_id_question_versions')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_question_versions_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_versions_question_id_questions')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_question_versions_topic_id_topics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_versions')),
    sa.UniqueConstraint('question_id', 'version_number', name=op.f('uq_question_versions_question_id_version_number'))
    )
    op.create_index('ix_question_versions_competency_difficulty', 'question_versions', ['competency_id', 'difficulty'], unique=False)
    op.create_index('ix_question_versions_org_content_hash', 'question_versions', ['organization_id', 'content_hash'], unique=False)
    op.create_index(op.f('ix_question_versions_organization_id'), 'question_versions', ['organization_id'], unique=False)
    op.create_table('user_competencies',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('job_role_id', sa.UUID(), nullable=True),
    sa.Column('role_mapping_version', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('level_number', sa.SmallInteger(), nullable=True),
    sa.Column('evidence_band', sa.Text(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('method_version', sa.Text(), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_stale', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("evidence_band IN ('insufficient', 'low', 'medium', 'high')", name=op.f('ck_user_competencies_evidence_band')),
    sa.CheckConstraint('evidence_count > 0 OR score IS NULL', name=op.f('ck_user_competencies_no_score_without_evidence')),
    sa.CheckConstraint('evidence_count >= 0', name=op.f('ck_user_competencies_evidence_count_non_negative')),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 1)', name=op.f('ck_user_competencies_score_range')),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], name=op.f('fk_user_competencies_competency_id_competencies')),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], name=op.f('fk_user_competencies_job_role_id_job_roles')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_user_competencies_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_competencies_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_competencies')),
    sa.UniqueConstraint('user_id', 'competency_id', name=op.f('uq_user_competencies_user_id_competency_id'))
    )
    op.create_index(op.f('ix_user_competencies_organization_id'), 'user_competencies', ['organization_id'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('question_version_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_questions_assessment_id_assessments')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_assessment_questions_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], name=op.f('fk_assessment_questions_question_version_id_question_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_questions')),
    sa.UniqueConstraint('assessment_id', 'question_version_id', name=op.f('uq_assessment_questions_assessment_id_question_version_id'))
    )
    op.create_index(op.f('ix_assessment_questions_organization_id'), 'assessment_questions', ['organization_id'], unique=False)
    op.create_table('attempt_questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_version_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('option_order', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], name=op.f('fk_attempt_questions_attempt_id_assessment_attempts')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_attempt_questions_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], name=op.f('fk_attempt_questions_question_version_id_question_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempt_questions')),
    sa.UniqueConstraint('attempt_id', 'position', name=op.f('uq_attempt_questions_attempt_id_position')),
    sa.UniqueConstraint('attempt_id', 'question_version_id', name=op.f('uq_attempt_questions_attempt_id_question_version_id'))
    )
    op.create_index(op.f('ix_attempt_questions_organization_id'), 'attempt_questions', ['organization_id'], unique=False)
    op.create_table('question_options',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('question_version_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("label IN ('A', 'B', 'C', 'D')", name=op.f('ck_question_options_label')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_question_options_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], name=op.f('fk_question_options_question_version_id_question_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_options')),
    sa.UniqueConstraint('question_version_id', 'label', name=op.f('uq_question_options_question_version_id_label'))
    )
    op.create_index(op.f('ix_question_options_organization_id'), 'question_options', ['organization_id'], unique=False)
    op.create_index('uq_question_options_one_correct', 'question_options', ['question_version_id'], unique=True, postgresql_where=sa.text('is_correct'))
    op.create_table('answers',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_version_id', sa.UUID(), nullable=False),
    sa.Column('selected_option_id', sa.UUID(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rescore_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], name=op.f('fk_answers_attempt_id_assessment_attempts')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_answers_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], name=op.f('fk_answers_question_version_id_question_versions')),
    sa.ForeignKeyConstraint(['selected_option_id'], ['question_options.id'], name=op.f('fk_answers_selected_option_id_question_options')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers')),
    sa.UniqueConstraint('attempt_id', 'question_version_id', name=op.f('uq_answers_attempt_id_question_version_id'))
    )
    op.create_index(op.f('ix_answers_organization_id'), 'answers', ['organization_id'], unique=False)
    op.create_table('competency_evidence',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.Text(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=True),
    sa.Column('answer_id', sa.UUID(), nullable=True),
    sa.Column('question_version_id', sa.UUID(), nullable=True),
    sa.Column('difficulty_weight', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('adjusted_level_number', sa.SmallInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.UUID(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("evidence_type <> 'assessment_answer' OR (attempt_id IS NOT NULL AND answer_id IS NOT NULL AND question_version_id IS NOT NULL AND difficulty_weight IS NOT NULL AND is_correct IS NOT NULL)", name=op.f('ck_competency_evidence_answer_evidence_fields')),
    sa.CheckConstraint("evidence_type <> 'human_adjustment' OR (adjusted_level_number IS NOT NULL AND reason IS NOT NULL AND created_by IS NOT NULL AND created_by <> user_id)", name=op.f('ck_competency_evidence_adjustment_fields')),
    sa.CheckConstraint("evidence_type IN ('assessment_answer', 'human_adjustment')", name=op.f('ck_competency_evidence_evidence_type')),
    sa.CheckConstraint('(voided_at IS NULL) = (void_reason IS NULL)', name=op.f('ck_competency_evidence_void_reason_with_void')),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('fk_competency_evidence_answer_id_answers')),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], name=op.f('fk_competency_evidence_attempt_id_assessment_attempts')),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], name=op.f('fk_competency_evidence_competency_id_competencies')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_competency_evidence_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_competency_evidence_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], name=op.f('fk_competency_evidence_question_version_id_question_versions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_competency_evidence_user_id_users')),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], name=op.f('fk_competency_evidence_voided_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competency_evidence'))
    )
    op.create_index('ix_competency_evidence_active', 'competency_evidence', ['user_id', 'competency_id'], unique=False, postgresql_where=sa.text('voided_at IS NULL'))
    op.create_index('ix_competency_evidence_answer', 'competency_evidence', ['answer_id'], unique=False)
    op.create_index(op.f('ix_competency_evidence_organization_id'), 'competency_evidence', ['organization_id'], unique=False)
    # Deferred foreign keys: actor columns and the questions <-> question_versions cycle.
    op.create_foreign_key(op.f('fk_questions_approved_version_id_question_versions'), 'questions', 'question_versions', ['approved_version_id'], ['id'])
    op.create_foreign_key(op.f('fk_questions_created_by_users'), 'questions', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_questions_current_version_id_question_versions'), 'questions', 'question_versions', ['current_version_id'], ['id'])
    op.create_foreign_key(op.f('fk_questions_updated_by_users'), 'questions', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_assessments_created_by_users'), 'assessments', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_assessments_updated_by_users'), 'assessments', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_assessment_attempts_created_by_users'), 'assessment_attempts', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_assessment_attempts_updated_by_users'), 'assessment_attempts', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_user_competencies_created_by_users'), 'user_competencies', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_user_competencies_updated_by_users'), 'user_competencies', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_assessment_questions_created_by_users'), 'assessment_questions', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_assessment_questions_updated_by_users'), 'assessment_questions', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_answers_created_by_users'), 'answers', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_answers_updated_by_users'), 'answers', 'users', ['updated_by'], ['id'])

    op.execute(_TRIGGERS_SQL)

    # DEC-045: allow 'demo_seed' as a course-competency mapping method so demo rows never claim human review.
    op.drop_constraint(op.f("ck_course_competencies_method"), "course_competencies", type_="check")
    op.create_check_constraint(op.f("ck_course_competencies_method"), "course_competencies",
                               "method IN ('human', 'keyword_rule', 'demo_seed')")


def downgrade() -> None:
    op.execute("DELETE FROM course_competencies WHERE method = 'demo_seed'")
    op.drop_constraint(op.f("ck_course_competencies_method"), "course_competencies", type_="check")
    op.create_check_constraint(op.f("ck_course_competencies_method"), "course_competencies",
                               "method IN ('human', 'keyword_rule')")
    op.execute(_DROP_TRIGGERS_SQL)
    op.drop_constraint(op.f('fk_questions_approved_version_id_question_versions'), 'questions', type_='foreignkey')
    op.drop_constraint(op.f('fk_questions_created_by_users'), 'questions', type_='foreignkey')
    op.drop_constraint(op.f('fk_questions_current_version_id_question_versions'), 'questions', type_='foreignkey')
    op.drop_constraint(op.f('fk_questions_updated_by_users'), 'questions', type_='foreignkey')
    op.drop_constraint(op.f('fk_assessments_created_by_users'), 'assessments', type_='foreignkey')
    op.drop_constraint(op.f('fk_assessments_updated_by_users'), 'assessments', type_='foreignkey')
    op.drop_constraint(op.f('fk_assessment_attempts_created_by_users'), 'assessment_attempts', type_='foreignkey')
    op.drop_constraint(op.f('fk_assessment_attempts_updated_by_users'), 'assessment_attempts', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_competencies_created_by_users'), 'user_competencies', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_competencies_updated_by_users'), 'user_competencies', type_='foreignkey')
    op.drop_constraint(op.f('fk_assessment_questions_created_by_users'), 'assessment_questions', type_='foreignkey')
    op.drop_constraint(op.f('fk_assessment_questions_updated_by_users'), 'assessment_questions', type_='foreignkey')
    op.drop_constraint(op.f('fk_answers_created_by_users'), 'answers', type_='foreignkey')
    op.drop_constraint(op.f('fk_answers_updated_by_users'), 'answers', type_='foreignkey')
    op.drop_index(op.f('ix_competency_evidence_organization_id'), table_name='competency_evidence')
    op.drop_index('ix_competency_evidence_answer', table_name='competency_evidence')
    op.drop_index('ix_competency_evidence_active', table_name='competency_evidence', postgresql_where=sa.text('voided_at IS NULL'))
    op.drop_table('competency_evidence')
    op.drop_index(op.f('ix_answers_organization_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index('uq_question_options_one_correct', table_name='question_options', postgresql_where=sa.text('is_correct'))
    op.drop_index(op.f('ix_question_options_organization_id'), table_name='question_options')
    op.drop_table('question_options')
    op.drop_index(op.f('ix_attempt_questions_organization_id'), table_name='attempt_questions')
    op.drop_table('attempt_questions')
    op.drop_index(op.f('ix_assessment_questions_organization_id'), table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_index(op.f('ix_user_competencies_organization_id'), table_name='user_competencies')
    op.drop_table('user_competencies')
    op.drop_index(op.f('ix_question_versions_organization_id'), table_name='question_versions')
    op.drop_index('ix_question_versions_org_content_hash', table_name='question_versions')
    op.drop_index('ix_question_versions_competency_difficulty', table_name='question_versions')
    op.drop_table('question_versions')
    op.drop_index('uq_assessment_attempts_one_open', table_name='assessment_attempts', postgresql_where=sa.text("status = 'in_progress'"))
    op.drop_index('uq_assessment_attempts_one_baseline', table_name='assessment_attempts', postgresql_where=sa.text('is_baseline'))
    op.drop_index('ix_assessment_attempts_user_assessment', table_name='assessment_attempts')
    op.drop_index(op.f('ix_assessment_attempts_organization_id'), table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_organization_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_absolute_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_notice_acknowledgements_organization_id'), table_name='notice_acknowledgements')
    op.drop_table('notice_acknowledgements')
    op.drop_index('uq_assessments_one_published_pre_per_role', table_name='assessments', postgresql_where=sa.text("purpose = 'pre' AND status = 'published'"))
    op.drop_index(op.f('ix_assessments_organization_id'), table_name='assessments')
    op.drop_index('ix_assessments_org_status', table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_questions_organization_id'), table_name='questions')
    op.drop_index('ix_questions_org_status', table_name='questions')
    op.drop_table('questions')


_TRIGGERS_SQL = r"""
CREATE FUNCTION forbid_update_delete() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'append_only: % rows cannot be modified or deleted', TG_TABLE_NAME USING ERRCODE = '23514';
END $$;

CREATE TRIGGER trg_question_versions_append_only BEFORE UPDATE OR DELETE ON question_versions
  FOR EACH ROW EXECUTE FUNCTION forbid_update_delete();
CREATE TRIGGER trg_question_options_append_only BEFORE UPDATE OR DELETE ON question_options
  FOR EACH ROW EXECUTE FUNCTION forbid_update_delete();
CREATE TRIGGER trg_attempt_questions_append_only BEFORE UPDATE OR DELETE ON attempt_questions
  FOR EACH ROW EXECUTE FUNCTION forbid_update_delete();
CREATE TRIGGER trg_notice_acknowledgements_append_only BEFORE UPDATE OR DELETE ON notice_acknowledgements
  FOR EACH ROW EXECUTE FUNCTION forbid_update_delete();

CREATE FUNCTION competency_evidence_void_once() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'append_only: competency_evidence rows cannot be deleted' USING ERRCODE = '23514';
  END IF;
  IF OLD.voided_at IS NOT NULL
     OR (to_jsonb(NEW) - 'voided_at' - 'voided_by' - 'void_reason')
        IS DISTINCT FROM (to_jsonb(OLD) - 'voided_at' - 'voided_by' - 'void_reason') THEN
    RAISE EXCEPTION 'append_only: only the void columns of competency_evidence may be set, once'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER trg_competency_evidence_void_once BEFORE UPDATE OR DELETE ON competency_evidence
  FOR EACH ROW EXECUTE FUNCTION competency_evidence_void_once();
"""

_DROP_TRIGGERS_SQL = """
DROP TRIGGER IF EXISTS trg_competency_evidence_void_once ON competency_evidence;
DROP TRIGGER IF EXISTS trg_notice_acknowledgements_append_only ON notice_acknowledgements;
DROP TRIGGER IF EXISTS trg_attempt_questions_append_only ON attempt_questions;
DROP TRIGGER IF EXISTS trg_question_options_append_only ON question_options;
DROP TRIGGER IF EXISTS trg_question_versions_append_only ON question_versions;
DROP FUNCTION IF EXISTS competency_evidence_void_once();
DROP FUNCTION IF EXISTS forbid_update_delete();
"""
