"""Learning experience tables (Phase 4B; DATA_MODEL.md §8, approved lessons proposal with Phase 4 amendments).

- ``course_modules`` and ``lessons`` hold course structure. Lesson bodies are Markdown written for this platform
  (``content_kind='inline_markdown'``); ``learning_material`` bodies arrive with document ingestion (Phase 5).
- ``course_prerequisites`` are advisory: the learning path orders them first, nothing is locked.
- ``progress_records`` hold the current state per learner and target. Completion is self-reported by the learner
  ("Mark as complete") and says so (``status_source``); it is never presented as assessed competence.
- ``learning_activities`` is append-only (trigger) and carries identifiers and counts only.
- ``learning_paths`` / ``learning_path_items`` are generated by rule ``path-v1`` (DEC recorded) from ``rec-v1``.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, Index, Integer, Text, UniqueConstraint, func, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.db import Base, StandardColumnsMixin, TenantMixin, check_in
from app.core.vocab import ACTIVE_INACTIVE

LESSON_TYPES = ("reading", "worked_example", "practice_check")
CONTENT_KINDS = ("inline_markdown", "learning_material")
PROGRESS_TARGETS = ("course", "lesson", "learning_path_item")
PROGRESS_STATUSES = ("not_started", "in_progress", "completed")
STATUS_SOURCES = ("system", "self_reported", "administrator")
ACTIVITY_TYPES = ("course_started", "lesson_opened", "lesson_completed", "course_completed", "path_generated")
PATH_STATUSES = ("active", "superseded")
PATH_ITEM_TYPES = ("course", "no_content_placeholder")


class CourseModule(StandardColumnsMixin, TenantMixin, Base):
    __tablename__ = "course_modules"

    course_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("courses.id"), nullable=False, index=True)
    position: Mapped[int] = mapped_column(Integer, nullable=False)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    summary: Mapped[str | None] = mapped_column(Text)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'active'"))

    __table_args__ = (
        CheckConstraint(check_in("status", ACTIVE_INACTIVE), name="status"),
        CheckConstraint("position > 0", name="position_positive"),
        UniqueConstraint("course_id", "position"),
    )


class Lesson(StandardColumnsMixin, TenantMixin, Base):
    __tablename__ = "lessons"

    module_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("course_modules.id"), nullable=False, index=True)
    course_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("courses.id"), nullable=False, index=True)
    position: Mapped[int] = mapped_column(Integer, nullable=False)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    lesson_type: Mapped[str] = mapped_column(Text, nullable=False)
    estimated_minutes: Mapped[int] = mapped_column(Integer, nullable=False)
    content_kind: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'inline_markdown'"))
    body_markdown: Mapped[str | None] = mapped_column(Text)
    learning_material_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))  # FK arrives in Phase 5
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'active'"))

    __table_args__ = (
        CheckConstraint(check_in("lesson_type", LESSON_TYPES), name="lesson_type"),
        CheckConstraint(check_in("content_kind", CONTENT_KINDS), name="content_kind"),
        CheckConstraint(check_in("status", ACTIVE_INACTIVE), name="status"),
        CheckConstraint("position > 0", name="position_positive"),
        CheckConstraint("estimated_minutes BETWEEN 1 AND 240", name="estimated_minutes_range"),
        CheckConstraint("content_kind <> 'inline_markdown' OR body_markdown IS NOT NULL", name="inline_body_present"),
        UniqueConstraint("module_id", "position"),
    )


class CoursePrerequisite(StandardColumnsMixin, TenantMixin, Base):
    __tablename__ = "course_prerequisites"

    course_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("courses.id"), nullable=False, index=True)
    prerequisite_course_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("courses.id"), nullable=False)

    __table_args__ = (
        CheckConstraint("course_id <> prerequisite_course_id", name="not_self"),
        UniqueConstraint("course_id", "prerequisite_course_id"),
    )


class ProgressRecord(StandardColumnsMixin, TenantMixin, Base):
    __tablename__ = "progress_records"

    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    target_type: Mapped[str] = mapped_column(Text, nullable=False)
    target_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    course_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("courses.id"))
    title_snapshot: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False)
    status_source: Mapped[str] = mapped_column(Text, nullable=False)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    resume_lesson_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("lessons.id"))

    __table_args__ = (
        CheckConstraint(check_in("target_type", PROGRESS_TARGETS), name="target_type"),
        CheckConstraint(check_in("status", PROGRESS_STATUSES), name="status"),
        CheckConstraint(check_in("status_source", STATUS_SOURCES), name="status_source"),
        CheckConstraint("status <> 'completed' OR completed_at IS NOT NULL", name="completed_has_timestamp"),
        CheckConstraint("resume_lesson_id IS NULL OR target_type = 'course'", name="resume_only_for_courses"),
        UniqueConstraint("user_id", "target_type", "target_id"),
        Index("ix_progress_records_user_status", "user_id", "status"),
        Index("ix_progress_records_user_course", "user_id", "course_id"),
    )


class LearningActivity(TenantMixin, Base):
    """Append-only (trigger ``trg_learning_activities_append_only``). Metadata holds identifiers and counts only."""

    __tablename__ = "learning_activities"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    activity_type: Mapped[str] = mapped_column(Text, nullable=False)
    target_type: Mapped[str] = mapped_column(Text, nullable=False)
    target_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    # Keys are identifiers and counts; never free text (DATA_MODEL.md LearningActivity).
    activity_metadata: Mapped[dict] = mapped_column("metadata", JSONB, nullable=False, server_default=text("'{}'::jsonb"))
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())

    __table_args__ = (
        CheckConstraint(check_in("activity_type", ACTIVITY_TYPES), name="activity_type"),
        Index("ix_learning_activities_user_occurred", "user_id", "occurred_at"),
    )


class LearningPath(StandardColumnsMixin, TenantMixin, Base):
    __tablename__ = "learning_paths"

    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False, index=True)
    job_role_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("job_roles.id"))
    status: Mapped[str] = mapped_column(Text, nullable=False)
    rule_version: Mapped[str] = mapped_column(Text, nullable=False)
    input_snapshot_hash: Mapped[str] = mapped_column(Text, nullable=False)
    generated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    __table_args__ = (
        CheckConstraint(check_in("status", PATH_STATUSES), name="status"),
        CheckConstraint("input_snapshot_hash ~ '^[0-9a-f]{64}$'", name="input_hash_is_sha256"),
        Index("uq_learning_paths_user_active", "user_id", unique=True, postgresql_where=text("status = 'active'")),
    )


class LearningPathItem(StandardColumnsMixin, TenantMixin, Base):
    __tablename__ = "learning_path_items"

    learning_path_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("learning_paths.id"), nullable=False, index=True)
    position: Mapped[int] = mapped_column(Integer, nullable=False)
    item_type: Mapped[str] = mapped_column(Text, nullable=False)
    target_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    gap_competency_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("competencies.id"))
    reasons: Mapped[list] = mapped_column(JSONB, nullable=False)
    provenance: Mapped[dict] = mapped_column(JSONB, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'not_started'"))
    status_source: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'system'"))
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        CheckConstraint(check_in("item_type", PATH_ITEM_TYPES), name="item_type"),
        CheckConstraint(check_in("status", PROGRESS_STATUSES), name="status"),
        CheckConstraint(check_in("status_source", STATUS_SOURCES), name="status_source"),
        CheckConstraint("item_type <> 'course' OR target_id IS NOT NULL", name="course_item_has_target"),
        CheckConstraint("position > 0", name="position_positive"),
        UniqueConstraint("learning_path_id", "position"),
    )
